### DISCUSSION TITLE
Make UI available under a sub path

### DISCUSSION THREAD

**Discussion by IceflowRE** [wg-easy/wg-easy#1002] [General]
I would like to host the ui iin a subpath like `example.com/wg-easy`.

I could not find any option to already do it now.

**Comment by pheiduck** [comment]
You can use a subdomain for that case.

**Comment by IceflowRE** [comment]
> You can use a subdomain for that case.

That was not the request. I know i can use a subdomain, i explicitly asked for a subpath.

**Comment by pheiduck** [comment]
> > You can use a subdomain for that case.
> 
> That was not the request. I know i can use a subdomain, i explicitly asked for a subpath.

Well, it does not an Issue specific to wg-easy

**Comment by IceflowRE** [comment]
~~Maintainer not interested in a solution.~~
Not true, just my incompetence.

**Reply by eandersons** [reply]
Just use your favourite search engine and look up information on how to serve an application with a subpath with a web server/reverse proxy of your choice, because if you want to do something extraordinary in a lot of cases you are on your own, unless someone has already done something similar.

Besides, you did not provide enough information to begin with. For example, what you have already tried, which web server/reverse proxy you are using/are planning to use.

**Reply by IceflowRE** [reply]
> Just use your favourite search engine and look up information on how to serve an application with a subpath with a web server/reverse proxy of your choice, because if you want to do something extraordinary in a lot of cases you are on your own, unless someone has already done something similar.

The proxy is pretty irrelevant if the wg-easy server does not agnostic it, all files it requests (images/qr code scgs) are not requested with that sub path and will not be found.

> Besides, you did not provide enough information to begin with. For example, what you have already tried, which web server/reverse proxy you are using/are planning to use.

The web server/reverse proxy is irrelevant.

**Reply by peterlewis** [reply]
@IceflowRE Thank you for your suggestion. If URLs can be refined to accommodate sub-path installs then a PR in this area would be appreciated and welcomed! 🙏

**Reply by eandersons** [reply]
@IceflowRE, with a little bit of search effort this can be achieved.

For example, with nginx ([`rewrite`](https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite) directive is the important bit here):

```nginx
server {
  ...

  location /wg-easy/ { 
    rewrite ^/wg-easy/(.*) /$1 break;
    ...
    proxy_pass http://127.0.0.1:51821;
    include /etc/nginx/include/proxy_headers.conf;
  }

  ...
}
```

With the above everything is working fine without any changes in WireGuard Easy:

![image](https://github.com/wg-easy/wg-easy/assets/9976861/a5eacb33-5b2f-4e4e-8442-5c3dcf31cbfd)

I guess something similar should be achievable with other reverse proxy servers as well.

> The web server/reverse proxy is irrelevant.

So in the end the used proxy server is quite relevant.

**Reply by IceflowRE** [reply]
Good catch, i was wrong here!
For the record
```
proxy_cookie_path / /wg-easy/;
```
is required.

**Comment by CosasDePuma** [comment]
If someone is using **Traefik**, this is the way to proceed:

```yml
labels:
      traefik.enable: true
      # Web UI
      traefik.http.routers.wg-easy.rule: Host(`${WG_DOMAIN:-example.tld}`) && PathPrefix(`${WG_PATH:-/vpn}/`)
      traefik.http.routers.wg-easy.entrypoints: https
      traefik.http.routers.wg-easy.service: wg-easy
      traefik.http.routers.wg-easy.middlewares: wg-easy@docker
      traefik.http.services.wg-easy.loadbalancer.server.port: 51821
      traefik.http.middlewares.wg-easy.stripprefix.prefixes: "${WG_PATH:-/vpn}"
      # WireGuard VPN
      traefik.udp.routers.wg-easy.entrypoints: vpn
      traefik.udp.routers.wg-easy.service: wg-easy
      traefik.udp.services.wg-easy.loadbalancer.server.port: 51820
```
