### DISCUSSION TITLE
IPVLAN on Docker dont let me access internet via the VPN

### DISCUSSION THREAD

**Discussion by rohoal1012** [wg-easy/wg-easy#1051] [General]
When I configure that wg-easy goes through a IPVLAN network i cant access to the internet via vpn but yes to my local network, why is this happening?

DOCKER-COMPOSE.YML
```yml
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=####################################
      - PASSWORD=###########
      - PORT=80
      - WG_DEFAULT_DNS=112.0.0.3
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /dockervault/wireguard-easy:/etc/wireguard
    networks:
       ipvlan:
         ipv4_address: 112.0.0.4
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
    ipvlan:
     external: true
     name: ipvlan
```
