### DISCUSSION TITLE
WG-Easy with Pi-Hole & Pi-Hole DHCP

### DISCUSSION THREAD

**Discussion by MaximumPotato** [wg-easy/wg-easy#1058] [Q&A] [answered]
Hi!

I have been slowly working on setting up WG_Easy and Pi-Hole on my home network, learning as I go. I have gotten both running individually, each in a docker container, and now I am looking to make them work together. There is an issue on my end that makes this less straightforward than just following the [Wiki page](https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole) on this topic.

My ISP provided Modem/Router will not allow me to point to a DNS server within my own network, which is either a known issue with the hardware or an intentional design choice. Nobody seems confident which is the case. I am able to get around this by using the Pi-Hole setup as the networks DHCP server, while disabling the DHCP server on the ISP hardware. This setup necessitates running the Pi-Hole container with 'network_mode' set to 'host'. I believe the example on the Wiki assumes that both of the containers are running within Dockers closed subnet.

I am not sure how to properly configure the setup given my circumstances. I am going to start making changes to the example script to see if I can get it working, but in the mean time I would be more than happy if somebody more experienced could explain it to me so I can use some of my Saturday for other things. I'll update if I make any headway on my own.

_**Edit:**_

For reference, here are my docker_compose files.

**wg-easy:**
```
version: "3.8"

services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy

    environment:
      - PASSWORD=<MyPassword>
      - WG_HOST=<MyHost>

      # Unsure how to configure these, playing with different settings
      - WG_DEFAULT_DNS=localhost
      - WG_DEFAULT_ADDRESS=192.168.0.1

    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules
    network_mode: host
    # ports:
    #   - "51820:51820/udp"
    #   - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # These cause issues when network_mode is host, commented them out for now
    # sysctls:
    #   - net.ipv4.ip_forward=1
    #   - net.ipv4.conf.all.src_valid_mark=1
```

**pi-hole:**
```
version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    #   - "80:80/tcp"
    environment:
      TZ: <MyTimezone>
      WEBPASSWORD: <MyPassword>
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped```

**Comment by MaximumPotato** [comment]
I was thinking I could just flip wireguard into host mode as well, but I am unsure if that would introduce security issues into the setup.

Edit: Nope that didn't work.

**Comment by pheiduck** [comment]
I have Pi-hole (DHCP and DNS) as none docker installed, everything works w/ wg-easy.

**Reply by MaximumPotato** [reply]
What do you mean by "none docker"?

**Reply by pheiduck** [reply]
It's directly installed on the system.

**Reply by MaximumPotato** [reply]
Gotcha. Is your wg-easy install in a docker container? If so, could you show me the compose file? That might help me understand what I'm doing wrong.

**Reply by pheiduck** [reply]
> Is your wg-easy install in a docker container?

Yes.

**Reply by MaximumPotato** [reply]
May I see your compose file for that?

**Reply by MaximumPotato** [reply]
I'm trying to figure out what exactly you have configured that I haven't tried.

**Comment by MaximumPotato** [comment]
Figured I'd try it like this, somewhat expectedly didn't work.

```
version: "3.8"

services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy

    environment:
      - PASSWORD=<MyPassword>
      - WG_HOST=<MyHost>

      - WG_DEFAULT_DNS=<RaspberryPiiPOnNetwork>

    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Comment by MaximumPotato** [comment]
This particular setup with WG_DEFAULT_DNS and WG_DEFAULT_ADDRESS set to the ip of the Pi causes a connected client to rapidly reload whatever page they try and connect to. That's progress at least!

```
version: "3.8"

services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy

    environment:
      - PASSWORD=<MyPassword>
      - WG_HOST=<ExternalIP>

      # Wireguard and the PiHole are set up on the same Raspberry Pi
      - WG_DEFAULT_DNS= # This should be either the Raspberry Pi IP on the network, e.g. 192.168.0.x, or alternatively localhost? I think?
      - WG_DEFAULT_ADDRESS= # Not entirely sure 

    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
```

**Comment by MaximumPotato** [comment, marked as answer]
Alright well it turns out that in my tunnel-visioning this as a configuration issue with one of the containers, I neglected to check other aspects of the network. I dealt with the weirdness involving my modem not respecting in-network DNS servers _after_ I first got Wireguard running. One of the troubleshooting steps for that involved changing the internal static IP of the Raspberry Pi (See "Side Quest: Restoring Internet Access to the Pi-Hole." on [this page](https://johnbeales.com/2023/make-a-pi-hole-work-with-a-bell-giga-hub/)). So when I first set up Wireguard, I had forwarded the port it needs to a different IP within my network via my router.

This has been a refresher in stepping back to chill out for a bit when hitting my head against a problem that I don't entirely understand. That likely would have been more productive to do _before_ trying random values for several hours. The docker compose file I'm using now has exactly one extra line when compared to my original one: Setting the environment variable WG_DEFAULT_DNS to the static internal IP of my Raspberry Pi on which both Wireguard & Pi-Hole live. Kind of confused as to why this wouldn't be 127.0.0.1 or localhost instead, but assuming that's just related to Wireguard running inside of Dockers subnet. With network_mode set to host as I was trying in my replies here, that change might be necessary. Not really concerned about that now though because things appear to be working as they should!

Here's my final Docker Compose file:


```
version: "3.8"

services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped

    environment:
      - PASSWORD=<MyPassword>
      - WG_HOST=<MyExternalIP>
      - WG_DEFAULT_DNS=<RaspberryPiInternalIP> (192.168.0.**)
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules
    
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
