### DISCUSSION TITLE
Problem with local network access 172.16.0.0/24

### DISCUSSION THREAD

**Discussion by Wern-rm** [wg-easy/wg-easy#1076] [Q&A]
Please tell me, I set up Wg-easy using the following docker-compose.yml, there is a connection, ping **10.8.8.1** is there, but devices on the local network **172.16.0.10**, for example, or **172.16.0.12** do not have ping and ssh access either. 

What did I miss in my setup?

My docker-compose.yml
```
services:
    wg-easy:
        image: ghcr.io/wg-easy/wg-easy:13
        container_name: wg-easy
        volumes:
            - /opt/wg-easy/etc:/etc/wireguard
        ports:
            - "8888:8888/udp"
            - "8093:8093/tcp"
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        environment:
            - LANG=en
            - WG_HOST=<my_static_ip>
            - PASSWORD=<my_password>
            - PORT=8093
            - WG_PORT=8888
            - WG_DEFAULT_ADDRESS=10.8.8.x
            - WG_DEFAULT_DNS=8.8.8.8, 8.8.4.4
            - WG_MTU=1420
            - WG_ALLOWED_IPS=172.16.10.0/24, 10.8.8.0/24
            - WG_PERSISTENT_KEEPALIVE=25
            - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
            - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
            - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
            - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
            - UI_TRAFFIC_STATS=true
            - UI_CHART_TYPE=1
            - WEBUI_HOST=0.0.0.0
```

How do I access the LAN 172.16.0.0/24?
