### DISCUSSION TITLE
Access to LAN blocked by UFW when connected via WireGuard

### DISCUSSION THREAD

**Discussion by kevbire** [wg-easy/wg-easy#1159] [Q&A]
Hi all,

I am unable to access network services on my local network such as Technitium (192.168.50.55:5380) or WG Easy portal (192.168.50.55:51821) connected via WireGuard however I am able to connect to the internet.

I have found that temporarily disabling UFW (Ubuntu) allows me to connect to local IP addresses when connected via WireGuard however I am keen to identify and implement a more specific rule so that I can keep the firewall enabled.

**Diagram**
![image](https://github.com/wg-easy/wg-easy/assets/175109074/2eb167a0-8ca2-4cb7-9bd1-64a910cf63ad)

**UFW Rules**

```
To                         Action      From
--                         ------      ----
51820/udp                  ALLOW       Anywhere                  
Anywhere on docker0        ALLOW       Anywhere                  
5353/udp                   ALLOW       Anywhere                  
4000/tcp                   ALLOW       Anywhere                  
4000/udp                   ALLOW       Anywhere                  
Anywhere                   ALLOW       10.0.0.0/8                
51820/udp (v6)             ALLOW       Anywhere (v6)             
Anywhere (v6) on docker0   ALLOW       Anywhere (v6)             
5353/udp (v6)              ALLOW       Anywhere (v6)             
4000/tcp (v6)              ALLOW       Anywhere (v6)             
4000/udp (v6)              ALLOW       Anywhere (v6)             

Anywhere                   ALLOW OUT   Anywhere on docker0       
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on docker0  
```

**WG Easy Config**
```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=connect.MYDOMAIN.com

      # Optional:
      # - PASSWORD=foobar123 (deprecated, see readme)
      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=0.0.0.0/0, 192.168.50.0/24, 10.0.0.0/8
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman 
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Docker Setup**
```
WG Easy 20.13.1
Portainer 
Docker 27.07.3
Ubuntu 24.04 TLS
```

I'd greatly appreciate some advice on how to reconfigure the app and/or firewall so that I can access local services.

Thanks!
