### DISCUSSION TITLE
Only one query from wg-easy server instead of every connected client IP/hostname

### DISCUSSION THREAD

**Discussion by NetRat88** [wg-easy/wg-easy#1168] [Q&A] [answered]
**Describe the bug**
Dear community,

the initial post is already closed and I would like to ask for a solution to show every connected client hostname in pi-hole running in the same docker-compose.yaml stack with the following configuration.

**To Reproduce**
Use this docker-compose.yaml to reproduce:

```docker
version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wireguard-easy
    hostname: wireguard-docker
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true" #nur Monitoring auf Updates durch Watchtower und kein Auto-Update
    volumes:
      - /home/pi/wireguard-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    env_file:
      - stack.env
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=${WG_HOST}
      # ⚠️ Change the Web UI Password:
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole-docker
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true" #nur Monitoring auf Updates durch Watchtower und kein Auto-Update
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "82:80/tcp" # Admin Web Port
    env_file:
      - stack.env
    environment:
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - FTLCONF_LOCAL_IPV4=${HOST_IP}
    # Volumes store your data between container upgrades
    volumes:
      - /home/pi/pihole/etc-pihole:/etc/pihole
      - /home/pi/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: always
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3
networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
```

**Expected behavior**
I would expect that every client send there querys with the clients IP address 10.8.0.x instead of only one query from the wg-easy server with IP address 10.8.1.2 like in the issue report https://github.com/wg-easy/wg-easy/issues/971
The same beavior you have with pivpn for example.

**Screenshots**
![wg-easy_pihole_hostname](https://github.com/wg-easy/wg-easy/assets/6528507/73b16db0-3bff-4862-b833-8f975202d2b9)

**Comment by Zer0Rem** [comment]
Same Problem but with Adguard Home. I would love to see the peers IPs instead of the wg easy docker IP. 

This is my docker-compose.yaml:

version: "3.8"

```
services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=HIDDEN

      # ⚠️ Change the Web UI Password:
      - PASSWORD=HIDDEN

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_ALLOWED_IPS=192.168.2.0/24, 10.8.1.0/24
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2


  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    # Für DHCP wird empfohlen, diese Ports zu entfernen und stattdessen hinzuzufügen: network_mode: "host"
    restart: always
    ports:
      # DNS-Ports
      - "53:53/tcp"
      - "53:53/udp"
      - "784:784/udp"
      - "853:853/tcp"   
      - "7200:80/tcp"
      - "4435:443/tcp"
      # Dashboard
      - "3000:3000/tcp"
    environment:
      TZ: Europe/Berlin
    volumes:
      - /DATA/AppData/AdGuardHome/Work:/opt/adguardhome/work
      - /DATA/AppData/AdGuardHome/Config:/opt/adguardhome/conf
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3

networks:
   wg-easy:
     ipam:
       config:
         - subnet: 10.8.1.0/24
```

**Reply by fer-ri** [reply]
Do you found solution? I'm using Adguard as well. Thanks

**Reply by Zer0Rem** [reply]
No, unfortunately I haven't found a solution yet, I'll try a few more things later and will update you if it works

**Reply by fer-ri** [reply]
> No, unfortunately I haven't found a solution yet, I'll try a few more things later and will update you if it works


Great, thanks. I'll update here too if I found it

**Reply by eandersons** [reply]
VPN requests are routed through WireGuard Easy container's interface, hence its IP address/hostname is logged in Pi-hole for queries that originate from VPN users, so probably there is nothing much that can be done.

**Reply by fer-ri** [reply]
Yes, I wish that WG also send something like CF did with their header with original client IP.

**Reply by NetRat88** [reply]
On Reddit it seems to be a solution existing for some people. But I couldn't get this up and running.
https://www.reddit.com/r/WireGuard/comments/1ahb2og/comment/koreyel/

I tried to set the following rule as environement variable. After adding this it shows up every client ip/hostname BUT through the tunnel there was no internet connection possible and I also could not reach the local network devices by hostname or IP address.

WG_POST_UP="iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;"

But maybe someone else has more luck to get this up and running.

BG NetRat

**Reply by NetRat88** [reply]
Does anybody get this up and running with working internet connection?

**Reply by pavholm** [reply, marked as answer]
@NetRat88 
try to run these commands on the host:

```
iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
ip route add 10.8.0.0/24 via 10.8.1.2
```

where `10.8.0.0/24` - wg-easy default address, `eth0` - name of interface with internet (can find it by running `ip route show` in default section), `10.8.1.2` - IP of docker container (ipv4_address in examples above).

you have to run these commands on every server start or automate it via systemd (I haven't found the best solution yet, but it's not the main problem).

**Reply by NetRat88** [reply]
Amazing! This is working now! Thanks a lot @pavholm for this tip!

**Reply by NetRat88** [reply]
@pavholm 
It seems that since the update of pi-hole to v6.2.2 the lines:

`iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
ip route add 10.8.0.0/24 via 10.8.1.2
`

are not working anymore. There is no traffic router through the tunnel.
Any ideas home to fix this again?
I had to uncomment temporarily to get it up and running again but have now only one entry of the wg-easy container IP in pi-hole. 🤐 

Best regards

**Comment by rumpelbaer** [comment]
## See real WireGuard client IPs in Pi-hole (wg-easy + Docker)

### Problem

In a setup with `wg-easy`, `Pi-hole`, and `Caddy` in the same Docker network (`172.21.0.0/16`), WireGuard assigns clients IPs from `10.8.0.0/24`.

By default, Pi-hole only sees DNS requests from the WireGuard container’s Docker IP (e.g. `172.21.0.4`). This is due to NAT (`MASQUERADE`) hiding the client IPs. Disabling NAT breaks DNS responses because Pi-hole doesn’t know how to reach the VPN subnet.

### Goal

- VPN clients should have full internet access
- Pi-hole should see the real client IPs (`10.8.0.x`) in its logs

---

### Solution

1. **Adjust NAT in `wg-easy`** to exclude Docker traffic  
2. **Add a static route in the Pi-hole container**  
3. **Allow Pi-hole to modify routes**

---

### 1. `WG_POST_UP` and `WG_POST_DOWN`

```env
WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 172.21.0.0/16 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -A FORWARD -s 172.21.0.0/16 -d 10.8.0.0/24 -j ACCEPT

WG_POST_DOWN=iptables -t nat -D POSTROUTING -s 10.8.0.0/24 ! -d 172.21.0.0/16 -o eth0 -j MASQUERADE; iptables -D INPUT -p udp --dport 51820 -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -D FORWARD -s 172.21.0.0/16 -d 10.8.0.0/24 -j ACCEPT
```

This keeps NAT for internet traffic but passes real IPs to other containers.

---

### 2. Static route in Pi-hole

Create a file `pihole-init.sh`:

```bash
#!/bin/bash
ip route add 10.8.0.0/24 via 172.21.0.4
exec /usr/bin/start.sh "$@"
```

Mount it into the container and configure Pi-hole like this:

```yaml
cap_add:
  - NET_ADMIN

entrypoint: [ "bash", "/init.sh" ]

volumes:
  - ./pihole-init.sh:/init.sh:ro
```

Replace `172.21.0.4` with the actual IP of your WireGuard container.

---

### 3. Example `docker-compose.yml`

```yaml
services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wireguard
    privileged: true
    restart: always
    environment:
      - LANG=de
      - WG_HOST=your.domain.tld
      - PASSWORD_HASH=<bcrypt-hash>
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=172.21.0.11
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PERSISTENT_KEEPALIVE=0
      - WG_DEVICE=eth0
      - WG_POST_UP=WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 172.21.0.0/16 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -A FORWARD -s 172.21.0.0/16 -d 10.8.0.0/24 -j ACCEPT
      - WG_POST_DOWN=iptables -t nat -D POSTROUTING -s 10.8.0.0/24 ! -d 172.21.0.0/16 -o eth0 -j MASQUERADE; iptables -D INPUT -p udp --dport 51820 -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -D FORWARD -s 172.21.0.0/16 -d 10.8.0.0/24 -j ACCEPT
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    ports:
      - "51820:51820/udp"
    volumes:
      - ./wireguard/config:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      proxy:
        ipv4_address: 172.21.0.4

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      - TZ=Europe/Berlin
      - FTLCONF_webserver_api_password=<redacted>
      - FTLCONF_dns_listeningMode=all
      - DNSMASQ_USER=pihole
    cap_add:
      - NET_ADMIN
    entrypoint: [ "bash", "/init.sh" ]
    volumes:
      - ./pihole/data:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d
      - ./pihole/pihole-init.sh:/init.sh:ro
    networks:
      proxy:
        ipv4_address: 172.21.0.11

networks:
  proxy:
    external: true
```

---

### Result

- Pi-hole logs show the real IPs of VPN clients (`10.8.0.x`)
- VPN clients have internet access
- NAT is disabled inside Docker but retained for external traffic

Tested with `wg-easy`, `pihole/pihole`, and `caddy` in the same Docker network.
