### DISCUSSION TITLE
Port forwarding for ports other than 51820/51821 not working

### DISCUSSION THREAD

**Discussion by k2helix** [wg-easy/wg-easy#1189] [Q&A] [answered]
**Describe the bug**
I wanted to forward port 60000 to device 10.8.0.2.  I first made sure that it is not blocked by firewall and opened it. Then I went to `docker-compose.yml`, added port 60000:60000 and had to change some things in the `/etc/wireguard/wg0.conf` file in the docker container with iptables to forward port 60000 to the device which has got the ip 10.8.0.2 like this
```
SaveConfig = true
PostUp = iptables -i eth0 -t nat -A PREROUTING -p tcp --dport 60000 -j DNAT --to-destination 10.8.0.2:60000
PostDown = iptables -i eth0 -t nat -D PREROUTING -p tcp --dport 60000 -j DNAT --to-destination 10.8.0.2:60000
```

However, the device 10.8.0.2 is not receiving any traffic even though port 60000 is open

**To Reproduce**
1. Open the port that you want to forward to another device connected to Wireguard
2. Add this port to the `docker-compose.yml` file
3. Add the necessary config (like the one above) to `/etc/wireguard/wg0.conf` in the docker container
4. Port is not forwarded to the device.

**Expected behavior**
The device should receive any traffic that the machine on which wg-easy is running gets in the specified port.

**Desktop:**
 - OS: Debian 12
 - Version: Latest

**Comment by winston164** [comment]
Same issue for me. I've tried many `iptables` configurations but nothing seems to work. I have a feeling it has to do with the fact that iptables has to be installed on Alpine containers so maybe there's something missing to enable NAT.

**Reply by k2helix** [reply]
Seems we're out of luck then. Maybe it is possible to build a container with the necessary tools installed and to check it there. Do you know what needs to be specifically included?

**Reply by winston164** [reply, marked as answer]
I managed to do port-forwarding, this is the docker-compose.yml file:

```yaml
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      LANG: "en"
      # ⚠️ Required:
      # Change this to your host's public address
      WG_HOST: <my-host>
      WG_PRE_UP: > 
        iptables -A FORWARD -i wg0 -j ACCEPT;
        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;
        iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j DNAT --to-destination 10.8.0.3:80;
        iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 443 -j DNAT --to-destination 10.8.0.3:443;
        iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 2222 -j DNAT --to-destination 10.8.0.3:22;
        iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 53 -j DNAT --to-destination 10.8.0.3:53;
        iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 25 -j DNAT --to-destination 10.8.0.3:25;
      WG_PRE_DOWN: > 
        iptables -D FORWARD -i wg0 -j ACCEPT;
        iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE;
        iptables -D PREROUTING -t nat -i eth0 -p tcp --dport 80 -j DNAT --to-destination 10.8.0.3:80;
        iptables -D PREROUTING -t nat -i eth0 -p tcp --dport 443 -j DNAT --to-destination 10.8.0.3:443;
        iptables -D PREROUTING -t nat -i eth0 -p tcp --dport 2222 -j DNAT --to-destination 10.8.0.3:22;
        iptables -D PREROUTING -t nat -i eth0 -p tcp --dport 53 -j DNAT --to-destination 10.8.0.3:53;
        iptables -D PREROUTING -t nat -i eth0 -p tcp --dport 25 -j DNAT --to-destination 10.8.0.3:25;


    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
        #- "51821:51821/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "2222:2222/tcp"
        #- "53:53/tcp"
      - "25:25/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
