### DISCUSSION TITLE
Subject: HTTPS Issues After Restarting wg-easy Container

### DISCUSSION THREAD

**Discussion by this-xkit** [wg-easy/wg-easy#1281] [Q&A] [answered]
Hello,

I am using wg-easy with Docker, Nginx, and Certbot to enable HTTPS. I am encountering an issue where HTTPS stops working after restarting the wg-easy container.

I followed the instructions for [Using WireGuard Easy with Nginx and SSL](https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL).

Here’s how I restore HTTPS after a restart:

1. I run _docker compose down_ and then _docker compose up --detach_.

2. After this, HTTPS no longer works, and I have to manually execute the following steps inside the nginx container:

```
docker exec -it nginx /bin/sh
cp /etc/nginx/servers/wg-easy.conf /etc/nginx/conf.d/.
certbot --nginx --non-interactive --agree-tos -m webmaster@google.com -d vpn.xkit.pro
nginx -s reload
exit
```

These steps temporarily fix the issue, but I would like to understand why this happens and how it can be resolved.

Could you please provide any insights or recommendations on how to address this issue?

**Comment by eandersons** [comment, marked as answer]
You should try to replace the command `cp /etc/nginx/servers/wg-easy.conf /etc/nginx/conf.d/.` with `cp /etc/nginx/servers/wg-easy.conf /etc/nginx/servers/`, because `/etc/nginx/conf.d/default.conf` has the line `include /etc/nginx/servers/*.conf;` and the content of `/etc/nginx/conf.d` is reset after container is recreated. Since `/etc/nginx/servers` is already mapped to a volume, then configuration should not be gone after recreating container.

Another thing I would like to point out is that the image `weejewel/nginx-with-certbot` is quite outdated - it was last updated about two years ago (see <https://hub.docker.com/r/weejewel/nginx-with-certbot/tags>).
To resolve that, I would:

1. save [`Dockerfile` of `weejewel/nginx-with-certbot`](https://raw.githubusercontent.com/WeeJeWel/nginx-with-certbot/master/Dockerfile) as `nginx-certbot.Dockerfile`;
2. update `compose.yaml`:

   ```yaml
   services:
     ...
       
     nginx:
       build:
         dockerfile: nginx-certbot.Dockerfile
       image: weejewel/nginx-with-certbot:custom  # Not mandatory; just to distinct the published image from the custom built one.
       ...
   
   ...
   
   ```

3. run `docker compose up --detach`;
  it should build an image with the latest Nginx and use it for the Nginx container.
