### DISCUSSION TITLE
How to move the tunnel outside the docker container

### DISCUSSION THREAD

**Discussion by VecH** [wg-easy/wg-easy#1303] [General]
How to move the tunnel outside the docker container so that it would be possible to work with connected clients that are connected to the container wg-easy?

`cat docker-compose.yml`
```
volumes:
  etc_amneziawg:

services:
  amnezia-wg-easy:
    env_file:
      - .env
    image: ghcr.io/spcfox/amnezia-wg-easy
    container_name: amnezia-wg-easy
    volumes:
      - ./amnezia-wg-easy:/etc/wireguard
    ports:
      - "${WG_PORT}:51820/udp"
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun
```

That is, on the host, see the tunnel interface with its IP address
so that it can be specified as an interface for services on the server (host)

**Comment by VecH** [comment]
This is how it works, the tunnel is up on the host system

`cat /etc/sysctl.d/97-amneziawg.conf`
```
net.ipv4.ip_forward=1
net.ipv4.conf.all.src_valid_mark=1
```

`cat docker-compose.yml`
```
volumes:
  etc_amneziawg:

services:
  amnezia-wg-easy:
    env_file:
      - .env
    image: ghcr.io/spcfox/amnezia-wg-easy
    container_name: amnezia-wg-easy
    volumes:
      - ./amnezia-wg-easy:/etc/wireguard
#    ports:
#      - "${WG_PORT}:51820/udp"
#      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
#    sysctls:
#      - net.ipv4.ip_forward=1
#      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
```
