### DISCUSSION TITLE
Linux clients don't get responses through Wireguard - please help

### DISCUSSION THREAD

**Discussion by rolandu** [wg-easy/wg-easy#1379] [Q&A]
I am trying to set up wg-easy at home so I can connect to my home server when away. I have got it to work on my iOS client, now I wanted to do some tests using Linux VMs (AWS EC2 and Hetzner VM), but was unable to connect in both cases.

So I set up wg-easy, I build the client (Ubuntu VM), install wireguard client, install the conf-file from the wg-easy web interface, run `wg-quick up wg0` and then the problems start.

The odd thing is that my iOS client works, it's just the Linux client, even at different cloud providers...

## Problem description:

- wg-easy web interface shows client connected
- client can connect to internet IPs (e.g. 8.8.8.8) - because it's a split tunnel setup
- unable to `ping` any IPs in my home/docker/wireguard network
- DNS requests using `dig` show up in my pi-hole's web interface, but on the client the request times out

It looks like a problem with routing traffic, the requests go through but the client does not get any response. The client does not run any firewall, neither locally (no ufw, empty iptables, everything on the cloud provider's side is set to open)...

## My setup:

- Home network: 10.34.0.0/24, 10.35.0.0/24
- Docker network: 10.35.2.0/24
- Wireguard's network: 10.35.1.0/24

## Server Docker-compose:

```
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: '***'
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      # run `touch ./var-log/pihole.log` first unless you like errors
      - './pihole/var-log/pihole.log:/var/log/pihole.log'
    restart: unless-stopped
    networks:
      knightnet:
        ipv4_address: "10.35.2.2"

  wg-easy:
    environment:
      # the server's hostname (clients will connect to):
      - WG_HOST=***

      # the Web UI Password:
      - PASSWORD_HASH=${PASSWORD_HASH}

      # The DNS server is the docker host, always .1 within the docker network
      - WG_DEFAULT_DNS=10.35.2.2

      # the addresses we are giving out to clients
      - WG_DEFAULT_ADDRESS=10.35.1.x

      # which IPs should be routed through the VPN
      # I selected 10.35.0.0/16 because I want to route 10.35.0.0 (physical network) and 10.35.1.0 (VPN network) as well
      - WG_ALLOWED_IPS=10.35.0.0/16,10.34.0.0/16
    image: ghcr.io/wg-easy/wg-easy
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      knightnet:
        ipv4_address: 10.35.2.3

# not shown: nginx reverse proxy for the web interfaces

networks:
  knightnet:
    ipam:
      driver: default
      config:
        - subnet: "10.35.2.0/24"
```

## how this looks like on the client:

```
root@ubuntu-4gb-nbg1-2:~# wg-quick up wg0
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.35.1.3/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] ip -4 route add 10.35.0.0/16 dev wg0
[#] ip -4 route add 10.34.0.0/16 dev wg0


root@ubuntu-4gb-nbg1-2:~# dig google.com
;; communications error to 127.0.0.53#53: timed out
^C


root@ubuntu-4gb-nbg1-2:~# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=116 time=3.83 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=116 time=3.41 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 3.413/3.620/3.828/0.207 ms


root@ubuntu-4gb-nbg1-2:~# ping 10.35.1.1
PING 10.35.1.1 (10.35.1.1) 56(84) bytes of data.
^C
--- 10.35.1.1 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1031ms


root@ubuntu-4gb-nbg1-2:~# ping 10.35.2.2
PING 10.35.2.2 (10.35.2.2) 56(84) bytes of data.
^C
--- 10.35.2.2 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1008ms

```
