### DISCUSSION TITLE
Is there a way to push routes to a client device?

### DISCUSSION THREAD

**Discussion by ewleonardspock** [wg-easy/wg-easy#1399] [Q&A] [answered]
I've been successfully using wg-easy for a while now, but I've run into some issues with my Wireguard configuration, and I seem to have hit a roadblock.

At home I use 10.18.x.x for my local network. And when I'm connected to the VPN from pretty much anywhere, it works totally fine, everything appears to be routed through the VPN (I see traffic on the server interface that matches what I'm doing) and I'm able to access services on my home network.

The issue I'm encountering is that when I go to the dealership to get my car serviced, their WiFi hands out 10.x.x.x IP addresses, and uses 255.0.0.0 as the subnet.

When I first encountered this issue a few years ago while running OpenVPN, I added 'push "route 10.18.0.0 255.255.0.0"' to the server config to fix it, but there doesn't seem to be an equivalent to that (that I've found at least) for wireguard.

Here's the Docker Compose:

```
services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=<REMOVED>

      # Optional:
      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=10.18.89.10, 10.18.88.50
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0, 128.0.0.0/1
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - WG_ENABLE_ONE_TIME_LINKS=true
      # - UI_ENABLE_SORT_CLIENTS=true
      # - WG_ENABLE_EXPIRES_TIME=true
      # - ENABLE_PROMETHEUS_METRICS=false
      # - PROMETHEUS_METRICS_PASSWORD=$$2a$$12$$vkvKpeEAHD78gasyawIod.1leBMKg8sBwKW.pQyNsq78bXV3INf2G # (needs double $$, hash of 'prometheus_password'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /opt/wg-easy/etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

And here's the wg0.conf from inside the container:

```
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = <REMOVED>
Address = 
ListenPort = 51820
PreUp = 
PostUp =  iptables -t nat -A POSTROUTING -s  -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; 
PreDown = 
PostDown =  iptables -t nat -D POSTROUTING -s  -o eth0 -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; 10.8.0.1/2410.8.0.0/2410.8.0.0/24
# Client: <ewleonardspock>'s iPhone (<Removed>)

[Peer]
PublicKey = <Removed>
PresharedKey = <Removed>
AllowedIPs = 10.8.0.2/32
```

Is there something super obvious that I'm missing?

If it makes a difference, I’m using an iPhone and a Mac. The client I’m using is [Passepartout](https://apps.apple.com/us/app/passepartout-vpn-client/id1433648537). I tried the Wireguard app on the iPhone, but it had the same behavior.
