### DISCUSSION TITLE
Can't get it working on kubernetes - no internete access

### DISCUSSION THREAD

**Discussion by GameBurrow** [wg-easy/wg-easy#1435] [Q&A] [answered]
So I managed to get to the point where we can connect to the server using the client, but as soon as we do, we lose all internet access, including to the server itself.

```yaml
# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: wireguard
  strategy:
    # Restrict to a Single wg-easy instance, on redeploys it will tear down the old one before bring a new one up.
    type: Recreate
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      tolerations:
      - key: "GameServersOnly"
        operator: "Equal"
        value: "true"
      nodeSelector:
        sepaurg.node.name: "gameserver"
      containers:
        - name: wg-easy
          # Specify external hostname and port as environment variables
          env:
            - name: WG_HOST
              value: wg.domain.eu
            - name: WG_PORT
              value: "30000"
            # - name: WG_DEVICE
            #   value: enp0s31f6
          image: ghcr.io/wg-easy/wg-easy:14 # https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy
          resources:
          ports:
            - containerPort: 30000 # WG_PORT now affects this also, see https://github.com/wg-easy/wg-easy/issues/1231#issuecomment-2259833816
              name: wg
              protocol: UDP
            - containerPort: 51821
              name: http
              protocol: TCP
          # Use the http server for pod health checks
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          # Give pod permissions to modify iptables and load the wireguard kernel module
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          # Persistent storage location
          volumeMounts:
            - mountPath: /etc/wireguard
              name: config
      restartPolicy: Always

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: wireguard-pvc

```

What am I doing wrong? You can see the `WG_DEVICE` I tried. Server has firewall preventing in connection but no out connection.

`ip a` of the server where the wireguard is running
```shell
zsh ❯ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute
       valid_lft forever preferred_lft forever
2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 90:1b:0e:ab:a6:34 brd ff:ff:ff:ff:ff:ff
    inet 95.216.9.252/26 brd 95.216.9.255 scope global enp0s31f6
       valid_lft forever preferred_lft forever
    inet6 2a01:4f9:2a:a26::2/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::921b:eff:feab:a634/64 scope link
       valid_lft forever preferred_lft forever
...
```

I followed the kubernetes tutorial: https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Kubernetes

**Comment by GameBurrow** [comment]
Got it working, needed to add:

```
      initContainers:
        - image: busybox:latest
          imagePullPolicy: IfNotPresent
          name: init-busybox
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1 && sysctl -w net.ipv4.conf.all.src_valid_mark=1
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
```

**Comment by GameBurrow** [comment]
Actually, small issue is remaining, after some time (very random) - I have to restart the pod. Otherwise I again won't have internet access when I connec to it.

**Reply by GameBurrow** [reply, marked as answer]
> Actually, small issue is remaining, after some time (very random) - I have to restart the pod. Otherwise I again won't have internet access when I connec to it.

Alright, seems I found solution for this also, instead of using initContainer, I had to put it's contents into WG_POST_UP:

````
containers:
        - name: wg-easy
          # Specify external hostname and port as environment variables
          env:
            - name: WG_HOST
              value: vpn-wg.sepaurg.eu
            - name: WG_PORT
              value: "30000"
              # Value of WG_POST_UP is built by combining the sysctl-s we need at the beginning 
              # and the default values from https://github.com/wg-easy/wg-easy/blob/master/src/config.js#L26
              # Do note all variables got replaced with their default values or what we've set above
            - name: WG_POST_UP
              value: sysctl -w net.ipv4.ip_forward=1; sysctl -w net.ipv4.conf.all.forwarding=1; sysctl -w net.ipv4.conf.all.src_valid_mark=1; iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 30000 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
          image: ghcr.io/wg-easy/wg-easy:14 # https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy
          
````

Do note it has to be single liner, couldn't get it working as multi-line env var. I also copied the default WP_POST_UP content to not lose it (and replaced vars in it with the default values)

It has now ran 3 days without issues
