### DISCUSSION TITLE
Docker image automatic build

### DISCUSSION THREAD

**Discussion by loranger** [wg-easy/wg-easy#144] [Ideas]
Hello, and thanks a lot for this wireguard bundle which made my vpn much simpler to manage.

I use wg-easy with docker-compose, and did setup [watchtower](https://containrrr.dev/watchtower/) in order to keep all my docker services up-to-date.

Watchtower look for any new docker image build, pulls it and notify me. I used to automatically restart the updated service, but once traefik was broken and nothing was not reachable until I fixed it, I learned the lesson and I'm now satisfied with the notification. I wait for the right moment to restart my service, and there is often no issue with the updated service.

wg-easy seems to have a daily automatic build, which trigger the *image updated* notification. I firstly thought there was new fixes or features, but it seems there have been no major modification since 14 days, whereas watchtower find a new wg-easy build everyday.
I then imagined only the latest image was built automatically, and fell back on `weejewel/wg-easy:4` but the result is the same: A new docker image is built even if there is no modification until the last one.

What do you think about not build an image if no modification were done ? Or maybe keep the latest auto build, but the real tagged images could use a manual build instead an automatical one ?

**Comment by l4rm4nd** [comment]
Yep, currently receiving watchtower notifications on a daily basis too, although no real image changes have been pushed.

**Comment by holocronology** [comment]
Could you share a copy of your docker-compose for wg-easy?

**Reply by l4rm4nd** [reply]
Sure, no problem:

````
version: "3"

services:
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wg-easy
    environment:
      - WG_HOST=vpn.example.com
      - PASSWORD="MyVerySecurePasswordForAdminPanel"
      - WG_DEFAULT_DNS=1.1.1.1
    hostname: wireguard-easy
    image: docker.io/weejewel/wg-easy:latest
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    volumes:
      - /Docker-Volumes/WireGuard-Easy:/etc/wireguard
````

**Reply by loranger** [reply]
Here's mine, for what it worth

```yaml
  wg-easy:
    image: weejewel/wg-easy:4
    container_name: wg-easy
    env_file:
      - .env
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.http.routers.wg-easy.entrypoints=http"
      - "traefik.http.routers.wg-easy.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.wg-easy.middlewares=redirect-to-https@file"
      - "traefik.http.routers.wg-easy-secure.entrypoints=https"
      - "traefik.http.routers.wg-easy-secure.rule=Host(`${APP_URL}`)"
      - "traefik.http.routers.wg-easy-secure.tls=true"
      - "traefik.http.routers.wg-easy-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.wg-easy-service.loadbalancer.server.port=51821"
      - "com.centurylinklabs.watchtower.enable=true"
```

**Reply by NetRat88** [reply]
I know this issue is closed but recognized, that I have the same issue. There are a lot of unused images of wg-easy in my portainer. Is there anny fix planned for this behavoir?

This is my currenty docker-compose.yaml:

```yaml
version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wireguard-easy
    hostname: wireguard-docker
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true" #nur Monitoring auf Updates durch Watchtower und kein Auto-Update
    volumes:
      - /home/pi/docker/wireguard-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    env_file:
      - stack.env
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=${WG_HOST}
      # ⚠️ Change the Web UI Password:
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
      #- WG_ALLOWED_IPS=0.0.0.0/0,192.168.1.0/24
      - UI_TRAFFIC_STATS=true
      #- WG_PERSISTENT_KEEPALIVE=25
      #- WG_POST_UP=iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg-easy -j ACCEPT; iptables -A FORWARD -o wg-easy -j ACCEPT;
      #- WG_POST_DOWN=iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg-easy -j ACCEPT; iptables -A FORWARD -o wg-easy -j ACCEPT;
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

networks:
  wg-easy:
    external: true
```
