### DISCUSSION TITLE
Using wg-easy with adguard doesn't resolve dns rewrites

### DISCUSSION THREAD

**Discussion by jonskoglund** [wg-easy/wg-easy#1449] [Q&A]
Hi. I used some of the docker compose code in [this post](https://github.com/wg-easy/wg-easy/discussions/229#discussion-3950231) to connect wg-easy and adguard on the same docker network. This setup works to resolve local ips on my lan but not the DNS rewrites that I have set up in Adguard. Example:
```
homepage-local.mydomain.com   - 192.168.2.46
```
The above is the ip address where I host my docker containers.

Adguard docker compose:
```
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    environment:
      - TZ=xxxxxxxxxxxxxxxxxxx
    ports:
      - 53:53/tcp #plain DNS
      - 53:53/udp #plain DNS
      - 3001:3000/tcp # for Adguard Home's API 
      - 81:80/tcp # for HTTP web interface
      - 444:443/tcp # for HTTPS web interface
      - 444:443/udp # for HTTPS web interface   

    volumes:  # Mount host directories as volumes inside the container
      - /mnt/pool1/vm/appdata/adguardhome/work:/opt/adguardhome/work  
      - /mnt/pool1/vm/appdata/adguardhome/conf:/opt/adguardhome/conf

    networks:
      private_network:
        ipv4_address: 10.2.0.100 adguard IP Address (used as DNS server in wg-easy)

networks:
  private_network:
    external: true
```

wg-easy docker compose:
```
networks:
  private_network:
    name: private_network
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy  # The Docker image to use.
    container_name: wg-easy         # Name of the container.
    environment:                    # Environment variables to configure the instance.
      - LANG=en                     # Language settings.
      - WG_HOST=xxx.xxx.xxx.xxxx    # Public IP or domain name where WG-Easy is accessible.
      - PASSWORD_HASH=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - PORT=xxxxxx                  # Port for the web interface.
      - WG_PORT=xxxxx               # WireGuard port for VPN traffic.

      # 💡 This is the adguardhome Container's IP Address
      - WG_DEFAULT_DNS=10.2.0.100   #adguardhome    
    volumes:
      - /mnt/pool1/vm/appdata/wgeasy:/etc/wireguard   # Volume mapping for WireGuard configuration files.
    ports:
      - "xxxxx:xxxxx/udp"           # UDP port used by WireGuard - Add this to your router!
      - "xxxxxx:xxxxx/tcp"           # TCP port for accessing the web interface.
    cap_add:                        # Capabilities required for managing networking features.
      - NET_ADMIN
      - SYS_MODULE
    sysctls:                        # Kernel parameters that need to be set for WireGuard.
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped         # Ensures the container restarts automatically unless manually stopped.
    networks:
      private_network:
        ipv4_address: 10.2.0.3 #wg-easy IP Address in adguard, you won't see 10.8.0.x in Query Log
```

When I access the url homepage-local.mydomain.com via wg-easy vpn I get a Forbidden in the browser.
The url has HTTPS using Traefik by the way. And Traefik is also a docker container. Any ideas how to fix this issue?
