### DISCUSSION TITLE
How to start caddy on wg-easy wireguard network?

### DISCUSSION THREAD

**Discussion by gyzerok** [wg-easy/wg-easy#1466] [Q&A]
Hello there!

I am moving from a OS native `wg-quick` setup to a full docker with `wg-easy` and am not sure how to specify port forwards for `caddy`.

Previously I've had a wireguard server on a 10.8.0.1 and a Caddy in `docker-compose.yml` would forward ports like so:
```
services:
  caddy:
    container_name: caddy
    ports:
      - 10.8.0.1:80:80
      - 10.8.0.1:443:443
      - 10.8.0.1:443:443/udp
```

Now I'd like to achieve the same goal but having both `wg-easy` and `caddy` running through docker. However whatever configuration, I end up with `caddy` not being able to bind to the specified address.

Here are relevant parts from my `docker-compose.yml`
```
services:
  wg-easy:
    container_name: wg-easy
    networks:
      - caddy-net
    environment:
      - WG_HOST=${WG_HOST}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=10.8.0.1

  caddy:
    depends_on:
      - wg-easy
    networks:
      - caddy-net
    ports:
      - 10.8.0.1:80:80
      - 10.8.0.1:443:443
      - 10.8.0.1:443:443/udp
```

What am I doing wrong?
