### DISCUSSION TITLE
How to make Pi-hole work on both LAN network and through WireGuard VPN?

### DISCUSSION THREAD

**Discussion by DirkBraakman** [wg-easy/wg-easy#1467] [Q&A]
I'd like to make my Pi-hole container work as DNS server on both local network and also as DNS server for my VPN clients.

I guess you have to set Pi-hole in network mode "host".
But I can't figure out how to make the VPN clients use the Pi-hole DNS IP this way.

And the template isn't useful. With that I can't set my Docker host's IP as the DNS server in my external DHCP server...

I'd like it to work either like this:

**Option 1:**
Pi-hole container has both an IP from the host's interface, and an IP from a Docker internal network.
WireGuard uses the internal network IP as the WG_DEFAULT_DNS.
The DHCP server sets the IP from the host interface as DNS server for LAN clients.

I can't figure out how to do this, the Pi-hole container can't have access to both interfaces in host or bridge mode...

**Option 2:**
 Pi-hole runs in network mode "host". I set my DHCP DNS to the Docker host IP.
 WireGuard uses the host IP (DHCP reservation) as the WG_DEFAULT_DNS.
 
 I can't figure out how to do this, the clients can't ping my host, even though I use WG_ALLOWED_IPS...
 
 
 
 
This is my current docker-compose.yaml file trying option 2:
```yml
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - PASSWORD_HASH=hidden
      - WG_HOST=hidden (public domain record)
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_ALLOWED_IPS=10.8.0.0/24, 192.168.10.0/24 # Change second range to the subnet docker host and router is in
      - WG_DEFAULT_DNS=192.168.10.5 # Change to docker host IP address
    volumes:
      - '/container-configs/wg-easy:/etc/wireguard'
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    environment:
      - TZ='Europe/Amsterdam'
      - WEBPASSWORD=hidden
      - WEB_PORT=5353
      - INTERFACE=eno1 # Change to network interface name
      - PIHOLE_DNS_=1.1.1.1;8.8.8.8
    volumes:
      - '/container-configs/pihole/etc-pihole:/etc/pihole'
      - '/container-configs/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
```
 
Can somebody help me?
Thanks! 
 
[UPDATE]
Okay, it seems to be the Debian 12 issue other users have posted about already...
