### DISCUSSION TITLE
Unable to get wg-easy with pihole up and running despite following wiki guide, noob alert?

### DISCUSSION THREAD

**Discussion by therealjin** [wg-easy/wg-easy#1485] [Q&A]
Hello everyone, to preface this, I am a mega noob. But I have whipped up my RPI4 with Raspbian OS and have installed docker and portainer to help me manage my dockers. Now if i try to make separate stacks for Pihole and wg-easy, they both work I can connect to pihole via the IP I reserved for my RPI (192.168.2.3x) and I can connect to wg. However I do not understand why they would not work if I tried to make one single stack and paste the docker-compose.yml file, with the necessary edits. Below is my yml file. And for whatever reason, I can only connect to the wg web UI, but nothing will load if I connect a client.  I am unable to connect to the 10.8.1.3/admin for pihole at all.

Can someone assist me in getting wg-easy with pihole running please?

```
services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=myservername.duckdns.org

      # ⚠️ Change the Web UI Password:
      - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG #still foobar123 to test
      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3 # DNS server clients will use.
      - WG_DEFAULT_ADDRESS=10.8.0.x # Clients IP address range.
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2 # wg-easy IP Address in Pi-hole, you won't see 10.8.0.x in Query Log

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      # ⚠️ Change the Web UI Password:
      - WEBPASSWORD=apasswordforpihole
      - TZ= 'America/Toronto'
    volumes:
      - '~/.pihole/etc-pihole:/etc/pihole'
      - './.pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
```
