### DISCUSSION TITLE
Absolutely no traffic through VPN server

### DISCUSSION THREAD

**Discussion by USSURATONCACHI** [wg-easy/wg-easy#1492] [Q&A]
I have set up docker and wg-easy container on a fresh ubuntu machine. I tried three versions of docker. I tried versions of the container - `:latest`, `:nightly`, and older `weejewel/wg-easy`. I tried a LOT of `AllowedIPs` configurations. Firewall is NOT on. Raw TCP and UDP traffic freely passes.

Webpage on SERVER_IP:51801 works perfectly fine. I tried to connect clients from Manjaro Linux, Ubuntu, Windows 10, and Android. Client machines are perfectly fine, since we also tested them with another wireguard server the same.

When client connects - webpage panel shows that client both sends and receives 64-400 bytes. And clients do connect fine. However, any traffic except connections and disconnections is not even received on the server.

I tried to dump the udp traffic (I replaced actual IPs with "CLIENT" and "SERVER"):
```
root:~/my_vpn# tcpdump udp port 51800
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
14:53:31.296613 IP CLIENT.33082 > SERVER.51800: UDP, length 148
14:53:31.296912 IP SERVER.51800 > CLIENT.33082: UDP, length 92
14:53:31.446440 IP CLIENT.33082 > SERVER.51800: UDP, length 96
14:53:31.448327 IP SERVER.51800 > CLIENT.33082: UDP, length 144
14:53:31.480341 IP CLIENT.33082 > SERVER.51800: UDP, length 112
14:53:31.712169 IP CLIENT.33082 > SERVER.51800: UDP, length 112
14:53:33.160467 IP CLIENT.33082 > SERVER.51800: UDP, length 112
14:53:33.165930 IP SERVER.51800 > CLIENT.33082: UDP, length 144
```
All these packets fire immideately after i turn VPN on my phone. And then absolutely no traffic packets, no matter what I do. Maybe related to "listening on eth0" but idk.

All clients report sending kilobytes of data and receiving no more then 64-400 bytes. `ifconfig` on linux clients report a lot of dropped packets on the VPN network device. Web panel with profiles shows that client never sent or received more than 64-400 bytes (even though we actively tried to ping or curl or nslookup domains and ips).

Trying to do absolutely any request through that vpn from clients leads to absolutely nothing. No ping, no response, no connection. Traffic is not even registered on server side by tcpdump or by web panel traffic ui itself.

Here is my current setup:
```
root:~/my_vpn# cat docker-compose.yml 
version: "3.8"

services:
  wg-easy-main:
    environment:
      - WG_HOST=...my ip...
      - WG_PORT=51800
      - PORT=51801
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=0.0.0.0/1, 128.0.0.0/2, 192.0.0.0/7, 194.0.0.0/8...
      - WG_DEFAULT_ADDRESS=10.8.3.x
#      - UI_TRAFFIC_STATS=true
#      - UI_CHART_TYPE=1

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy-main
    hostname: wg-easy-main
    volumes:
      - ./data/wireguard:/etc/wireguard
    ports:
      - "51800:51800/udp"
      - "51801:51801/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

I tried a bunch of different `AllowedIPs` values - none work. Trying to reach any IP that falls into "AllowedIPs" gives no response or ping or anything.

I did not find any related info on the interned. Not sure what to do.

UPD: websites and internet `ping`s and `curl`s perfectly fine from the server machine AND from inside the docker container (`docker exec --it wg-easy-main /bin/bash`)
