### DISCUSSION TITLE
Running as non-root user?

### DISCUSSION THREAD

**Discussion by 0xFFA500** [wg-easy/wg-easy#1506] [Q&A]
Am I able to run wg-easy as a non-root user?

I tried the following
<details><summary>compose.yaml</summary>
<p>

```yaml
services:
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=👀

      - PASSWORD_HASH=👀
      - WG_PORT=51820
    image: ghcr.io/wg-easy/wg-easy
    labels:
      - traefik.enable=true

      - traefik.http.routers.wg-easy.entryPoints=webSecure
      - traefik.http.routers.wg-easy.rule=Host(`wg-easy.👀`)
      - traefik.http.services.wg-easy.loadBalancer.server.port=51821
      - traefik.http.routers.wg-easy.service=wg-easy
    ports:
      - 51113:51113/udp
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    user: 1013:1013
    volumes:
      - ./wg-easy/wireguard:/etc/wireguard
```

</p>
</details>

But I got the following error

```
Error: Command failed: wg-quick up wg0
/usr/bin/wg-quick: line 85: exec: sudo: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:339:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```
