### DISCUSSION TITLE
Ping client from server container

### DISCUSSION THREAD

**Discussion by Batimius** [wg-easy/wg-easy#1509] [Q&A]
Hello there. I'll make this as short as possible. I have wg-easy running on a Docker container, and I'd like to be able to directly ping (in the future, I'll route traffic through there via a reverse proxy) the connected client. I was able to ping the client from inside the container, but I am struggling to ping them from outside (or from another container). I did try using the `ip route add 10.8.0.0/24 via 172.19.0.2` command, but it didn't work. Here is my `docker-compose.yml`:
```yaml
version: '3.8'
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy  # The Docker image to use.
    container_name: wg-easy         # Name of the container.
    environment:                    # Environment variables to configure the instance.
      - LANG=en                     # Language settings.
      - WG_HOST=HIDDEN      # Public IP or domain name where WG-Easy is accessible.
      - PASSWORD_HASH=HIDDEN
      - PORT=51821                  # Port for the web interface.
      - WG_PORT=51820               # WireGuard port for VPN traffic.
    volumes:
      - ./wg-easy/:/etc/wireguard   # Volume mapping for WireGuard configuration files.
    ports:
      - "51820:51820/udp"           # UDP port used by WireGuard.
      - "51821:51821/tcp"           # TCP port for accessing the web interface.
    networks:
      wireguard:
        ipv4_address: 172.19.0.2
    cap_add:                        # Capabilities required for managing networking features.
      - NET_ADMIN
      - SYS_MODULE
    sysctls:                        # Kernel parameters that need to be set for WireGuard.
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped         # Ensures the container restarts automatically unless manually >

networks:
  wireguard:
    name: 'wireguard'
    driver: bridge
```
If I run the command `docker exec -it wg-easy sh` and then run `ping 10.8.0.2`, I get a response, however, that doesn't work with any other container or on the host network.

Any and all help is appreciated. Thank you for your time and help.

**Comment by kaaax0815** [comment]
Docker networks are isolated by default. You would have to join the network to make it work.
create a container and also specify
```yaml
services:
  replaceme:
    networks:
      - wireguard
```
and it should work
