### DISCUSSION TITLE
wg-easy + Nginx Proxy Manager (Web-UI Error)

### DISCUSSION THREAD

**Discussion by zero-proger** [wg-easy/wg-easy#1543] [Q&A] [answered]
![Снимок экрана 2024-12-05 203442](https://github.com/user-attachments/assets/87fe4e37-ebe6-4efa-93bb-ceaa1ba74f5f)
I use wg-easy + Nginx proxy manager
here is my config:
npm:
```
services:
  app:
    container_name: npm
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '45555:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - npm

networks:
  npm:
    driver: 'bridge'
    ipam:
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1
          ip_range: 10.10.1.0/24

```
wg-easy:
```
services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped
    networks:
      - default
      - npm_npm
    environment:
      - WG_HOST=wg.mydomain.duckdns.org
      - LANG=ru
      - PASSWORD_HASH='$$2a$$12$$exapleexample.......'
      - WG_DEVICE=eth0
    volumes:
      - ./conf:/etc/wireguard
    ports:
      - 51820:51820/udp
      # - 51821:51821/tcp # web-ui
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
networks:
  backend:
    driver: bridge
  npm_npm:
    external: true
```
