### DISCUSSION TITLE
QR code not valid AND DNS does not propogate to server or clients

### DISCUSSION THREAD

**Discussion by azurecrash** [wg-easy/wg-easy#1596] [Q&A]
Hi - I am in the process of consolidating servers and have been using WG successfully on bare metal. I am now reconfiguring on docker with wg-easy and trying to mimic (not move) my client settings. I am doing the same with pihole and unbound. pinhole/unbound (and orbital sync are all working). wg-easy comes up and I can create clients on the UI, but there is some strangeness.

First, DNS is not apparently in wg0.conf, nor in any of the client confs even though the env. variable is defined.
Second, the QR code in the UI is not valid as per the iOS wireguard app. The error is: "The scanned QER code in not a valid WireGuard configuration."

Here is the docker compose (with private details removed)

```
# Deploys Pihole and Unbound containers, separately, with a docker based sync mechanism and a prometheus exporter.

version: '3'

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.1.0/24
          gateway: 10.8.1.1
        
services:
  unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
#   volumes:
#     - ./unbound.conf:/usr/local/unbound/unbound.conf:rw
#     - ./conf.d/:/usr/local/unbound/conf.d/:rw
#     - ./log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
#     - ./zones.d/:/usr/local/unbound/zones.d/:rw
    restart: unless-stopped
    healthcheck:
      test: /usr/local/unbound/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s
    networks:
      pihole_net:
        ipv4_address: 10.8.1.3
    environment:
      TZ: "America/New_York"
#      UNBOUND_UID: 1000 #optional
#      UNBOUND_GID: 1000 #optional
      HEALTHCHECK_PORT: 5335 #optional
      EXTENDED_HEALTHCHECK: true #optional
      EXTENDED_HEALTHCHECK_DOMAIN: "nlnetlabs.nl" #optional
      ENABLE_STATS: false #optional
    
  pihole:
    container_name: pihole
    hostname: pihole.lan
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "82:80/tcp"
    environment:
      TZ: 'America/New York'
      WEBPASSWORD: 'xxx'
      DNSMASQ_LISTENING: all
      PIHOLE_DNS_: 'unbound#5053;unbound#5335'
    # Volumes store your data between container upgrades
    volumes:
      - '/home/xxx/pihole-docker/pihole/pihole:/etc/pihole'
      - '/home/xxx/pihole-docker/pihole/dnsmasq.d:/etc/dnsmasq.d'
    networks:
      pihole_net:
        ipv4_address: 10.8.1.2
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    dns:
      - 127.0.0.1
    restart: unless-stopped
    depends_on: 
      - unbound

# sync mechanism 
  orbital-sync:
    container_name: orbital-sync
    image: mattwebbio/orbital-sync:latest
    environment:
      PRIMARY_HOST_BASE_URL: 'http://192.168.1.108:82'
      PRIMARY_HOST_PASSWORD: 'xxx'
      SECONDARY_HOSTS_1_BASE_URL: 'http://192.168.1.109'
      SECONDARY_HOSTS_1_PASSWORD: 'xxx'
      SECONDARY_HOSTS_2_BASE_URL: 'http://pihole.lan'
      SECONDARY_HOSTS_2_PASSWORD: 'xxx'
      INTERVAL_MINUTES: 60
    networks:
     pihole_net:
       ipv4_address: 10.8.1.4
    depends_on: 
      - pihole

#this is wg-easy, which is an implementation of wireguard with a GUI that is well used.
#this is in replacement of PiVPN.
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=http://xxx.duckdns.org

      # ⚠️ Change the Web UI Password:
      - PASSWORD_HASH=xxx

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS = 10.8.1.2

      - WG_DEFAULT_ADDRESS = 10.8.0.x
      - ENABLE_PROMETHEUS_METRICS = true
      - UI_TRAFFIC_STATS = true
      - UI_CHART_TYPE = 1
      - UI_ENABLE_SORT_CLIENTS = true
      - WG_PERSISTENT_KEEPALIVE = 25
      
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /home/xxx/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
     pihole_net:
       ipv4_address: 10.8.1.5
    depends_on: 
      - pihole
```

Separately, when I bring the whole thing up, the config *looks* fine, but the QR code when adding to iOS is invalid. If I download the conf file, it looks like this:

[Interface]
PrivateKey = xxx
Address = 10.8.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = xxx
PresharedKey = xxx
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = http://xxx.duckdns.org:51820
