### DISCUSSION TITLE
Help needed for setting up docker host iptables

### DISCUSSION THREAD

**Discussion by LaurentAtJoes** [wg-easy/wg-easy#1603] [Q&A] [answered]
Hi all,

I just set up wgeasy and it works great, except for one thing I can't figure out.

It runs on docker (homelab ubuntu 22 server, through portainer).

Connected clients can access other devices on the LAN (browse shares, connect to web UIs...), the only thing I can't get to work is to access services that are _also running on the same docker instance_

I've been searching half of the day about this, found some infos about adding rules to WG_POST_UP env variable (which are correctly applied, checked through container console), but to no avail (which seems logical since as explained below, the trouble appears to lie on the host's side).

I know I could run wgeasy in network host mode, but I'd rather try to keep it as is (bridge).

I can not create a docker network common to all containers I want to access, because 1. I find this too "static" and 2. some of them _must_ be accessed by their (physical) LAN IP to work properly (here 192.168.0.x)

After tinkering a bit, and following a hint in another post here, I just tried to disable ufw _on the HOST_ .

And access to those dockerized services immediately worked.

So I guess I must add some rules _on the host_ either trough ufw or directly to iptables, but I don't know which (I'm not an ubuntu / docker / iptables expert, I'm just a power user able to apply advice found online...)

Any help would be greatly appreciated.

compose file :
```
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    networks:
      wg-easy:
        ipv4_address: 172.20.0.2
    volumes:
      - /var/lib/docker/files/wg-easy:/etc/wireguard
    ports:
      - "$WG_PORT:$WG_PORT/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      LANG: en
      WG_HOST: MY_WAN_IP
      # WG_DEVICE: enp0s31f6
      PASSWORD_HASH: $PASSWORD_HASH
      WG_PORT: $WG_PORT
      WG_DEFAULT_ADDRESS: $WG_DEFAULT_ADDRESS
      WG_DEFAULT_DNS: 192.168.0.1
      WG_ALLOWED_IPS: $WG_LAN_SUBNET
      WG_PERSISTENT_KEEPALIVE: 30
      WG_POST_UP: "iptables -t nat -A POSTROUTING -s $WG_VPN_SUBNET -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport $WG_PORT -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s $WG_VPN_SUBNET -d $WG_DOCKER_SUBNET -j MASQUERADE; iptables -A FORWARD -s $WG_VPN_SUBNET -d $WG_DOCKER_SUBNET -j ACCEPT; iptables -A FORWARD -s $WG_DOCKER_SUBNET -d $WG_VPN_SUBNET -j ACCEPT"
      WG_POST_DOWN: "iptables -t nat -D POSTROUTING -s $WG_VPN_SUBNET -o eth0 -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport $WG_PORT -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s $WG_VPN_SUBNET -d $WG_DOCKER_SUBNET -j MASQUERADE; iptables -D FORWARD -s $WG_VPN_SUBNET -d $WG_DOCKER_SUBNET -j ACCEPT; iptables -D FORWARD -s $WG_DOCKER_SUBNET -d $WG_VPN_SUBNET -j ACCEPT"

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  wg-easy:
    ipam:
      config:
        - subnet: $WG_DOCKER_SUBNET
```
(note : the 'explicit' bridge network was only added to ensure permanent IPs, should I use that in some rule. Works the same without it)

together with env :
```
PASSWORD_HASH=*******
WG_PORT=51822
WG_DEFAULT_ADDRESS=192.168.5.x
WG_VPN_SUBNET=192.168.5.0/24
WG_DOCKER_SUBNET=172.20.0.0/16
WG_LAN_SUBNET=192.168.0.0/24```
