### DISCUSSION TITLE
Make WebUI accessible only from localhost

### DISCUSSION THREAD

**Discussion by erasesys32** [wg-easy/wg-easy#1609] [Q&A] [answered]
I would like the WebUI to be only accessible from localhost but when I set the "WEBUI_HOST" variable to "127.0.0.1" or "localhost" I can't reach it.
When I'm using "curl" it only returns "curl: (56) Recv failure: Connection reset by peer"

I've also tried to add "127.0.0.1" to the "ports" section but without success.
`127.0.0.1:8080:8080`

Here is my compose file:
```
volumes:
  etc-wireguard:
    name: etc-wireguard

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=PUBLIC_IP
      - WEBUI_HOST=127.0.0.1
      - PORT=8080
    volumes:
      - etc-wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 8080:8080/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
