### DISCUSSION TITLE
Error: Command failed: wg-quick up wg0

### DISCUSSION THREAD

**Discussion by mihaijulien** [wg-easy/wg-easy#1647] [Q&A]
```
wireguard  | $ wg-quick up wg0
wireguard  | Error: Command failed: wg-quick up wg0
wireguard  | [#] 
wireguard  | [#] ip link add wg0 type wireguard
wireguard  | [#] wg setconf wg0 /dev/fd/63
wireguard  | [#] ip -4 address add 10.8.0.1/24 dev wg0
wireguard  | [#] ip link set mtu 1420 up dev wg0
wireguard  | [#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
wireguard  | iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
wireguard  | Perhaps iptables or your kernel needs to be upgraded.
wireguard  | [#] ip link delete dev wg0
wireguard  | 
wireguard  |     at genericNodeError (node:internal/errors:984:15)
wireguard  |     at wrappedFn (node:internal/errors:538:14)
wireguard  |     at ChildProcess.exithandler (node:child_process:422:12)
wireguard  |     at ChildProcess.emit (node:events:519:28)
wireguard  |     at maybeClose (node:internal/child_process:1105:16)
wireguard  |     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
wireguard  |   code: 3,
wireguard  |   killed: false,
wireguard  |   signal: null,
wireguard  |   cmd: 'wg-quick up wg0'
```

<details>
 <summary>compose.yml</summary>
 
```yaml
  wireguard:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi, ja, si)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=<my_host>

    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    volumes:
      - /etc/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
</details>
