### DISCUSSION TITLE
Testing V15

### DISCUSSION THREAD

**Discussion by Radiohofen** [wg-easy/wg-easy#1685] [General]
Hi there!

Is it possible to try out the new V15 Version? I looking forward to try out the new features. 
I don't mind that the version is in alpha or beta.

Best regards
René

**Comment by bitbronze** [comment]
Use the :development tag, like: `image: ghcr.io/wg-easy/wg-easy:development`

**Comment by Radiohofen** [comment]
Thank you ! It´s done :-)

**Comment by haitham506** [comment]
I can barely finish the setup and If I do I can't Login, It needs more time

**Reply by kaaax0815** [reply]
Please elaborate? Maybe you have to pull the new development tag?

**Reply by haitham506** [reply]
I am on a Raspberry Pi and I did pull the latest development image released today

The is my Docker Compose


```
services:
  wg-easy-dev:
    environment:
      - PORT=51821
      # Optional:
      - HOST=0.0.0.0

    image: ghcr.io/wg-easy/wg-easy:development
    container_name: wg-easy-dev
    networks:
      wg-dev:
        ipv4_address: 10.8.0.8
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - /portainer/Config/wireguard-dev:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

networks:
  wg-dev:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.8.0.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
```
