### DISCUSSION TITLE
Example docker-compose.yml with how to set WG_POST_UP & WG_POST_DOWN

### DISCUSSION THREAD

**Discussion by cschwarck** [wg-easy/wg-easy#173] [Q&A] [answered]
Thank you for adding some additional features to wg-easy! (WG_PERSISTENT_KEEPALIVE, etc)

Would you post an example docker-compose that includes WG_POST_UP & WG_POST_DOWN? 

This would be very helpful.

```
version: "3.5"
services:
  wg-easy:
    environment:
      # Host's public address
      - WG_HOST=xx.xxxx.net
      - PASSWORD=xxx
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.10.10.x
      - WG_DEFAULT_DNS=192.168.1.1, 8.8.8.8
      - WG_ALLOWED_IPS=10.10.10.0/24, 192.168.1.0/24
      - WG_PERSISTENT_KEEPALIVE=45
      - WG_POST_UP=(???)
      - WG_POST_DOWN=(???)

    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Comment by WeeJeWel** [comment]
See https://github.com/WeeJeWel/wg-easy/blob/master/src/config.js#L19

**Comment by cschwarck** [comment]
Thank you, I looked at this, but unfortunately I don't understand how to use those settings in a compose file. Would you be kind enough to point me where I can learn how to use that?

**Comment by cschwarck** [comment]
..testing:

```
version: "3.5"
services:
  wg-easy:
    environment:
      # Host's public address
      - WG_HOST=xx.xxxx.net
      - PASSWORD=xxx
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.10.10.x
      - WG_DEFAULT_DNS=192.168.1.1, 8.8.8.8
      - WG_ALLOWED_IPS=10.10.10.0/24, 192.168.1.0/24
      - WG_PERSISTENT_KEEPALIVE=45
      # UP:
      - WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT
      - WG_POST_UP=iptables -A FORWARD -o wg0 -j ACCEPT
      - WG_POST_UP=iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - WG_POST_UP=iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT
      # DOWN:
      - WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT
      - WG_POST_DOWN=iptables -D FORWARD -o wg0 -j ACCEPT
      - WG_POST_DOWN=iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      - WG_POST_UP=iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Comment by cschwarck** [comment, marked as answer]
Ok, this seems to work:

```
version: "3.5"
services:
  wg-easy:
    environment:
      # Host's public address
      - WG_HOST=xx.xxxx.net
      - PASSWORD=xxx
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.10.10.x
      - WG_DEFAULT_DNS=192.168.1.1, 8.8.8.8
      - WG_ALLOWED_IPS=10.10.10.0/24, 192.168.1.0/24
      - WG_PERSISTENT_KEEPALIVE=45
      # UP:
      - WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT
      - WG_POST_UP=iptables -A FORWARD -o wg0 -j ACCEPT
      - WG_POST_UP=iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      # DOWN:
      - WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT
      - WG_POST_DOWN=iptables -D FORWARD -o wg0 -j ACCEPT
      - WG_POST_DOWN=iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
