### DISCUSSION TITLE
New working wg-easy + pihole docker compose example for version 15.

### DISCUSSION THREAD

**Discussion by DirkBraakman** [wg-easy/wg-easy#1747] [Q&A]
Hi,

I've tried making a docker compose file for both wg-easy and pihole, based on the example from August 2024.
The syntax for wg-easy and pihole has changed quite a bit.
I am now trying to make the new version 15 work standalone. I'll add pihole later.

I have this config, and it completely doesn't work.
The webportal isn't accessible. I followed all the documentation. I had some luck with beta 10, but this seems unusable.
I'd appreciate help or a better (tested) compose file for the new beta's.

**Current code:**

```
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15.0.0-beta.11
    container_name: wg-easy
    networks:
      default:
        ipv4_address: 10.42.42.42
    environment:
      - INIT_ENABLED=true
      - INIT_USERNAME=admin # Can be shorter than 8 characters since beta 11
      - INIT_PASSWORD=HIDDEN # At least 1 special character
      - INIT_HOST=HIDDEN DOMAIN
      - INIT_PORT=51820
      - INIT_DNS=1.1.1.1
      - INIT_IPV4_CIDR=10.42.42.0/24
      - INIT_IPV6_CIDR=fdcc:ad94:bacf:61a3::/64 # Mandatory variable because of group 3 requirement
    volumes:
      - /container-configs/wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  default:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
```

**Here is the compose file for version 15 for example:**

```
volumes:
  etc_wireguard:

services:
  wg-easy:
    #environment:
    #  Optional:
    #  - PORT=51821
    #  - HOST=0.0.0.0
    #  - INSECURE=false

    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman Compose
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
```
