### DISCUSSION TITLE
No network

### DISCUSSION THREAD

**Discussion by hvmzx** [wg-easy/wg-easy#1749] [Q&A]
Hello,

I've tried running wg-easy and i get a handshake but nothing else 

![CleanShot 2025-03-18 at 01 01 25@2x](https://github.com/user-attachments/assets/28ecc10a-9ea5-411f-824c-a4c22fc7948e)

this is my docker-compose:

```
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    volumes:
      - $CONFIG_PATH/wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    environment:
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
      - PASSWORD_HASH=$PASSWORD_HASH
      - WG_MTU=1450
      - WG_HOST=$SERVERURL
      - WG_DEVICE=$INTERFACE
      - WG_MTU=1420
      - WG_DEFAULT_DNS=1.1.1.1
```

I've tried the linxuserver/wireguard project with wireguard-ui and it worked well but wanted to switch to this one because of more frequent update and running all in 1 container.

Do you have any idea what could be causing this ? Been searching and searching in vain
