### DISCUSSION TITLE
Use Adguard as DNS

### DISCUSSION THREAD

**Discussion by hvmzx** [wg-easy/wg-easy#1760] [Q&A]
I am trying to make every connection made through wg-easy to go through Adguard's DNS but the latter doesn't show me any traffic. wg-easy works well on its own, but the moment I add the WG_DEFAULT_DNS, it's like nothing happened. I also tried add the container_name instead of the ip so WG_DEFAULT_DNS=adguardhome, but same behavior.
They are both on the same network of course

Here is my compose :

```
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - $CONFIG_PATH/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - LANG=en
      - PASSWORD_HASH=$PASSWORD_HASH
      - WG_HOST=$SERVERURL
      - WG_MTU=1420
      - WG_DEFAULT_DNS=$ADGUARD_CONTAINER_IP
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1ACCEPT
      
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 54:53/tcp
      - 54:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3001:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - $CONFIG_PATH/adguard/workdir:/opt/adguardhome/work
      - $CONFIG_PATH/adguard/confdir:/opt/adguardhome/conf
```
