### DISCUSSION TITLE
How to make wg-easy to listen something different than `0.0.0.0`? (to deploy on `Fly.io`)

### DISCUSSION THREAD

**Discussion by hacker-hackman** [wg-easy/wg-easy#1782] [Q&A]
Hello, dear `wg-easy` community!
I'm trying to deploy on Fly.io. But to everything work properly [this change](https://fly.io/docs/networking/udp-and-tcp/#your-app-needs-to-bind-to-the-fly-global-services-address) is needed:

> ### Your app needs to bind to the fly-global-services address
> 
> To receive UDP packets, your app needs to bind to the special fly-global-services address (that’s it; that’s the address). Just as importantly: it needs to reply to messages using that address.
> 
> You usually need to explicitly bind your UDP service to fly-global-services. Sorry, but 0.0.0.0, *, and INADDR_ANY generally won’t do: Linux will use the wrong source address in replies if you use those.
> 
> But: TCP can’t use fly-global-services
> 
> You can’t bind your TCP service to fly-global-services; the TCP side of your app should probably bind to *.

> ### Your app needs to listen on the same port externally and internally
> 
> Fly will only rewrite the IP addresses for UDP packets. The destination port for inbound packets will not be rewritten. That means if your app receives UDP traffic on port 5000 externally, the app needs to bind to fly-global-services:5000 to receive that UDP traffic.

But I can't find where should I apply this change.

My current setup:

Dockerfile:
```dockerfile
FROM ghcr.io/wg-easy/wg-easy:latest

# Copy our custom entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set our script as the entrypoint
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/bin/dumb-init", "node", "server.js"]
```

entrypoint.sh:
```sh
#!/bin/bash

# Ensure we have the proper networking capabilities
echo "Ensuring proper network configuration..."
sysctl -w net.ipv4.conf.all.src_valid_mark=1
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv6.conf.all.disable_ipv6=0
sysctl -w net.ipv6.conf.all.forwarding=1
sysctl -w net.ipv6.conf.default.forwarding=1

exec "$@"
```

fly.toml:
```toml
app = "myapp"
primary_region = "mad"
swap_size_mb = 1024

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "51821"
  HOST = "0.0.0.0"

[mounts]
  source = "etc_wireguard"
  destination = "/etc/wireguard"
  initial_size = '1gb'
  
[[services]]
  protocol = "udp"
  internal_port = 51820

  [[services.ports]]
    port = 51820

[[services]]
  protocol = "tcp"
  internal_port = 51821

  [[services.ports]]
    port = 51821

[[restart]]
  policy = 'always'
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
```

.env:
```sh
WG_HOST=myapp.fly.dev

INIT_ENABLED=true

INIT_USERNAME=*****
INIT_PASSWORD=*****
INIT_HOST=myapp.fly.dev  # not sure if it's correct. we already set WG_HOST
INIT_PORT=51820
INIT_DNS=8.8.8.8
INIT_IPV4_CIDR=10.8.0.0/24
INIT_IPV6_CIDR=2001:0DB8::/32
```
