### DISCUSSION TITLE
Working Docker Swarm solution

### DISCUSSION THREAD

**Discussion by devantler** [wg-easy/wg-easy#180] [Show and tell]
Preface: I have tried a multitude of ways to get wg-easy to work within an overlay network, but I have not been able to find a way to let it discover devices on the local network in this mode. Therefore I here present a solution where it works as intended WHILE running in docker swarm.

```
version: '3.8'

services:
  wireguard:
    image: weejewel/wg-easy:5
    environment:
      WG_HOST: ${WIREGUARD_VPN_SUBDOMAIN:-vpn}.${DOMAIN:?}
      PASSWORD: ${WIREGUARD_PASSWORD?}
      WG_DEFAULT_DNS: ${WIREGUARD_DNS:-192.168.1.1}
    volumes:
      - wireguard_etc_wireguard:/etc/wireguard
    networks:
      - host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

networks:
  host:
    name: host
    external: true

volumes:
  wireguard_etc_wireguard:
```

Hope this is of use to someone having trouble setting it up.

Some findings:
- If you use Portainer you have to deploy it manually. Capabilities are not yet supported by Portainer, so this will not run when deployed from there.
- WireGuard DOES NOT give you a VPN IP if you are behind a carrier-grade NAT. In this case you will still be given the public IP assigned to you by your ISP.
