### DISCUSSION TITLE
the schema was changed. you have to delete ......????

### DISCUSSION THREAD

**Discussion by phill22** [wg-easy/wg-easy#1809] [Q&A]
hello,

first of all i'd like to say thank you for this project. i'm playing around an testing some new thins. in production i use vx3r/wg-gen-web, but there are now more working on new things / fixing bugs since two years.  so i'm looking for some new wireguard scripts. i start with v15 beta 10 on wg-easy and it is working okay (except de double nat from the docker bridge).

i'm not realy familiar with docker and this is my first try to use docker-compose. so i have no idea with file i must delete and i need a tutorial.

> the schema was changed. you have to delete the volume / folder / database for the migrations to run

but were???????

i found the database folder on `/var/lib/docker/overlay2/2349bbe0775504e2cd45e0eda37f6908422943556a296185064f3647423535bb/merged/app/server/database`
and `/var/lib/docker/overlay2/dfca45606cdd1d184544a533e8fbd0bea3a7f5bb91c236c7f8669d61dca143dc/diff/app/server/database`
on the docker host and 
`./server/database`
inside the docker container

deleting is not working. if i upgrade from beta 11 to beta 12 i can't login anymore an the docker host says the container is unhealthy. the only thing that is working, is to remove the wg-easy.db file on the host and rerun the setup process.  but so i lose all configuration and clients. thats very frustrating.

this is my docker-compose.yml (i use caddy as reversproxy on the host (for ssl cert))

```

services:

  wg-easy:
    environment:
      - PORT=80
      - HOST=10.42.42.42
      - INSECURE=true

    image: ghcr.io/wg-easy/wg-easy:15.0.0-beta.11
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - /opt/wg-easy/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "53:55514/udp"
      - "55514:55514/udp"
      - "127.0.0.1:8080:80/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    networks:
      wg:
        ipv4_address: 10.42.42.53
    hostname: adguard
    restart: unless-stopped
#    ports:
#      - "53:53/tcp" # unverschl  sseltes DNS
#      - "53:53/udp" # unverschl  sseltes DNS
#      - "67:67/udp" # DHCP
#      - "68:68/udp" # DHCP
#      - "127.0.0.1:8153:80/tcp" # Admin-Webobefl  che & DNS over HTTPS
#      - "443:443/tcp" # Admin-Webobefl  che & DNS over HTTPS
#      - "443:443/udp" # Admin-Webobefl  che & DNS over HTTPS
#      - "3000:3000/tcp" # Ersteinrichtung
#      - "853:853/tcp" # DNS over TLS
#      - "853:853/udp" # DNS over Quic
#      - "784:784/udp" # DNS over Quic
#      - "8853:8853/udp" # DNS over Quic
#      - "5443:5443/tcp" # DNSCrypt
#      - "5443:5443/udp" # DNSCrypt
    volumes:
      - "/opt/wg-easy/adguard/workdir:/opt/adguardhome/work"
      - "/opt/wg-easy/adguard/confdir:/opt/adguardhome/conf"
      - "/etc/localtime:/etc/localtime:ro"


networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64


```

and this i used for upgrading from b11 to b12

`docker compose -f /opt/wg-easy/docker-compose.yml down; sleep 1; nano /opt/wg-easy/docker-compose.yml; docker compose -f /opt/wg-easy/docker-compose.yml pull; sleep 1; docker compose -f /opt/wg-easy/docker-compose.yml up -d;`

thanks for helping
lg phill

ps: sorry for my english :)
