### DISCUSSION TITLE
Guide: SSH Port Forwarding to Host on Docker Desktop (Mac) via Wireguard - Requires socat Relay

### DISCUSSION THREAD

**Discussion by rafjaf** [wg-easy/wg-easy#1810] [Q&A]
### 1. Environment:

Image: ghcr.io/wg-easy/wg-easy (latest as of 2025-04-13)

Host OS: macOS Sequoia 15.3.2

Docker: Docker Desktop for Mac (4.38.0)

### 2. Goal:

To configure wg-easy running in Docker on macOS so that connecting to the WireGuard server's IP (e.g., 10.8.0.1) on port 22 from a WireGuard client successfully forwards the connection to the sshd service running on the macOS host machine.

### 3. Problem Encountered:

Using standard iptables DNAT and MASQUERADE rules within WG_POST_UP to forward port 22 fails, typically resulting in connection timeouts or resets.

Initial attempts using `iptables -t nat -A PREROUTING -i wg0 -p tcp --dport 22 -j DNAT --to-destination <HOST_LAN_IP>:22` combined with various MASQUERADE rules failed.

Further investigation with `tcpdump` inside the container and on the host revealed that Docker Desktop for Mac's network proxy intercepts container-to-host traffic, often translating it via the host's loopback interface (127.0.0.1) or using its internal gateway IPs (e.g., 192.168.65.x, resolved via host.docker.internal).

While the host sshd received SYN packets (via the proxy) and sent SYN-ACK replies, the container's kernel often failed to send the final ACK to complete the TCP handshake when using only iptables. This is likely due to connection tracking (conntrack) confusion caused by the combination of WireGuard (wg0), iptables NAT/forwarding across interfaces, and the Docker Desktop network proxy translation.

### 4. Solution: iptables Redirect + socat Relay

The reliable solution involves bypassing kernel-level forwarding for the SSH connection and using a user-space relay (socat) within the wg-easy container.

#### Concept:

iptables redirects incoming traffic on wg0:22 to the container's loopback interface (e.g., 127.0.0.1:12222).

socat listens on 127.0.0.1:12222.

When socat accepts a connection, it initiates a new, separate TCP connection from the container (using its Docker bridge IP, e.g., 172.18.x.x) to the host via host.docker.internal (resolved dynamically) on port 22.

Docker Desktop handles this second connection normally, and socat relays data between the two connection legs. This avoids the conntrack issues seen with pure iptables.

#### Implementation Steps:

a) Custom Dockerfile: Create a Dockerfile to add dependencies (socat and bind-tools for dig used for dynamic IP resolution).

```
# Start from the official wg-easy image
FROM ghcr.io/wg-easy/wg-easy:latest

# Run subsequent commands as root
USER root

# Update package lists and install socat and bind-tools, then clean up
RUN apk update && \
    apk add --no-cache socat bind-tools && \
    echo "socat and bind-tools installed."

# No need to switch user back, wg-easy needs root for wg-quick
# Original CMD is inherited
```

b) docker-compose.yml Configuration: Modify your docker-compose.yml to build the custom image, mount necessary volumes, add capabilities, set crucial sysctls, and define the WG_POST_UP/WG_POST_DOWN environment variables.

```yaml
services:
  wg-easy:
    build: . # Build from Dockerfile in current directory
    container_name: wg-easy # Or your preferred name
    environment:
      # --- Essential wg-easy ENV VARS ---
      # Example: Adjust WG_HOST, PASSWORD, WG_DEFAULT_ADDRESS etc. as needed
      - WG_HOST=your.vpn.domain.com
      - PASSWORD=your_webui_password
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_ALLOWED_IPS=10.8.0.0/24, 192.168.0.0/16 # Example: Add host LAN if needed

      # --- Port Forwarding via socat ---
      - WG_POST_UP=
          iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -d 172.18.0.0/16 -j MASQUERADE;
          iptables -A FORWARD -i wg0 -j ACCEPT;
          iptables -A FORWARD -o wg0 -j ACCEPT;
          iptables -t nat -A PREROUTING -i wg0 -p tcp --dport 22 -j DNAT --to-destination 127.0.0.1:12222;
          echo "Attempting to resolve host.docker.internal and start socat..." ;
          socat TCP4-LISTEN:12222,bind=127.0.0.1,fork,reuseaddr TCP4:$(dig +short host.docker.internal A | head -n 1):22 &
      - WG_POST_DOWN=
          iptables -t nat -D PREROUTING -i wg0 -p tcp --dport 22 -j DNAT --to-destination 127.0.0.1:12222;
          iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -d 172.18.0.0/16 -j MASQUERADE;
          iptables -D FORWARD -i wg0 -j ACCEPT;
          iptables -D FORWARD -o wg0 -j ACCEPT;      

    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp" # Web UI
    volumes:
      - ./data:/etc/wireguard # Or your volume path
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # --- Essential sysctls for forwarding and routing to localhost ---
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.all.route_localnet=1
    restart: unless-stopped
```

c) Ensure Host sshd is Running: Verify the 'Remote Login' service is enabled in macOS System Settings -> Sharing and that sshd is listening (check with sudo lsof -i -P | grep LISTEN | grep sshd on the host).

### 5. Key Takeaways:

Direct iptables forwarding from wg0 to host.docker.internal (or host IPs) often fails on Docker Desktop for Mac due to networking complexities and potential conntrack issues.

Using `socat` to relay the connection between the WireGuard interface (via loopback) and the host connection (via eth0) successfully bypasses these issues.

A custom Docker image is needed to add `socat` and `bind-tools` (for dynamic IP lookup using `dig`).

Specific sysctls (net.ipv4.ip_forward, net.ipv4.conf.all.route_localnet) are required in the Docker Compose configuration.

Resolving host.docker.internal dynamically using `dig +short host.docker.internal A` within the `socat` command in WG_POST_UP is recommended over hardcoding potentially unstable internal IPs.

This setup allows successfully SSH'ing to the host machine via the WireGuard tunnel IP (e.g., ssh your_mac_user@10.8.0.1). 

### 6. Credits:

I spent much time trying to resolve this. I couldn't find any solution on the web, and ChatGPT and Claude were of little of no help, insisting that it could not be done with Wireguard running on Docker on a Mac (which we now know is false). Only Gemini 2.5 Pro Preview 03-25 allowed me to find the solution summarized above, after much back-and-forth. I also asked it to summarize the solution in the post above, which will hopefully help others facing similar challenges!
