### DISCUSSION TITLE
Migration from v14 to v15: Port configuration and critical environment variables

### DISCUSSION THREAD

**Discussion by IoSonoPiero** [wg-easy/wg-easy#1900] [Q&A]
### Background

I'm trying to migrate from v14 to v15 of wg-easy but I'm facing several compatibility issues. According to the migration guide, v15 is a complete rewrite with a setup wizard, but I need to maintain specific configurations that seem to be no longer supported or documented.
Sorry if what I ask here is dumb, but I'm not an expert and I'm learning.

### Current Working Configuration (v14)

```yaml
services:
  wg-easy:
    environment:
      - LANG=it
      - WG_HOST=93.93.93.93
      - PASSWORD_HASH=HASHEDPASSWORD
      - PORT=51821
      - WG_PORT=51821
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=192.168.1.0/24, 0.0.0.0/0, ::/0
      - WG_PERSISTENT_KEEPALIVE=25
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3

    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51821:51821/udp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - pangolin

networks:
  pangolin:
    external: true
```

### Attempted v15 Configuration

```yaml
volumes:
  etc_wireguard:

services:
  wg-easy:
    #environment:
    #  Optional:
    #  - PORT=51821
    #  - HOST=0.0.0.0
    #  - INSECURE=false

    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
      pangolin: # Connect the service to external "pangolin" network
    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

networks:
  pangolin:
    external: true
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
```

### Issues and Questions

**Note**: I understand that `WG_HOST` and `PASSWORD_HASH` are now handled by the v15 setup wizard where I can set the public IP and create username/password through the dashboard.

1. **Critical Port Configuration Issue**: How can I modify the v15 configuration to use port 51821 UDP instead of 51820? I need to use port 51821 because another service (pangolin) is already using port 51820. In v14, I used:
    - `WG_PORT=51821` environment variable
    - `"51821:51821/udp"` port mapping

But in the v15 example, the environment variables are commented out and it uses port 51820 by default.
2. **Missing Critical Environment Variables**: I need several environment variables that were working in v14:
    - **`WG_ALLOWED_IPS=192.168.1.0/24, 0.0.0.0/0, ::/0`** (critical for LAN access - without this I cannot access my home LAN network `192.168.1.0/24` through the VPN)
    - `WG_DEFAULT_DNS=1.1.1.1` (custom DNS settings)
    - `WG_PERSISTENT_KEEPALIVE=25` (connection stability)
3. **UI Configuration**: Are `UI_TRAFFIC_STATS=true` and `UI_CHART_TYPE=3` (UI configuration for traffic monitoring) now handled internally by v15, or do I still need to configure them manually?

### Specific Questions

1. **How can I configure v15 to use port 51821 UDP for WireGuard?** Do I need to add `WG_PORT=51821` to the environment variables and change the port mapping to `"51821:51821/udp"`?
2. **Are the critical v14 environment variables still supported in v15?** Specifically:
    - **`WG_ALLOWED_IPS` for LAN access (`192.168.1.0/24`)** - this is the most critical one
    - `WG_DEFAULT_DNS` and `WG_PERSISTENT_KEEPALIVE` for connection settings
3. **How can I ensure LAN access is maintained** when migrating to v15? Is there an alternative way to configure allowed IPs if the `WG_ALLOWED_IPS` environment variable is no longer supported?

The most critical issues are:

- **Port configuration**: Using 51821 UDP instead of 51820
- **LAN access**: Maintaining access to my home LAN (`192.168.1.0/24`) through the VPN connection

Any guidance on how to configure these aspects in v15 would be greatly appreciated.
