### DISCUSSION TITLE
Additional networks breaks internet access on clients

### DISCUSSION THREAD

**Discussion by eiqnepm** [wg-easy/wg-easy#1909] [Q&A]
I'm trying to add an additional network to allow my reverse proxy to access WireGuard Easy.

Unfortunately internet access on my clients breaks whenever I add my internal Docker network as an external network.

There's no indication of errors, my assumption is that WireGuard Easy is trying to access the internet from the internet network instead of the dedicated `wg` network.

Any help would be much appreciated, thanks!

<details><summary>Docker Compose</summary>
<p>

```yaml
services:
  wg-easy:
    cap_add:
      - "NET_ADMIN"
      - "SYS_MODULE"
    container_name: "wg-easy"
    image: "ghcr.io/wg-easy/wg-easy:15"
    networks:
      wg:
        ipv4_address: "10.42.42.42"
        ipv6_address: "fdcc:ad94:bacf:61a3::2a"

      gerbil:
    ports:
      - "51820:51820/udp"
      # - "51821:51821/tcp"
    restart: "unless-stopped"
    sysctls:
      - "net.ipv4.ip_forward=1"
      - "net.ipv4.conf.all.src_valid_mark=1"
      - "net.ipv6.conf.all.disable_ipv6=0"
      - "net.ipv6.conf.all.forwarding=1"
      - "net.ipv6.conf.default.forwarding=1"
    volumes:
      - "./root/etc/wireguard:/etc/wireguard"
      - "/lib/modules:/lib/modules:ro"

networks:
  wg:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      config:
        - subnet: "10.42.42.0/24"
        - subnet: "fdcc:ad94:bacf:61a3::/64"
      driver: "default"

  gerbil:
    external: true
```

</p>
</details>
