### DISCUSSION TITLE
Cannot access the web interface

### DISCUSSION THREAD

**Discussion by kivadiu** [wg-easy/wg-easy#1955] [Q&A] [answered]
Hi,
I installed wg-easy 15 with docker compose on my raspberry pi but I'm blocked immediately because I cannot access the web interface. I tried to launch chromium on the raspberry with URL http://127.0.0.1:51821 or http://localhost:51821 but I do not get anything.
I configured docker-compose as follows:
```
services:
  wg-easy:
    environment:
    #  Optional:
      - PORT=51821
      - HOST=my.domain.name
      - INSECURE=true
```
The rest is untouched. I also tried without `PORT` and `HOST` but the web interface is always unreachable.
Thanks
