### DISCUSSION TITLE
Failure to Handshake on Mobile/ Computers

### DISCUSSION THREAD

**Discussion by PapayaPlant** [wg-easy/wg-easy#1961] [Q&A]
So I am trying to setup WG-Easy so I can access Vaultwarden when I am away from home. I am new to all this so learning as I go.

So far:

- I have setup Vaultwarden with a Cloudflare tunnel, I have setup an application that required a OTP before it provides access and also it's restricted currently to my country and only via my IP at home. This all works well.
- I have setup and installed Traefik, I can access the control panel
- I have setup WG-Easy & can access Wireguard config page.

I have been following the guide on the WG-Easy site:

https://wg-easy.github.io/wg-easy/latest/examples/tutorials/basic-installation/

I have setup a tunnel in Wireguard.

I don't seem to be getting any errors in my logs from either containers. But the phone app just does not connect, seems to be constantly trying the handshake but failing.

Ports setup on my router, all are the same for internal and external.

- 51820 (to my server internal IP) - UDP
- 443 (to my server internal IP) - TCP
- 80 (to my server internal IP) - TCP

Cloudflare setup:

- Both domains for WG-Easy and Traefik are setup for my public IP under a type A record and proxied.

Let me know if other details are needed to help, just been really struggling with the troubleshooting, I appreciate any help!

YML's WG-Easy Docker-Compose:

```
volumes:                                                                                                                 
  etc_wireguard:                                                                                                         
                                                                                                                         
services:                                                                                                                
  wg-easy:                                                                                                               
    image: ghcr.io/wg-easy/wg-easy:15                                                                                    
    container_name: wg-easy                                                                                              
    networks:                                                                                                            
      traefik: {}                                                                                                        
      wg:                                                                                                                
        ipv4_address: 10.42.42.42                                                                                        
        ipv6_address: fdcc:ad94:bacf:61a3::2a                                                                            
    volumes:                                                                                                             
      - etc_wireguard:/etc/wireguard                                                                                     
      - /lib/modules:/lib/modules:ro                                                                                     
    ports:                                                                                                               
      - "51820:51820/udp"                                                                                                
      - "51821:51821/tcp"                                                                                                
    restart: unless-stopped                                                                                              
    cap_add:                                                                                                             
      - NET_ADMIN                                                                                                        
      - SYS_MODULE                                                                                                       
    sysctls:                                                                                                             
      - net.ipv4.ip_forward=1                                                                                            
      - net.ipv4.conf.all.src_valid_mark=1                                                                               
      - net.ipv6.conf.all.disable_ipv6=0                                                                                 
      - net.ipv6.conf.all.forwarding=1                                                                                   
      - net.ipv6.conf.default.forwarding=1                                                                               
    labels:                                                                                                              
      - "traefik.enable=true"                                                                                            
      - "traefik.http.routers.wg-easy.rule=Host(`subdomain.domain.com`)"                                               
      - "traefik.http.routers.wg-easy.entrypoints=websecure"                                                             
      - "traefik.http.routers.wg-easy.tls=true"                                                                          
      - "traefik.http.routers.wg-easy.tls.certresolver=letsencrypt"                                                      
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"                                                   
                                                                                                                         
networks:                                                                                                                
  wg:                                                                                                                    
    driver: bridge                                                                                                       
    enable_ipv6: true                                                                                                    
    ipam:                                                                                                                
      driver: default                                                                                                    
      config:  
```

YML for Traefik Docker Compose:

```
services:                                                                                                                
    traefik:                                                                                                             
        image: traefik:3.3                                                                                               
        container_name: traefik                                                                                          
        restart: unless-stopped                                                                                          
        ports:                                                                                                           
            - '80:80'                                                                                                    
            - '443:443/tcp'                                                                                              
            - '443:443/udp'                                                                                              
        volumes:                                                                                                         
            - /etc/localtime:/etc/localtime:ro                                                                           
            - /etc/timezone:/etc/timezone:ro                                                                             
            - /var/run/docker.sock:/var/run/docker.sock                                                                  
            - /etc/docker/containers/traefik/traefik.yml:/traefik.yml:ro                                                 
            - /etc/docker/containers/traefik/traefik_dynamic.yml:/traefik_dynamic.yml:ro                                 
            - /etc/docker/containers/traefik/acme.json:/acme.json                                                        
                                                                                                                         
        networks:                                                                                                        
            - traefik                                                                                                    
                                                                                                                         
networks:                                                                                                                
    traefik:                                                                                                             
        external: true    
```                                                                                                           

Traefik:

```
log:                                                                                                                     
    level: INFO                                                                                                          
                                                                                                                         
entryPoints:                                                                                                             
    web:                                                                                                                 
        address: ':80/tcp'                                                                                               
        http:                                                                                                            
            redirections:                                                                                                
                entryPoint:                                                                                              
                    to: websecure                                                                                        
                    scheme: https                                                                                        
    websecure:                                                                                                           
        address: ':443/tcp'                                                                                              
        http:                                                                                                            
            middlewares:                                                                                                 
                - compress@file                                                                                          
                - hsts@file                                                                                              
            tls:                                                                                                         
                certResolver: letsencrypt                                                                                
        http3: {}                                                                                                        
                                                                                                                         
api:                                                                                                                     
    dashboard: true                                                                                                      
                                                                                                                         
certificatesResolvers:                                                                                                   
    letsencrypt:                                                                                                         
        acme:                                                                                                            
            email: EMAIIL HERE                                                                  
            storage: acme.json                                                                                           
            httpChallenge:                                                                                               
                entryPoint: web                                                                                          
                                                                                                                         
providers:                                                                                                               
    docker:                                                                                                              
        watch: true                                                                                                      
        network: traefik                                                                                                 
        exposedByDefault: false                                                                                          
    file:                                                                                                                
        filename: traefik_dynamic.yml                                                                                    
                                                                                                                         
serversTransport:                                                                                                        
    insecureSkipVerify: true  
```

Traefik Dynamic

```
http:                                                                                                                    
    middlewares:                                                                                                         
        services:                                                                                                        
            basicAuth:                                                                                                   
                users:                                                                                                   
                    - 'DETAILS:DETAILS'             
        compress:                                                                                                        
            compress: {}                                                                                                 
        hsts:                                                                                                            
            headers:                                                                                                     
                stsSeconds: 2592000                                                                                      
    routers:                                                                                                             
        api:                                                                                                             
            rule: Host(`subdomain.domain.com`)                                                                         
            entrypoints:                                                                                                 
                - websecure                                                                                              
            middlewares:                                                                                                 
                - services                                                                                               
            service: api@internal                                                                                        
                                                                                                                         
tls:                                                                                                                     
    options:                                                                                                             
        default:                                                                                                         
            cipherSuites:                                                                                                
                - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256                                                                  
                - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384                                                                  
                - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256                                                            
            sniStrict: true        

```
