### DISCUSSION TITLE
How do I expose other services on my Server where wg-easy is running in Docker?

### DISCUSSION THREAD

**Discussion by OmkoBass** [wg-easy/wg-easy#1966] [Q&A]
I hosted wg-easy with Docker Compose on my server. I have services running on port 80, port 8000 and port 9090.

How do I setup the wg-easy project so that Wireguard Clients can access ports on the server? 
When I connect with a client that has the VPN ip of `10.8.0.2` and I go to the I presume servers VPN ip of `10.8.0.1` I get no response.

Here's my `docker-compose.yml` file for `wg-easy`.

```yml
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - ./wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    extra_hosts:
          - "host.docker.internal:host-gateway"
```

I would like to have this `docker-compose.yml` isolated and not have other services inside of it.
