### DISCUSSION TITLE
wg-easy in combination with official adguard

### DISCUSSION THREAD

**Discussion by walmer26** [wg-easy/wg-easy#229] [Show and tell]
Dear All, I have tested this wireguard image and it is the best I have use so far. Thank you WeeJeWel. I have instaled adding adguard to the compose file and it is working perfect! I hope is working for you guys, I had it like that as I need to my child phone for parental control, and Adguard is better identifying and blocking even if the site is not in a list. 

```yml
version: "3"
networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  wg-easy:
    depends_on: [adguard]
    image: weejewel/wg-easy
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=<YOUR DDNS>
      - PASSWORD=<YOUR PASSWORD FOR THE WEB ACCESS>
      - WG_PORT=51820
      - WG_DEFAULT_DNS=10.2.0.100 # Set it to point to adguard/pihole
      # OPTIONAL:
      # - WG_DEFAULT_ADDRESS=10.6.0.0
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.1.0/24, 10.2.0.0/24
    volumes:
      - "./wg-easy:/etc/wireguard"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    environment:
      TZ: "America/New_York"
    volumes:
      - "./wg-easy/opt-adguard-work:/opt/adguardhome/work"
      - "./wg-easy/opt-adguard-conf:/opt/adguardhome/conf"
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.2.0.100
```
