### DISCUSSION TITLE
Peer-specific AllowedIPs via peer labelling

### DISCUSSION THREAD

**Discussion by rudasn** [wg-easy/wg-easy#337] [Ideas]
One of the nice things about `wg-easy` is how easy it is to just get it up and running. However, it seems that the default configuration (`WG_ALLOWED_IPS`) only allows for an "all or nothing" approach - either have all traffic for all peers go through the Wireguard network and have all peers available to each other, or nothing.

There is an open issue (and associated PR) that discusses and implements the ability to define the `AllowedIPs` setting for each peer, so that more control is provided to the user on how peers are to communicated with each other (or none at all). https://github.com/WeeJeWel/wg-easy/issues/243

I am proposing a different approach whereby the user is able to:

1) Apply one or more `label` or `tag` to each peer
2) Specify, using said `label`, which peers to include in the `AllowedIPs` section

Changes proposed:

- Add `labels` property (array) to peer configuration
- Add `allowedPeers` property (array) to peer configuration
- When requesting the configuration of each peer, and determining the `AllowedIPs` setting, use the peer's `allowedPeers` property to find the IPs of related peers, ie. those whose `labels` property include any of the labels specified in `allowedPeers`.
- Allow for wildcards in the `allowedPeers` configuration.

For example (using yaml for readability):

```yaml
# 
# Peer 1: A server used for development
# 
- name: Server A
  allowedPeers:
    - dev

#
# Peer 2: A server used by developers and support staff
# 
- name: Server B
  allowedPeers:
    - dev
    - support

#
# Peer 3: Developer workstation
#
- name: Developer 1
  labels:
    - dev


#
# Peer 4: Support staff workstation
#
- name: Support Staff 1
  labels:
    - support
```

This configuration would allow any peer with label `dev` to access both server A and server B, and any peer with label `support` to access only server B. The user is never asked to specify IP addresses or remember them or keep them up to date.

So when new development servers are added to the network, all we have to do is add `dev` to their `allowedPeers` property. Of course, users (eg. developers, support staff) would need to download their configuration again, but that's all they have to do. To revoke access we just need to update either the `allowedPeers` property or the `labels` property of any of the source/target peer(s). 

I understand that this type of scenario is probably out of scope for the context of `wg-easy`, but I think it is well within it's philosophical scope: making it easy to get wireguard networks up and running, even if more restricted access controls are required.

What do you guys think?
