### DISCUSSION TITLE
Block access to the Local Lan

### DISCUSSION THREAD

**Discussion by alekindrefdez** [wg-easy/wg-easy#385] [General]
Hello all,
I've been using this stack quite a while to access my server remotely and works great!
I would like to know if there is any option to restrict the access of the local network since I'm planning to create another service for Netflix usage, therefore I don't want these peers to access the local network but only the public IP. My stack looks like below: 

```
version: "3"
services:
  wg-easy-webui:
    image: weejewel/wg-easy
    environment:
      - PASSWORD=aNyPassWorD
      - WG_HOST=mydomain.com
      - SERVERPORT=51820
      - WG_DEFAULT_DNS=192.168.1.1
    volumes:
      - /home/wireguard/wg-easy:/etc/wireguard
    restart: always
    ports:
      - "51820:51820/udp"
#      - "51821/tcp" 
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

  nginx:
    image: nginx
    volumes:
      - /home/wireguard/wg-easy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/ssl/key-wg.pem:/etc/nginx/ssl/key-wg.pem       
      - /etc/nginx/ssl/cert-wg.pem:/etc/nginx/ssl/cert-wg.pem    
    ports:
      - "4334:443"      
    depends_on:
      - wg-easy-webui
```

Maybe there is any service environment that I'm not aware of in other to make it work this way. 

Thank you in advance!
