### DISCUSSION TITLE
How with vps (ubuntu) to access wireguard ip addresses that are in docker?

### DISCUSSION THREAD

**Discussion by Simplejke** [wg-easy/wg-easy#556] [Q&A]
I have a vps that has ubuntu 22.04 installed. There I picked up wg-easy and nginx proxy manager. Everything is working. I can't figure out how you can access wiregard's ip address while in a vps but not in a wg-easy container. This is necessary in order to make a proxy in NPM on your local computer.

I tried add param `--network host`, but then need to remove 
`--sysctl="net.ipv4.conf.all.src_valid_mark=1"
--sysctl="net.ipv4.ip_forward=1"`
Result is: I have access to wireguards ips, but clients haven't internet

**Comment by Pleonazm** [comment]
You need to add routes for the things behind your WG container in the "Allowed IPs" clause.
If you are using wg-easy in the host mode, you have to add IP forwarding directly on your host, not in the container initialization commands.

**Comment by eandersons** [comment]
You could try to put both Nginx Proxy Manager and WireGuard Easy containers in one Docker network, then WireGuard Easy container will be reachable from Nginx Proxy Manager via its name (`wg-easy`). This is described in Nginx Proxy Manager's documentation: [Best Practice: Use a Docker network](https://nginxproxymanager.com/advanced-config/#best-practice-use-a-docker-network).

**Comment by Simplejke** [comment]
Here is my docker compose config.

```
version: '3.8'
services:
   npm:
     container_name: npm
     image: 'jc21/nginx-proxy-manager:latest'
     restart: unless-stopped
     ports:
       # These ports are in format <host-port>:<container-port>
       - '80:80' # Public HTTP Port
       - '443:443' # Public HTTPS Port
       - '81:81' # Admin Web Port
       # Add any other Stream port you want to expose
       # - '21:21' # FTP
     environment:
       # Mysql/Maria connection parameters:
       DB_MYSQL_HOST: "db"
       DB_MYSQL_PORT: 3306
       DB_MYSQL_USER: "npm"
       DB_MYSQL_PASSWORD: "npm"
       DB_MYSQL_NAME: "npm"
       # Uncomment this if IPv6 is not enabled on your host
       # DISABLE_IPV6: 'true'
     volumes:
       - ~/nginx-proxy-manager/data:/data
       - ~/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
     depends_on:
       -db

   db:
     container_name: db
     image: 'jc21/mariadb-aria:latest'
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: 'npm'
       MYSQL_DATABASE: 'npm'
       MYSQL_USER: 'npm'
       MYSQL_PASSWORD: 'npm'
     volumes:
       - ~/nginx-proxy-manager/mysql:/var/lib/mysql

   wg-easy:
     container_name:wg
     environment:
       # ⚠️ Required:
       # Change this to your host's public address
       - WG_HOST=[my host ip]
       # optional:
       - PASSWORD=[my password]
       #-WG_PORT=51820
       #- WG_DEFAULT_ADDRESS=10.8.0.x
       #- WG_DEFAULT_DNS=10.8.1.20, 10.8.1.20
       #- WG_ALLOWED_IPS=0.0.0.0/0
     image: weejewel/wg-easy
     volumes:
       - ~/.wg-easy:/etc/wireguard
     ports:
       - "51820:51820/udp"
       - "51821:51821/tcp"
     restart: unless-stopped
     cap_add:
       -NET_ADMIN
       - SYS_MODULE
     sysctls:
       -net.ipv4.ip_forward=1
       - net.ipv4.conf.all.src_valid_mark=1
```

If I run it, then everything works as it should - there is access to both UI interfaces, the VPN works correctly on all devices.
All three containers are on the same default network created by docker compose "npmwg_default" and ping each other.
```
docker network inspect npmwg_default
[
     {
         "Name": "npmwg_default",
         "Id": "cb74949d9fde62ea216d3bb40b16b0cdc0144b12ca0c376db2d771b02d466566",
         "Created": "2023-05-24T15:23:36.590359358+03:00",
         "Scope": "local",
         "driver": "bridge",
         "EnableIPv6": false,
         IPAM: {
             "driver": "default",
             Options: null
             "Config": [
                 {
                     Subnet: "172.19.0.0/16",
                     "Gateway": "172.19.0.1"
                 }
             ]
         },
         "Internal": false
         Attachable: false
         "Ingress": false
         "ConfigFrom": {
             "Network": ""
         },
         "ConfigOnly": false
         "Containers": {
             "54d14d4765477b7fed82054c56522bfb0d28535126fc6dbac629de7cb81fdd3c": {
                 "Name": "wg",
                 "EndpointID": "0284588a3a058eae3bb78ad2ba07c9e0fa017a4b35635e250937db05473e7647",
                 "MacAddress": "02:42:ac:13:00:03",
                 "IPv4Address": "172.19.0.3/16",
                 "IPv6Address": ""
             },
             "a65726a2daf36601db11f17f8aa83363de721b36350252b896094cded6163d15": {
                 "Name": "db",
                 "EndpointID": "35c0e2c096e8eab294893aa08212a1add9641cb088f2b32531af6eb2e3c0bb51",
                 "MacAddress": "02:42:ac:13:00:02",
                 "IPv4Address": "172.19.0.2/16",
                 "IPv6Address": ""
             },
             "cc34da7cfb89b00c5100a16757a96571b9c10aba4261fd6ee03b4727d070e492": {
                 "Name": "npm",
                 "EndpointID": "c18646901d3743beb8ffde26cde1feb621dc07cc928e7f6cb3a30bb59f2375f5",
                 "MacAddress": "02:42:ac:13:00:04",
                 "IPv4Address": "172.19.0.4/16",
                 "IPv6Address": ""
             }
         },
         Options: {},
         Labels: {
             "com.docker.compose.network": "default",
             "com.docker.compose.project": "npmwg",
             "com.docker.compose.version": "2.17.3"
         }
     }
]
```
And I also want to get access from the NPM container to access the ip addresses of connected devices - in order to create a rule in NPM that forwards access to my ip of the local computer connected to the VPN. And there, for example, a web server, nextcloud, docker and etc. have already been raised.

I don't understand how this can be done - and is it possible at all?)
I will be glad for any help.
