### DISCUSSION TITLE
Synology: No access to WireGuard GUI or server services

### DISCUSSION THREAD

**Discussion by cargnellogiacomo** [wg-easy/wg-easy#727] [General]
I installed the wg-easy on my Synology DS723+ (DSM 7.2.1) via docker compose (see below). I can connect to it remotely but I can access all services and webpages that are on a different IP than my Synology (192.168.62.2). Therefore I cannot access the WireGuard and DSM Web GUI or any other services installed on my Synology.

```
wgeasy:
    image: 'ghcr.io/wg-easy/wg-easy:latest'
    network_mode: bridge
    container_name: 'WireGuard'
    restart: always
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    environment:
      - WG_HOST=###HOST###
      - WG_PORT=51821
      - PASSWORD=###PASSWORD###
      - WG_DEFAULT_DNS=192.168.62.2,9.9.9.9
      - WG_PERSISTENT_KEEPALIVE=24
    labels:
      - "com.centurylinklabs.watchtower.scope=other"
    volumes:
      - /volume1/docker/WireGuardNAS:/etc/wireguard
```
