### DISCUSSION TITLE
[Question] Reverse Traffic to Clients from the LAN.

### DISCUSSION THREAD

**Discussion by bram-nijenkamp** [wg-easy/wg-easy#751] [Q&A]
Hi have been using your project for a couple years now.
What I was wondering and maybe you know or might be willing to intergrate it into the project or docs is how to reverse connect from the docker host's LAN and other computers to a wireguard client.

What I tried for now is using the docker compose sample from this github but giving it a custom network using the default driver as to give it a static ip.

config:
```
version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=192.168.178.0/24, 10.8.0.0/24
      - WG_PERSISTENT_KEEPALIVE=9999
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./data:/etc/wireguard:Z
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wireguard_internal:
        ipv4_address: 10.18.0.2
networks:
  wireguard_internal:
    ipam:
      driver: default
      config:
        - subnet: 10.18.0.0/24
 ```

And then i added a static route in my ubi router routing 10.8.0.0/24 to 192.168.178.3 and on the docker host:
```
route add -net 10.8.0.0/24 gw 10.18.0.2
```

vpn-host:/srv/wireguard# ip route
```
default via 192.168.178.1 dev eth0  metric 202 
10.8.0.0/24 via 10.18.0.2 dev br-d16ada0e2ed8 
10.18.0.0/24 dev br-d16ada0e2ed8 scope link  src 10.18.0.1 
172.17.0.0/16 dev docker0 scope link  src 172.17.0.1 
172.18.0.0/16 dev br-447a96e1bb06 scope link  src 172.18.0.1 
172.19.0.0/16 dev br-869c403925e5 scope link  src 172.19.0.1 
172.20.0.0/16 dev br-a8556d96cc47 scope link  src 172.20.0.1 
172.22.0.0/16 dev br-06c1c27181fa scope link  src 172.22.0.1 
172.23.0.0/16 dev br-26d1e9b5bb6f scope link  src 172.23.0.1 
172.24.0.0/16 dev br-6cbb7233cd48 scope link  src 172.24.0.1 
172.25.0.0/16 dev br-817a50e1bff0 scope link  src 172.25.0.1 
192.168.178.0/24 dev eth0 scope link  src 192.168.178.3 
```

but so far I am still unable to ping, might you have any idea? or has it been done before which I am unable to find?

Sincerely,
