### DISCUSSION TITLE
WG_POST_UP not working?

### DISCUSSION THREAD

**Discussion by xploz1on** [wg-easy/wg-easy#786] [Q&A]
Hi everyone!
First let me paste my setup.
I have a docker compose file:
```
version: "3.8"
services:
  wg-easyX:
    environment:
      # ⚠️ Required:
      # Change this to your host's public IP address
      - WG_HOST=CHANGEME
      # Optional:
      - PASSWORD=CHANGEME
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS= 10.8.0.1
      # - WG_DEFAULT_DNS= 1.1.1.1
      # - WG_MTU=1420
      - WG_ALLOWED_IPS= 0.0.0.0/0
      - WG_PERSISTENT_KEEPALIVE= 25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      - WG_POST_UP=echo "/etc/wireguard/post-up.txt"
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
    image: weejewel/wg-easy
    container_name: wg-easyX
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "8081:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
  ```

And my post-up.txt loos like this:
```
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8080 -j DNAT --to-destination 10.8.0.2
```

Now, with WG_POST_UP commente, i have internet no problem. WIth it uncommented, i have no internet.
Also the redirect doesn't work. I do have in the machine running as 10.8.0.2 (client) a service running on port 80.

So, the main goal is going to the VPN server port 8080 for example, and have it show whats in the client (10.8.0.2) port 8080.

Does 'WG_POST_UP' overwrites the defaults too? Also after uncommenting 'WG_POST_UP' i noticed the post-up.txt file is empty with just 'Post Up' text in the first line.

No idea what i might be doing wrong. Thanks all!
