### DISCUSSION TITLE
Configuration for VPN to other docker services on the same docker network

### DISCUSSION THREAD

**Discussion by arminus** [wg-easy/wg-easy#846] [Q&A]
I'm trying to find out if I could use wg-easy to set up a VPN for multiple services running inside the same network as wg-easy. So far I'm stuck, here's my test setup:

- wg-easy out-of-the-box, running on
```
    networks:
      - secure

networks:
  secure:
    name: secure
    external: true
```
- an nginx test container:
```
  nginx:
    image: nginx:latest
    expose:
      - 80
    networks:
      - secure

networks:
  secure:
    name: secure
    external: true
```
(port 80 is intentionally only exposed inside the docker network)

Now I connect to wireguard with AllowedIPs = 10.8.0.1/32 from some windows client - but I can't connect to 10.8.0.1:80 because that's the wg-easy container. How can I access ports of other containers on that docker network?

Do I need to add a wireguard client to the nginx container so that I can access it from my windows client ort is there same routing which can be done (via WG_POST_UP ?) which would avoid having to add wireguard clients to all docker containers on that network?
