### DISCUSSION TITLE
Where to find a proper changelog?

### DISCUSSION THREAD

**Discussion by Mat-DB** [wg-easy/wg-easy#942] [Q&A]
I just had a problem that I was not able to connect to the internet when connected to wireguard.
Turned out te be a change in environmental variables...

So my question is where can I find a proper changelog to read before I do an update?

Thanks!!
Great project btw! Love it!

**Comment by peterlewis** [comment]
Please can you provide details of the changed environment variable? Wherever possible it has been the aim to provide backwards compatibility, and so this sounds like omission as opposed to intention (or perhaps reversion).

**Comment by Mat-DB** [comment]
I did some tests since I changed more than one variable at once.
I tested with `WG_ALLOWED_IPS=0.0.0.0/0, ::/0` but that wasn't the problem even though it is advised to put IPv6 addresses between `[ ]`.

What turned out te be the problem for me was the `WG_DEVICE` variable. I had it set to my host interface that is connected, but after an update it didn't work anymore. After commenting this everything worked.
The only thing I can think of is that it should be the interface inside the container but I not tried that. I do remember I struggled with that variable when I was setting it up, but that is quite some time ago and I do not remember everything.

Hope that helps. If I need to give more info just ask!

Edit: This is my compose file now,
```yml
---
version: "3.8"
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    hostname: wireguardVPN
    mac_address: ${WIREGUARD_MAC}
    networks:
      macvlan_NET:
        ipv4_address: ${WIREGUARD_IP}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=${PUBLIC_HOST}
      - LANG=en
      
      # Optional
      - PASSWORD=${WEBUI_PASSWORD}
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.0
      - WG_DEFAULT_ADDRESS_RANGE=24
      - WG_DEFAULT_DNS=9.9.9.9
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=0.0.0.0/0, [::/0]
      # - WG_PERSISTENT_KEEPALIVE=25

      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2 #(0 Charts disabled, 1 Line chart, 2 Area chart, 3 Bar chart)
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/wg-easy:/etc/wireguard  # BACKUP
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 51820/udp
      - 51821/tcp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  macvlan_NET:
    name: macvlan_NET
    external: true
```
