### DISCUSSION TITLE
UFW Best practises with WG-Easy Docker

### DISCUSSION THREAD

**Discussion by stantaneous** [wg-easy/wg-easy#980] [Q&A]
I am using the following docker-compose.yml

```yaml
version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=redacted

      # ⚠️ Change the Web UI Password:
      - PASSWORD=redacted

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=8.8.8.8
      - WG_DEFAULT_ADDRESS=10.200.0.x
      - WG_PORT=51825
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=10
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51825:51820/udp"
      - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.200.1.2

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.200.1.0/24
```

I am using ufw firewall on the same server with default deny incoming. While I am able to connect to it using the client but there is no internet on the client. I have already allowed port 51825 on UFW and the connection is working fine. When the client connects, I am able to see the up and down arrow on the WG-Easy Web UI, but the internet does not work on the client. If I try disabling UFW, the internet works fine on the client. 

After some research, I was able to find that we need to allow forwarding the traffic that comes in on the wg0 VPN interface to the eth0 network interface on the server using the command `ufw route allow in on wg0 out on eth0`

But we do not have a wg0 interface when we use docker. Can someone suggest how can we allow the docker network interface in UFW to allow forwarding to ethernet? I do not want to disable UFW on the server for the VPN.
I am also looking for some best practices that we should follow while working with UFW and WG-Easy
