### DISCUSSION TITLE
healthcheck

### DISCUSSION THREAD

**Discussion by stanthewizzard** [wg-easy/wg-easy#989] [Ideas]
Hello could be nice to have an healthcheck for this container.

Thanks

**Comment by peterlewis** [comment]
Agreed!

**Comment by CosasDePuma** [comment]
You can add this to your compose file:

```yml
    healthcheck:
      test: /usr/bin/timeout 5s /bin/sh -c "/usr/bin/wg show | /bin/grep -q interface || exit 1"
      interval: 1m
      timeout: 5s
      retries: 3
```
