### ISSUE TITLE
docker-compose PORT environment variable is acting strangely

### ISSUE THREAD

**Issue by Extroonie** [wg-easy/wg-easy#1008]
This is the working docker-compose.yml:
```yml
version: "3.8"
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      # - LANG=de
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=host

      # Optional:
      - PASSWORD=password
      # - PORT=51821
      - WG_PORT=1524
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "1524:51820/udp"
      - "1525:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
![image](https://github.com/wg-easy/wg-easy/assets/42417143/7b203f87-4b61-4506-8a7c-b990e28b05e2)
And the outputs of `docker ps` and `netstat -tulpn`:
![image](https://github.com/wg-easy/wg-easy/assets/42417143/163ec0df-abd2-4712-a4c2-2efc29cd9ee0)
![image](https://github.com/wg-easy/wg-easy/assets/42417143/1f5247da-8070-4b5a-bc52-0b50216d909b)

Now, with this docker-compose.yml:
```yml
version: "3.8"
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      # - LANG=de
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=host

      # Optional:
      - PASSWORD=password
      - PORT=1525
      - WG_PORT=1524
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "1524:51820/udp"
      - "1525:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
(The only change is commenting out the `PORT` environment variable and setting it to 1525). I cannot seem to connect to the web UI with this docker-compose:
![image](https://github.com/wg-easy/wg-easy/assets/42417143/23d363d0-0916-45ec-a0a1-ff52569edcb8)
The outputs of `docker ps` and `netstat -tulpn`:
![image](https://github.com/wg-easy/wg-easy/assets/42417143/6149660b-c697-4d81-9b22-2ddcf257b450)
![image](https://github.com/wg-easy/wg-easy/assets/42417143/9e6f6711-f1f5-4bdf-b750-d0db8f5ac9e4)

I don't really see a difference between the outputs from before and after adding `PORT` environment variable. I might just be missing something here, and if so, please do let me know!

**Comment by pheiduck** [comment]
We have a similar bug fixed in nightly image please try:
`ghcr.io/wg-easy/wg-easy:nightly`

**Comment by Extroonie** [comment]
The nightly image doesn't seem to have fixed the issue.

**Comment by pheiduck** [comment]
Can't reproduce your issue.

**Comment by Extroonie** [comment]
This my exact docker-compose.yml:
```yml
version: "3.8"
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      # - LANG=de
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=host

      # Optional:
      - PASSWORD=password
      - PORT=1525
      - WG_PORT=1524
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "1524:51820/udp"
      - "1525:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
Outputs of `docker ps` and `netstat -tulpn`;
![image](https://github.com/wg-easy/wg-easy/assets/42417143/7cea9d65-0208-4462-abe9-d3ac101577c4)
![image](https://github.com/wg-easy/wg-easy/assets/42417143/7d833776-3ea6-466b-a99b-ed21bb0d0680)

I can access neither the web UI nor the wireguard vpn.
