### ISSUE TITLE
WG_PORT is not used in .conf file

### ISSUE THREAD

**Issue by goremykin** [wg-easy/wg-easy#1023]
**Describe the bug**
If I specify a custom port, 51820 is still used in conf files.

**To Reproduce**
1. Set WG_PORT to 12345
2. Create a new client
3. Download the conf file and check port

**Expected behavior**
Port 12345 in the conf file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 12 ARM

**Comment by pheiduck** [comment]
If you use latest / 12 tag then this behavior is expected until now.
Try nightly which already ship a fix for the issue you have.
If not please let me know.

**Comment by goremykin** [comment]
@pheiduck, Unfortunately the same on `nightly`. Btw, where I can find list of images / tags?

My docker-compose:
```
version: "3.9"

services:
  wg-ui:
    environment:
      - WG_HOST=wg.domain.com
      - WG-PORT=1820
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - PORT=1821 #web ui
      - PASSWORD=<secret>
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1


    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    volumes:
      - /volumes/wg:/etc/wireguard
    ports:
      - "1820:51820/udp"
      - "1821:1821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-pihole:
        ipv4_address: 10.8.1.2

  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    hostname: <hostname>
    domainname: <domainname>
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 88:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
    environment:
      - WEBPASSWORD=<secret>
      - FTLCONF_LOCAL_IPV4=<ipv4>
      - FTLCONF_LOCAL_IPV6=<ipv6>
      - WEBTHEME=default-dark
      - PIHOLE_DNS_=127.0.0.1#5335

      - DNSMASQ_LISTENING=single
    volumes:
      - /volumes/pihole/pihole:/etc/pihole
      - /volumes/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    networks:
      wg-pihole:
        ipv4_address: 10.8.1.3

networks:
  wg-pihole:
    ipam:
      config:
        - subnet: 10.8.1.0/24
```
