### ISSUE TITLE
no pw when PASSWORD_HASH is passed! 

### ISSUE THREAD

**Issue by KUKARAF** [wg-easy/wg-easy#1122]
**Describe the bug**
when PASSWORD_HASH flag is passed in docker compsoe or docker run directly no password is requested

**To Reproduce**
1. Clone example  docker-compose
2.  `python -c 'import bcrypt; print(bcrypt.hashpw(b"PASSWORD", bcrypt.gensalt(rounds=15)).decode("ascii"))`
4. uncomment PASSWORD_HASH and insert hash
5. run docker-compose up -d 
6. be in shock about the lack of a password 

**Expected behavior**
ask for PASSWORD

# docker-compose.yaml 
```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=de
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=my.hostename.com

      # Optional:
      # - PASSWORD=foobar123 (deprecated use `PASSWORD_HASH` instead)
      #- PASSWORD_HASH='$2b$15$HpD8jpgiTs5Q21nPeYsC1.bjJP6rh6h5LqTZN2aYhvd/Q3dVrwbbu'
      - PASSWORD='A/YLUSAH6SHzyw4N'
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Desktop (please complete the following information):**
 - OS: Armbian 24.5.1 Bookworm with Linux 6.6.31-current-rockchip64
 - Browser Firefox
 - Version 115.11.0esr (64-bit)
