### ISSUE TITLE
Wireguard cannot connect

### ISSUE THREAD

**Issue by yuhuazhu** [wg-easy/wg-easy#1126]
**Describe the bug**
Wireguard failed to establish connection.

**To Reproduce**
1.  Use `docker compose up -d` , 
```
volumes:
  wireguard:
    name: wireguard

networks:
  wireguard:
    name: wireguard

services:
  wg-easy:
    environment:
      - LANG=chs
      # Required!!!
      - WG_HOST=192.9.140.79

      # Optional:
      - WG_PORT=11020
      - WG_DEFAULT_ADDRESS=192.168.71.x
      - WG_DEFAULT_DNS=
      - WG_ALLOWED_IPS=192.168.71.0/24
      - WG_PERSISTENT_KEEPALIVE=25
      - UI_TRAFFIC_STATS=true

    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    volumes:
      - wireguard:/etc/wireguard
    ports:
      - "11020:11020/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wireguard
```
2. Open webui to add the client side and download the configuration file to the local
3. Unable to connect after running locally

**Expected behavior**
Can successfully establish a connection.

**Screenshots**
![wireguard](https://github.com/wg-easy/wg-easy/assets/10030402/da441d51-2902-4f4f-9cee-761bde9cb1c7)

**Server:**
 - OS: Ubuntu 22.04.3 LTS

**Desktop:**
 - OS: macOS 12.6.3

**Smartphone:**
 - Device: iPhoneX
 - OS: iOS 15.4
 - APP: WireGuard
