### ISSUE TITLE
There is no password protection on web UI.

### ISSUE THREAD

**Issue by Skysea45** [wg-easy/wg-easy#1151]
There is no password protection on deployment. (I generated pass with bcrypt and exactly passed to .yml file). It doesnt asks for any password for accesing wg profiles.

![image](https://github.com/wg-easy/wg-easy/assets/33579330/d5647348-ab05-4015-8304-d7ab0f40ad10)

**Comment by valorisa** [comment]
With the hash, no need password.

**Comment by filipkotoucek** [comment]
How is that? I understood it should be a hash of password the user has to enter when accessing the UI. This way if there is no password anyone who accesses the web UI can modify the allowed clients. Am I missing something? I'm running wg-easy in docker using docker compose and facing same issue.

**Comment by pheiduck** [comment]
My WG is protected on older versions with password or on nightly with a hashed password.
I guess it is a wrong configuration on the user side.

**Comment by Duoquote** [comment]
Same applies for me, I think it can be a real issue, here is my config for docker-compose:

```yaml
services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=xxx
      - PASSWORD_HASH=$$2b$$12$$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - WG_DEFAULT_DNS=8.8.8.8
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ./data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "127.0.0.1:51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

Also mine is behind reverse proxy here is my nginx config too if related:

```nginx
upstream wg-easy {
        server localhost:51821;
}

map $http_upgrade $connection_upgrade {
        default keep-alive;
        'websocket' upgrade;
        '' close;
}

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name xxx;

        ssl_certificate xxx;
        ssl_certificate_key xxx;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
                proxy_pass http://wg-easy;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header Host $server_name;
                proxy_redirect http:// https://;
                proxy_buffering off;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
                add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
        }
}
```

And here is the result, there is no prompt for anything, I can just browse to the address I defined and it's open. I also opened cookie section as something is stored there but it is probably cloudflare related. And yes I installed it on a real domain so right now its actually accessible by anyone...

![image](https://github.com/wg-easy/wg-easy/assets/16341937/8e8f7889-845e-4ee5-be36-1030599111e3)
