### ISSUE TITLE
Using files for credential storage

### ISSUE THREAD

**Issue by cliaz** [wg-easy/wg-easy#1152]
**Describe the bug**
I am trying to use files to store credentials and other secret material.
Due to environmental reasons (namely portainer's lack of being able to define a specific .env file), I am not using .env files. Instead, I am using docker secrets.

However, as I am not running docker swarm, I cannot use proper docker secrets. I am instead using this [workaround](https://blog.mikesir87.io/2017/05/using-docker-secrets-during-development/), which is successful with Watchtower and other containers.

The following compose works for Watchtower to retrieve the gmail password from a folder on the local filesystem

```yml
secrets:
  mailer_account_gmail_password:
    file: /mnt/external-workdir/watchtower/secrets/mailer_account_gmail_password

services:  
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    network_mode: bridge
    restart: unless-stopped
    secrets:
      - mailer_account_gmail_password
   environment:
    <snip>
WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: /run/secrets/mailer_account_gmail_password 
```

However it does not work for wg-easy:
```yaml
secrets:
  WIREGUARD_PASSWORD_HASH:
    file: ${SECRETS}/wireguard/wireguard_password_hash

services:
  services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    restart: unless-stopped
    <snip>
    secrets:
       - WIREGUARD_PASSWORD_HASH
    environment:
      <snip>
      # WebUI stuff
      PORT: ${WEBUI_PORT}
      PASSWORD_HASH: /run/secrets/WIREGUARD_PASSWORD_HASH                               # this does not work
      #PASSWORD_HASH: "$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG" # this works
```

The files have 777 perms (for testing), and when I jump into the container I am able to see them mounted and accessible in `/run/secrets`

```shell
wg-easy:/run/secrets# ls -la
total 12
drwxr-xr-x    2 root     root          4096 Jul  7 13:30 .
drwxr-xr-x    1 root     root          4096 Jul  7 13:30 ..
-rw-r--r--    1 root     root            64 Jul  7 13:29 WIREGUARD_PASSWORD_HASH
```

**Expected behavior**
Hash is loaded from file, interpolated into a docker variable, and used by wg-easy

**Additional context**
For reference, I lodged the (almost) exact same bug / feature request in a [different repo](https://github.com/mrlt8/docker-wyze-bridge/issues/1244), if that helps for context
