### ISSUE TITLE
Cannot find module '/app/wgpw'

### ISSUE THREAD

**Issue by SonnieP** [wg-easy/wg-easy#1197]
Per the instructions I tried to create a bcrpyt hash password... trying that command gives me the following error:

[root@host sonnie]# docker run ghcr.io/wg-easy/wg-easy wgpw (I entered my password here)
docker run ghcr.io/wg-easy/wg-easy wgpw (my password was shown here)
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '/app/wgpw'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_ma                    in:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.15.1
[root@host sonnie]#

Any ideas?

**Comment by eandersons** [comment]
That is because you are using image tag that does not have (yet) this functionality. Try `nightly`.

**Comment by SonnieP** [comment]
I'm not following... where do I insert "nightly," and how does that fix the module not found issue? Thanks!

**Comment by eandersons** [comment]
`docker run ghcr.io/wg-easy/wg-easy:nigthly wgpw`

If tag is not specified, `latest` is implied, and currently the `latest` tag does not yet has the functionality you are trying to use.

**Comment by eandersons** [comment]
Did you run container with the image of same tag?
Did you run container with `docker run` or with Compose file?

I suspect that the culprit is that the password hash contains `$`. See #1181 or #1191 depending on how are you running WireGuard Easy container for a solution.

Confusion comes from the fact that the branch `master` is not the production branch, therefore information that can be found on https://github.com/wg-easy/wg-easy might not reflect what is available on production images.

**Comment by SonnieP** [comment]
I ran the command: docker compose up -d && docker compose logs -f

I have the single quote around my hash password and I have cleared cache on my browser. I still get unauthorized. 

I think it's about time I give up on this... not worth two days of my time. I suppose I'll install Wireguard thru my Omada Controller. I thought maybe this would be easier and better, but it has wasted a vast amount of my time and is anything by easy. I never seen a program have so many issues. Truly remarkable that anyone is using it.

**Comment by mcmimik** [comment]
@eandersons There is a typo in your comment (`h` should be before the `t`).

In case someone else on the Internet comes across this issue and wants to quickly copy the command into their console:
```
docker run ghcr.io/wg-easy/wg-easy:nightly wgpw YOUR_PASSWORD
```

**Comment by empwilli** [comment]
Thanks for your work and suggestions. I came here after I figured it out by toying around with the different versions. Do you plan to release the nightly docker container as production soon? Otherwise I'd suggest to add some info into the readme that nightly is necessary :).

**Comment by SonnieP** [comment]
I give up on it… too much to comprehend for this hillbilly.

 

I’m using Tailscale and it is serving my purpose.

 

Regards,

Sonnie

**Comment by spagettikod** [comment]
Just installed wg-easy for the first time and I love it. But I must say that it's quite confusing that the master branch, which is the default page for the project, show documentation that belong to the nightly release and not the current production release.

Using separate feature/version branches and keeping master for latest production would make it easier for new users to get on board.

**Comment by ThunderThorr** [comment]
hello tried using docker run ghcr.io/wg-easy/wg-easy:nightly wgpw TEST123 and when i go to my panel it stays on a loop loading and never enter to the panel,

my config is


docker run -d \
  --name=wg-easy \
  -e LANG=en \
  -e WG_HOST=1.125.5.25 \
  -e PASSWORD_HASH='$2a$12$7tpLWwoiHUPQT0OxuBDike23WBYsZ1cZjaS6p0Xe8AiF1R1kGXdas' \
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy:nightly

**Comment by meddion** [comment]
I get the same error as @ThunderThorr in my console along with the loading screen when using Brave Browser `1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64)` (Safari is fine though):
```
ReferenceError: restoreConfig is not defined
    at Er.eval (eval at mc (vue.min.js:6:105188), <anonymous>:3:6811)
    at t._render (vue.min.js:6:45862)
    at Er.r (vue.min.js:6:79765)
    at t.get (vue.min.js:6:28262)
    at t.run (vue.min.js:6:28995)
    at cn (vue.min.js:6:19867)
    at Array.<anonymous> (vue.min.js:6:23307)
    at Sn (vue.min.js:6:22707)
  ```
  
 I am getting this error on both the nightly (nightly@sha256:b6a799f9d96d735e07d300863bd43d32d7e9f4514bb8e7ed88157c22891f4f3b) and the latest (latest@sha256:4c2c591498aa910ce86a90fa00c4714ffd78dd7556b1f488f226471b97346bc6).
  
My docker-compose.yml:
```yaml
services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=<MY_HOST>
      - WG_DEVICE=<MY_DEVICE>
      - WEBUI_HOST=0.0.0.0
      - PASSWORD=<PASSWORD> # OR PASSWORD_HASH for nightly
    image: ghcr.io/wg-easy/wg-easy:<IMAGE_TAG>
    container_name: wg-easy
    volumes:
      - /etc/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️   Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
