### ISSUE TITLE
Cannot deploy Docker compose file on AlmaLinux firewalld

### ISSUE THREAD

**Issue by ticklemyIP** [wg-easy/wg-easy#1217]
**Describe the bug**

**To Reproduce**
1. Write stack
2. Try deploying
3. Get error

**Expected behavior**

There is no error.

**Screenshots**

**Server (please complete the following information):**
 - OS: AlmaLinux 9.4 (Seafoam Ocelot) 

**Additional context**

What could be the issue?

Stack:
```
volumes:
  etc_wireguard:
  
services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=HOST
      # Optional:
      # - PASSWORD=foobar123 (deprecated, see readme)
      - PASSWORD_HASH=HASH  #(needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      #- PORT=51821
      #- WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman 
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```

Deployment error
```
failed to deploy a stack: Network wireguard_default Creating Network wireguard_default Error failed to create network wireguard_default: Error response from daemon: Failed to program NAT chain: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Could not process rule: No such file or directory internal:0:0-0: Error: Could not process rule: No such file or directory internal:0:0-0: Error: Could not process rule: No such file or directory internal:0:0-0: Error: Could not process rule: No such file or directory internal:0:0-0: Error: Could not process rule: No such file or directory internal:0:0-0: Error: No such file or directory; did you mean chain ‘filter_FWD_public_allow’ in table inet ‘firewalld’? internal:0:0-0: Error: Could not process rule: No such file or directory internal:0:0-0: Error: Could not process rule: No such file or directory JSON blob: {"nftables": [{"metainfo": {"json_schema_version": 1}}, {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_INPUT_ZONES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "br-70ed4b7f29f3"}}, {"goto": {"target": "filter_IN_docker"}}]}}}, {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "nat_POSTROUTING_ZONES", "expr": [{"match": {"left": {"meta": {"key": "oifname"}}, "op": "==", "right": "br-70ed4b7f29f3"}}, {"goto": {"target": "nat_POST_docker"}}]}}}, {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_FORWARD_ZONES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "br-70ed4b7f29f3"}}, {"goto": {"target": "filter_FWD_docker"}}]}}}, {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "nat_PREROUTING_ZONES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "br-70ed4b7f29f3"}}, {"goto": {"target": "nat_PRE_docker"}}]}}}, {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "mangle_PREROUTING_ZONES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "br-70ed4b7f29f3"}}, {"goto": {"target": "mangle_PRE_docker"}}]}}}, {"add": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_FWD_docker_allow", "expr": [{"match": {"left": {"meta": {"key": "oifname"}}, "op": "==", "right": "br-70ed4b7f29f3"}}, {"accept": null}]}}}, {"delete": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_FORWARD_POLICIES_pre", "handle": 494}}}, {"delete": {"rule": {"family": "inet", "table": "firewalld", "chain": "nat_POSTROUTING_POLICIES_pre", "handle": 496}}}]}
```
