### ISSUE TITLE
Version 13 doesn't work any more on Kubernetes

### ISSUE THREAD

**Issue by herberthobregon** [wg-easy/wg-easy#1231]
**Describe the bug**
Everything was working fine until version 12. I could create a Pod in my k8s cluster and connect. When updating to any version 7, 8,9, 10, 11, 12 It works fine but when using version 13. My client no longer connects.

I checked what changes they made and the only strange thing I see is this. That the port is no longer exposed. I think that could be the cause
https://github.com/wg-easy/wg-easy/commit/519f4efa20474e93ff6467662f0c2fdc57550f50#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R40-R42

**To Reproduce**
Create a pod in kubernetes (ubuntu node) with this config and open the port `31820` in firewall 
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
  labels:
    name: wireguard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wireguard
  namespace: wireguard
spec:
  serviceName: "wireguard"
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wg-easy
          # image: ghcr.io/wg-easy/wg-easy:12 # Works!!
          image: ghcr.io/wg-easy/wg-easy:13 # Doesn't work
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          env:
            - name: WG_HOST
              value: <YOUR PUBLIC IP OF NODE>
            - name: PASSWORD
              value: secure_password
            - name: WG_DEFAULT_DNS
              value: "8.8.8.8"
            - name: WG_ALLOWED_IPS
              value: "0.0.0.0/0"
            - name: WG_PORT
              value: "31820"
          volumeMounts:
            - name: wg-config-pvc
              subPath: "wg-easy"
              mountPath: /etc/wireguard
            - name: host-volumes
              mountPath: /lib/modules
          ports:
            - containerPort: 51820
              protocol: UDP
            - containerPort: 51821
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
      volumes:
        - name: host-volumes
          hostPath:
            path: /lib/modules
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: wg-config-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: wireguard
  name: wireguard-service
  namespace: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - port: 51820
      protocol: UDP
      targetPort: 51820
      nodePort: 31820
    - port: 51820
      protocol: TCP
      targetPort: 51820
      nodePort: 31820

```

**Expected behavior**
The WG can connect

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1
