### ISSUE TITLE
restoreConfig is not defined

### ISSUE THREAD

**Issue by offizium-berndstorath** [wg-easy/wg-easy#1253]
I get the same error as @ThunderThorr in my console along with the hanging loading screen when using Brave Browser `1.68.134 Chromium: 127.0.6533.88 (Official Build) (arm64)` (Safari is fine though):
```
ReferenceError: restoreConfig is not defined
    at Er.eval (eval at mc (vue.min.js:6:105188), <anonymous>:3:6811)
    at t._render (vue.min.js:6:45862)
    at Er.r (vue.min.js:6:79765)
    at t.get (vue.min.js:6:28262)
    at t.run (vue.min.js:6:28995)
    at cn (vue.min.js:6:19867)
    at Array.<anonymous> (vue.min.js:6:23307)
    at Sn (vue.min.js:6:22707)
  ```
  
 I am getting this error on both the nightly (nightly@sha256:b6a799f9d96d735e07d300863bd43d32d7e9f4514bb8e7ed88157c22891f4f3b) and the latest (latest@sha256:4c2c591498aa910ce86a90fa00c4714ffd78dd7556b1f488f226471b97346bc6).
  
My docker-compose.yml:
```yaml
services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=<MY_HOST>
      - WG_DEVICE=<MY_DEVICE>
      - WEBUI_HOST=0.0.0.0
      - PASSWORD=<PASSWORD> # OR PASSWORD_HASH for nightly
    image: ghcr.io/wg-easy/wg-easy:<IMAGE_TAG>
    container_name: wg-easy
    volumes:
      - /etc/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️   Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

_Originally posted by @meddion in https://github.com/wg-easy/wg-easy/issues/1197#issuecomment-2275053219_
