### ISSUE TITLE
[Bug]: VPN Clients Unable to Access Internet When Using wg-easy on Debian 12

### ISSUE THREAD

**Issue by MohamedFBoussaid** [wg-easy/wg-easy#1328]
### **Description**
I am experiencing an issue with my wg-easy setup on a Debian 12-based mini PC where VPN clients are unable to access the internet. The issue persists regardless of whether I use Pi-hole or other DNS servers (Google, Cloudflare). Below are the details of both the working setup on my Raspberry Pi 5 and the problematic setup on the mini PC.

I am using the same docker compose (except the `WG_DEFAULT_DNS` ): 

```
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - WG_HOST=xx.xxx.xx.x
      - WG_DEFAULT_DNS=10.0.0.14 # The mini pc is set to 10.0.0.15
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2 
      - WG_PERSISTENT_KEEPALIVE=25
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
volumes:
  etc_wireguard:
```

### **Setup Details**

- **Setup 1: Pi5 (Working Setup)**
**wg-easy:** Running inside a Docker container on a Raspberry Pi 5.
**Pi-hole:** Running inside a Docker container on the same Raspberry Pi 5, configured to use Unbound as a DNS resolver.
**VPN Client Behavior:** VPN clients connected via WireGuard can access the internet successfully and resolve DNS queries using Pi-hole.

- **Setup 2: Mini PC (Problematic Setup)**
**OS:** Debian 12
**wg-easy:** Running inside a Docker container on a Debian 12-based mini PC.
**Pi-hole:** Running inside a Docker container on the same mini PC, configured to use Unbound as a DNS resolver.
**VPN Client Behavior:** VPN clients connected via WireGuard cannot access the internet. This issue persists regardless of whether I use Pi-hole, Google DNS, or Cloudflare DNS.

### **Tests and Observations**

**1. DNS Resolution Inside wg-easy Container (Mini PC Setup):**
- **Ping to Pi-hole (10.0.0.15):** Successful
- **DNS Resolution via Pi-hole:** Successful when tested inside the wg-easy container:
`docker exec -it wg-easy nslookup google.com 10.0.0.15`
**This indicates that DNS resolution is working within the container.**

 **2.Client-Side Behavior (Mini PC Setup):**
VPN clients are unable to access the internet and cannot resolve DNS queries regardless of whether I use Pi-hole (10.0.0.15), Google DNS (8.8.8.8), or Cloudflare DNS (1.1.1.1).

**3. Cross-Testing Between Devices:**
- **Mini PC Using Pi5 for DNS** (`WG_DEFAULT_DNS` pointing to Pi5’s Pi-hole): **Result:** VPN clients **cannot** access the internet.
- **Pi5 Using Mini PC for DNS** (`WG_DEFAULT_DNS` pointing to Mini PC’s Pi-hole): **Result:** VPN clients **can** access the internet successfully.

**4. Direct DNS Testing on Client Devices:**
- **Manual DNS Configuration on Client (Without WireGuard)**: When I manually set the DNS on a client device to point to the Mini PC’s Pi-hole IP address (10.0.0.15), the client can access the internet successfully.

**5. Comparison with Pi5 Setup:**
- The exact same setup on the Pi5 works flawlessly, with clients able to access the internet and resolve DNS using Pi-hole with Unbound.

**6. iptables and Docker NAT Rules:**
Checked the iptables and NAT rules to ensure there’s no interference, but the issue persists.

### **Additional Context**
**Migration:** The mini PC is a new setup where I am migrating my services from the Pi5 to the mini PC. The Pi5 setup works perfectly, but I am encountering issues with the new mini PC setup.

### **Expected Behavior**
VPN clients connected to the wg-easy instance on the mini PC should be able to:
Resolve DNS queries via the specified DNS server (whether Pi-hole, Google, or Cloudflare).
Access the internet fully.

### **Actual Behavior**
VPN clients connect to the wg-easy instance on the mini PC but cannot access the internet.
DNS resolution works within the Docker container but not on the VPN clients.

I am looking for assistance in understanding why VPN clients cannot access the internet when connected to the wg-easy instance on my mini PC, despite the same configuration working perfectly on my Pi5. Any insights or guidance on how to resolve this issue would be greatly appreciated.

Thank you!

### Expected behavior

Work just fine!

**Comment by MohamedFBoussaid** [comment]
By the way, I have also tried to deploy both services with the same docker compose as recommended in the documentation 

```
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - WG_HOST=xx.xxx.xx.xxx
      - WG_DEFAULT_DNS=10.8.1.3
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2
      - WG_PERSISTENT_KEEPALIVE=25
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    #network_mode: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      TZ: 'Europe/Zurich'
      WEBPASSWORD: nAdA20$$$
    volumes:
      - etc_pihole:/etc/pihole
      - /etc/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3

volumes:
  etc_pihole:
  etc_wireguard:
  
        
networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
```
