### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by andrey0001** [wg-easy/wg-easy#138]
I am missing an option with IPV6 addresses.
Please add this feature.

**Comment by WeeJeWel** [comment]
Create a PR :)

**Comment by joelheaps** [comment]
Just dropping a comment to express support for this.  I appreciate all the work you've put into the project, and I understand why this might not be high on the list.  I also think that a lack of IPv6 support in 2022 puts a fairly significant limit on the project's functionality though.  If I can learn the ropes of the code here I may work on a PR.

**Comment by hzqim** [comment]
I build a docker image with  ipv6 support bases https://github.com/crazyracer98/wg-easy.

https://hub.docker.com/r/hzqim/wg-easy

```
docker run \
  --name=wireguard-ipv6 \
  --net=Your bridge with ipv6 address \
  -e WG_HOST=Your server ip or DDNS domain name \
  -e PASSWORD=Your password \
  -v /opt/docker/wireguard-ipv6:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821 \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.ip_forward=1" \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv6.conf.all.disable_ipv6=0" \
  --sysctl="net.ipv6.conf.all.forwarding=1" \
  --sysctl="net.ipv6.conf.default.forwarding=1" \
  --restart unless-stopped \
  --log-opt max-size=1m \
  hzqim/wg-easy

```
It works.

**Comment by lucyrose39** [comment]
Also adding a comment asking for IPv6 support. non dual stack systems aren't useful on my network.

**Comment by kaaax0815** [comment]
This issue shouldnt be stale

**Comment by GrauBlitz** [comment]
Maybe I am missing something, but why is the container despite this listening on IPv6?

```
# lsof -i:51820
COMMAND       PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
docker-pr X root    4u  IPv4 X 0t0  UDP *:51820
docker-pr X root    4u  IPv6 X 0t0  UDP *:51820
# lsof -i:51821
COMMAND       PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
docker-pr X root    4u  IPv4 X 0t0  TCP *:51821 (LISTEN)
docker-pr X root    4u  IPv6 X 0t0  TCP *:51821 (LISTEN)
```

**Comment by alvolalex** [comment]
As a temporary solution I can advise an ipv6-to-ipv4 proxy.
E.g. "tayga" or "socat".
An example below was generated by ChatGPT and wasn't tested yet by me and it comes with no warranty.
```
sudo apt-get update
sudo apt-get install tayga
```
```
echo 'ipv4-addr = 192.168.255.1
dynamic-pool = 192.168.255.0/24
prefix = fd00:1234::/96
allow-own-ranges = yes' | sudo tee /etc/tayga.conf
```
```
sudo ip tuntap add mode tun dev tun0
sudo ip addr add 192.168.255.1/24 dev tun0
sudo ip link set dev tun0 up
sudo ip route add 192.168.255.0/24 dev tun0
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE  
sudo tayga -d
```

**Comment by Jie2GG** [comment]
I implemented dual-stack support for wg-easy using the docker-compose.   yml configuration file.

Steps:
1.   Enable docker IPv6 NAT.
2.   Test this machine is support IPv6.
3.   Configuration nginx config & cert.
4.   Use my `docker-compose.yml` file start wg-easy container.

docker-compose.yml file:
```yaml
version: '3.8'  
services:  
  wg-easy:  
    image: ghcr.io/wg-easy/wg-easy  
    container_name: wg-easy  
    network_mode: bridge
    restart: always
    privileged: true
    environment:  
      - WG_HOST=********  
      - PASSWORD=********
      - WG_DEFAULT_DNS=********
      - WG_DEFAULT_ADDRESS=********
    volumes:  
      -  /data/wireguard:/etc/wireguard  
    ports:  
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    sysctls:  
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
  wg-nginx:
    image: nginx
    container_name: wg-nginx
    privileged: true
    restart: always
    hostname: nginx
    network_mode: bridge
    ports:
      - 51821:51821/tcp
    volumes:
      - /data/nginx/conf/:/etc/nginx/
      - /data/nginx/cert/:/etc/cert/
      - /data/nginx/www/:/usr/share/nginx/html/
      - /data/nginx/logs/:/var/log/nginx/
    depends_on:
      - wg-easy
    links:
      - wg-easy:wg-easy
```
nginx config:
```conf
worker_processes  auto;
error_log  /dev/null;

events {
    worker_connections  1024;
}

http {
    server {
        listen 51821 ssl;
        listen [::]:51821 ssl;

        server_name YOU_HOST;

        ssl_certificate /etc/cert/********.pem;
        ssl_certificate_key /etc/cert/********.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        # Proxy wg-easy web page
        location / {
            proxy_pass http://wg-easy:51821;
        }        
    }
}
```
