### ISSUE TITLE
[Bug]: client connects successfully but no traffic is going through

### ISSUE THREAD

**Issue by shadowlmd** [wg-easy/wg-easy#1386]
### Describe the bug

Clients successfully connect but there is no traffic going through. I cannot even ping the gateway (10.8.0.1) or DNS (1.1.1.1). There are no errors in logs or anywhere else. Everything is running under a clean installation of Ubuntu 24.04, all packages are updated to the latest versions. Any help is welcome. Here's my configuration:

```
# docker compose config
name: wg-easy
services:
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wg-easy
    environment:
      LANG: en
      PASSWORD_HASH: $$##REDACTED##
      PORT: "51821"
      WG_DEFAULT_ADDRESS: 10.8.0.x
      WG_DEFAULT_DNS: 1.1.1.1, 1.0.0.1
      WG_HOST: redacted.example.com
      WG_PORT: "51820"
    image: ghcr.io/wg-easy/wg-easy
    networks:
      default: null
    ports:
      - mode: ingress
        target: 51820
        published: "51820"
        protocol: udp
      - mode: ingress
        target: 51821
        published: "51821"
        protocol: tcp
    restart: unless-stopped
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv4.ip_forward: "1"
    volumes:
      - type: volume
        source: etc_wireguard
        target: /etc/wireguard
        volume: {}
networks:
  default:
    name: wg-easy_default
volumes:
  etc_wireguard:
    name: wg-easy_etc_wireguard
```

Screenshots:

![wg-gui](https://github.com/user-attachments/assets/aea14282-6856-473c-8ba5-c06d9fe4aa34)
![Screenshot_20240910_191100_WireGuard](https://github.com/user-attachments/assets/a5ac92bd-8ff5-4eb0-a4a7-61b820c273a0)
![Screenshot_20240910_191522_Termius](https://github.com/user-attachments/assets/175c2534-f2de-4a89-819a-7860ef9b4aae)

### Expected behavior

It should just work. Or at least print some errors.

### Relevant log output

```shell
# docker compose logs wg-easy
wg-easy  | 2024-09-10T11:24:39.017Z Server Listening on http://0.0.0.0:51821
wg-easy  | 2024-09-10T11:24:39.032Z WireGuard Loading configuration...
wg-easy  | 2024-09-10T11:24:39.043Z WireGuard Configuration loaded.
wg-easy  | 2024-09-10T11:24:39.044Z WireGuard Config saving...
wg-easy  | 2024-09-10T11:24:39.049Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | 2024-09-10T11:24:39.259Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-09-10T11:24:39.321Z WireGuard Config synced.
wg-easy  | 2024-09-10T11:27:30.117Z Server New Session: lUCMqn0Yw8Uqpd3r6GwuBBFjkPSbPCE8
```

**Comment by kaaax0815** [comment]
Try with
```yaml
services:
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wg-easy
    environment:
      LANG: en
      PASSWORD_HASH: $$##REDACTED##
      PORT: 51821
      WG_DEFAULT_ADDRESS: 10.8.0.x
      WG_DEFAULT_DNS: 1.1.1.1, 1.0.0.1
      WG_HOST: redacted.example.com
      WG_PORT: 51820
    image: ghcr.io/wg-easy/wg-easy
    networks:
      - default
    ports:
       - "51820:51820/udp"
       - "51821:51821/tcp"
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - etc_wireguard:/etc/wireguard

networks:
  default:
    name: wg-easy_default

volumes:
  etc_wireguard:
    name: wg-easy_etc_wireguard
```

**Comment by shadowlmd** [comment]
@kaaax0815, that's almost exactly what I am running. If you run docker compose config with your example, you'll have output identical to mine. Anyway, like I said, it's a clean installation of Ubuntu 24.04, so it can't be a firewall issue. I even tried to clean iptables with `iptables -F && iptables - nat -F` and restarting docker.service so that it created its default rules.

But I believe it's something with Ubuntu 24.04 because on my other server after I upgraded from 22.04 to 24.04, my previously working OpenVPN server stopped working with similar symptoms - clients connect but no traffic going through. I'm still investigating.

**Comment by Mikeileech** [comment]
Same issue.
Tested with ubuntu 20.04, 22.04, 24.04
Also tested with latest and 12-th version of utility.
Have no idea what am i doing wrong. 
Already reinstalled system on my server three times in a row.
Need help.

**Comment by rik43** [comment]
Same issue. Debian 12

**Comment by laperuz92** [comment]
Just FYI, worked like a charm with 22.04 and working now with 24.04.
If you need some output from working setup, will be glad to help.

**Comment by kaaax0815** [comment]
@laperuz92 Do you have a different docker-compose file or did you set something up to make it work?

**Comment by shadowlmd** [comment]
Guys, it's working flawlessly for me on 20.04 and 22.04, I've installed it on 4 different servers yesterday. And since it's working on 24.04 for some people, I suggest to close this issue. Maybe my problem was not with Ubuntu after all.

**Comment by laperuz92** [comment]
> @laperuz92 Do you have a different docker-compose file or did you set something up to make it work?

Here is my docker-compose:

```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=<HOST>

      # Optional:
      - PASSWORD_HASH=<HASH>
      - PORT=8588
      - WG_PORT=62560
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=8.8.8.8, 1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=2 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - WG_ENABLE_ONE_TIME_LINKS=true
      # - UI_ENABLE_SORT_CLIENTS=true
      # - WG_ENABLE_EXPIRES_TIME=true
      # - ENABLE_PROMETHEUS_METRICS=false
      # - PROMETHEUS_METRICS_PASSWORD=$$2a$$12$$vkvKpeEAHD78gasyawIod.1leBMKg8sBwKW.pQyNsq78bXV3INf2G # (needs double $>
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "8588:8588/tcp"
      - "62560:62560/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
```
