### ISSUE TITLE
[Bug]: Duplicate Packets

### ISSUE THREAD

**Issue by memesalot** [wg-easy/wg-easy#1398]
### Describe the bug

It appears like traffic going through the container is duplicated. Possibly due to misconfigured iptables rules? 

https://github.com/wg-easy/wg-easy/issues/795 <--- may be related to this

I've tried re-creating the container to verify it wasn't a configuration issue, as well as trying it on a completely different network - same issue persists. 

Example: 

![image](https://github.com/user-attachments/assets/a9152bcb-4b11-4b73-87b7-d2f9edfd9c57)

![image](https://github.com/user-attachments/assets/a1a999c4-2b7f-4c48-8d51-f701e554689d)

It's worth noting that using the same wg0.conf with wireguard directly (sans docker) does not reproduce this same issue. It also happens on every client OS, it's not OS dependent. 

## Config File

```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=redacted

      # Optional:
      - PASSWORD_HASH=redacted
      - PORT=51821
      - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=10.0.1.4, 10.0.1.250
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=10.0.0.0/24, 10.0.1.0/24, 10.0.2.0/24, 10.0.3.0/24, 10.0.4.0/24
      - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy-ls
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman 
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

### Expected behavior

Packets aren't being duplicated
