### ISSUE TITLE
[Bug]: Changing WG_DEFAULT_ADDRESS leads to invalid server config

### ISSUE THREAD

**Issue by rolandu** [wg-easy/wg-easy#1407]
## Description of issue

This bug relates to my earlier discussion: https://github.com/wg-easy/wg-easy/discussions/1379

It appears that variable "server: address" in `wg0.json` gets written the first time wg-easy is launched.

For example, if I use the following simple compose file:

```
services:
  wg-easy:
    environment:
      # the server's hostname (clients will connect to):
      - WG_HOST=foo.com

      # the Web UI Password:
      - PASSWORD_HASH=100

      # the addresses we are giving out to clients
      - WG_DEFAULT_ADDRESS=10.35.6.x

    image: ghcr.io/wg-easy/wg-easy
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
       - "51829:51820/udp"
        #- "51821:51821/tcp"  # web interface
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      knightnet:
        ipv4_address: 10.35.7.3

networks:
  knightnet:
    ipam:
      config:
        - subnet: "10.35.7.0/24"
```

and then change to `WG_DEFAULT_ADDRESS=10.35.66.x` the `wg0.json` does not change. This leads to errors for *some* clients apparently.

## Workaround

change the `wg0.json` manually - easy, you just have to know it...

### Update README

I would add a section below "Options" that reads:

> The following options are applied the first time the container is built:
> - WG_DEFAULT_ADDRESS: if you change it, you have to update wg0.json in your config volume/directory manually or rebuild the config volume/directory
>
> The following options are propagated to clients, if you change any of them you have to supply clients with a new config:
> - WG_HOST
> - WG_PORT
> - WG_DEFAULT_DNS
> - WG_DEFAULT_ADDRESS
> - WG_ALLOWED_IPS

### Update wg0.json on every container build

Might be easy to implement, I don't know. I understand my change in the config is an edge case that doesn't happen frequently.

### Expected behavior

Changes in the `docker-compose.yml` are always applied after every rebuild of the container...
