### ISSUE TITLE
[BUG] Example docker-compose has comments not commented out for PASSWORD_HASH

### ISSUE THREAD

**Issue by F1zzyD** [wg-easy/wg-easy#1433]
### Describe the bug

Trying to log into wg-easy for the first time and I get the authorized screen after following the instructions exactly. Crazy.

- I am using `docker-compose`
- I generated the hash using `docker run -it ghcr.io/wg-easy/wg-easy wgpw YOUR_PASSWORD`
- I pasted the hashed password in the compose file under `PASSWORD_HASH` with double $$ when present
- Started it up and put in "YOUR_PASSWORD" in the window
- Unauthorized

I tried with a different password:
- Rehashed using `docker run -it ghcr.io/wg-easy/wg-easy wgpw`
- Pasted the hashed password in with $$
- Started it up and put the new password in
- Unauthorized

I tried with the hashed password knowing that's not what you're supposed to do, but what the hey
- Unauthorized

I tried with the hashed password with double $$, again, just for the heck of it
- Unauthorized

I removed `PASSWORD_HASH` from the compose file and ran it up.... **no issues. I'm in**

Again, I read the instructions and copied it exactly as they say and it's bouncing back unauthorized. I also clear my browser's cache, history, everything...

**Unauthorized**

### Expected behavior

Password should log me in.

### Relevant log output

```shell
"Unauthorized"
```

**Comment by henrydavidge** [comment]
I'm seeing the same behavior

**Comment by moppman** [comment]
Just to be sure: in your docker-compose file, make sure to **not** wrap the password hash in quotes.

**Comment by henrydavidge** [comment]
I followed directions in the readme, but I tried again and can no longer replicate... so maybe I just fatfingered something multiple times.

Apologies for the disturbance on my end, and thanks for a great project.

**Comment by kaaax0815** [comment]
> I removed PASSWORD_HASH from the compose file and ran it up.... no issues. I'm in

Repull the docker image and try again. as you shouldn't be able to log in with no Password supplied

**Comment by lucasggit** [comment]
Solution for me :
when you use docker-compose format, you have to double ALL the "$" in the hash password :
docker run --rm ghcr.io/wg-easy/wg-easy wgpw MacronExplosion
PASSWORD_HASH='$2a$12$ktKot/61huQHPsBxMOc3S.pOptnWmqEynbM6Beps7998ZNPVgUNrS'

in my docker-compose :

PASSWORD_HASH=$$2a$$12$$ktKot/61huQHPsBxMOc3S.pOptnWmqEynbM6Beps7998ZNPVgUNrS

**Comment by MrAuger** [comment]
> Just to be sure: in your docker-compose file, make sure to **not** wrap the password hash in quotes.

Where I can get that File?

**Comment by kaaax0815** [comment]
> Where I can get that File?

If you're using docker compose you already have the file. Id you are using docker run you don't need it

**Comment by agospher4eg** [comment]
i spent 3 hours with auth problem. 
remove spaces after hashed password )

**Comment by CesarDavidSS** [comment]
What worked in my case, I am using ssh from the terminal, enter as SU then enter the following code: 

`docker run -it ghcr.io/wg-easy/wg-easy wgpw <my_password>`

what generated my hash key
`PASSWORD_HASH='$2a$12$dhAbb..............c'`

put in docker-compose the following: 
`- PASSWORD_HASH=$$2a$$12$$dhAbb..............c
`
When entering wireguard I enter **<my_password>**

**Comment by MrAuger** [comment]
OK, I have solved the problem by installing Bubuntu 24.04.
Thank you for all of you.

**Comment by TPDs** [comment]
I had this issue for a while too, "clear cache and site date" in Chrome (click the small lock icon left of your url), did the job.
Using docker run, with a parameter like this PASSWORD_HASH='$2a$12$grgej/q3EkWDPPVEO.sHqen76C8XXXXXXXXX'

**Comment by AlexKazm** [comment]
I've spent a lot of time too. I installed portainer and replaced the hash password from portainer without any $$ and unnecessary manipulations.

**Comment by jursed** [comment]
See https://github.com/wg-easy/wg-easy/issues/1507 for a better solution to these password-hash issues.

(I think this thread proves that the whole `$$`-escaping is a pretty inelegant and error-prone idea.)

**Comment by F1zzyD** [comment]
> See https://github.com/wg-easy/wg-easy/issues/1507 ("option 2") for a better solution to these password-hash issues.
> 
> (I think this thread proves that the whole `$$`-escaping is a pretty inelegant and error-prone idea.)

Agreed. I made sure I had $$ where appropriate and even tried different variations of it. Still no dice. There needs to be a better solution.

**Comment by kaaax0815** [comment]
Im very sorry for all this issues with escaping the password hash.

The thought of using password hashes instead of clear text passwords do make sense, but we never knew it would make things so complicated.

There is already a solution with #1333. Stay tuned

**Comment by Nickxsch** [comment]
Don't know if this is useful anymore: I had this issue when placing the hashed password in my .env-file. Placing it directly in my docker-compose.yml solved the issue. Somewhere in getting the variable from the .env it went wrong. And I've checked everything, inclucing trailing spaces and stuff.
Well, it works now and I look forward to 15.0.0!

**Comment by F1zzyD** [comment]
> Don't know if this is useful anymore: I had this issue when placing the hashed password in my .env-file. Placing it directly in my docker-compose.yml solved the issue. Somewhere in getting the variable from the .env it went wrong. And I've checked everything, inclucing trailing spaces and stuff.
> Well, it works now and I look forward to 15.0.0!

That's interesting that you go it to work. I tried the .env file and docker-compose.yml and got the same result, even with doubled $$. Something is inconsistent with the $$ or password handling...

**Comment by kaaax0815** [comment]
@F1zzyD do you still have the issue?

**Comment by SctrThCt** [comment]
Hello, have the same issue 

my docker-compose.yml

`volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=contoso.com
      # Optional:
      - PASSWORD_HASH=$$2a$12$biu.QjMlPTjtOXGnbpYLMutuKybh97//fNvSQZoFxBFx8Vz1pIok.
      - PORT=51821
      - WG_PORT=51820
      - WG_CONFIG_PORT=92820
      #- WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
`

**Comment by F1zzyD** [comment]
> [@F1zzyD](https://github.com/F1zzyD) do you still have the issue? If yes please post your docker compose file

I just gave it another go with the included docker-compose.yml file in the project files. The hashed password should be "foobar123", right? Just tried it in a fresh installation.... 

**Unauthorized**

> You have to double **every** `$`
> 
> ```
> Wrong
> $$2a$12$biu.QjMlPTjtOXGnbpYLMutuKybh97//fNvSQZoFxBFx8Vz1pIok.
> Right
> $$2a$$12$$biu.QjMlPTjtOXGnbpYLMutuKybh97//fNvSQZoFxBFx8Vz1pIok.
> ```

This is done in the example compose.yml file and it doesn't work. Still Unauthorized.....

**Comment by kaaax0815** [comment]
This hash
```
$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG
```
is included in the docker-compose.yml in the repo. And it does indeed work

**Comment by MrAuger** [comment]
Thank you for all of you! I have dicided the problem by reinstallation my OS and all of the programs.

**Comment by F1zzyD** [comment]
> This hash
> ```
> $$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG
> ```
> is included in the docker-compose.yml in the repo. And it does indeed work

Incorrect. Tried it again, routing the environment to a different location on the OS with full permissions and using the hash provided the stated password "foobar123" at the address 192.168.x.x:51821.

The result is still the same: **Unauthorized**

The only way into wg-easy at the default port is by commenting the password out. Otherwise, using the default hash or a different generated one with double $$ everywhere $ is present locks me out of wg-easy. I've cleared my cookies, given permissions, allowed ports.... you name it, it's probably been done.

"**Unauthorized**"

**Comment by kaaax0815** [comment]
If you are able to use the `PASSWORD` env var you are using a old version (older version of 14)

and what do you mean that you are routing the environment?

if you deploy the docker-compose.yml file as is and open the port `51821` it works. Guaranteed

**Comment by F1zzyD** [comment]
> If you are able to use the `PASSWORD` env var you are using a old version (older version of 14)

I am using the docker-compose.yml posted in the project code that uses 'PASSWORD_HASH'

> and what do you mean that you are routing the environment?

Bad wording, I meant changed the volume location to a different directory on my OS.

> if you deploy the docker-compose.yml file as is and open the port `51821` it works. Guaranteed

I only uncommented the 'PORT' and 'PASSWORD_HASH' and I am still getting "**Unauthorized**". It does not work.

**Comment by kaaax0815** [comment]
Yes but you have to update the image itself. Use something like
```shell
docker compose down
docker compose pull
docker compose up -d
```

**Comment by F1zzyD** [comment]
> Yes but you have to update the image itself. Use something like
> ```shell
> docker compose down
> docker compose pull
> docker compose up -d
> ```

I've pruned all images, networks, and files related to wg-easy to be sure I have the latest version of everything. I even pruned again this morning just to be sure.

**Comment by F1zzyD** [comment]
Here's my compose:
```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi, ja, si)
      - LANG=en
      # âš ï¸ Required:
      # Change this to your host's public address
      - WG_HOST=192.168.x.x

      # Optional:
      - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      - PORT=51821
      - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - WG_ENABLE_ONE_TIME_LINKS=true
      # - UI_ENABLE_SORT_CLIENTS=true
      # - WG_ENABLE_EXPIRES_TIME=true
      # - ENABLE_PROMETHEUS_METRICS=false
      # - PROMETHEUS_METRICS_PASSWORD=$$2a$$12$$vkvKpeEAHD78gasyawIod.1leBMKg8sBwKW.pQyNsq78bXV3INf2G # (needs double $$, hash of 'prometheus_password'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /home/user/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # âš ï¸ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

Here's the only logs I get, even after putting in the password:
```
Attaching to wg-easy
wg-easy  | 2024-11-21T13:18:49.229Z Server Listening on http://0.0.0.0:51821
wg-easy  | 2024-11-21T13:18:49.232Z WireGuard Loading configuration...
wg-easy  | 2024-11-21T13:18:49.234Z WireGuard Configuration loaded.
wg-easy  | 2024-11-21T13:18:49.234Z WireGuard Config saving...
wg-easy  | 2024-11-21T13:18:49.235Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-11-21T13:18:49.320Z WireGuard Config syncing...
wg-easy  | 2024-11-21T13:18:49.342Z WireGuard Config synced.
```
Putting in "foobar123" does not add anything to the log output. I just get "Unauthorized" in the webui. Again, commenting out `PASSWORD_HASH` allows me in the webui with no issues.
