### ISSUE TITLE
[Bug]: Custom ports not working correctly

### ISSUE THREAD

**Issue by Rekkertt** [wg-easy/wg-easy#1439]
I'm currently using version 12 without issues, but I'm looking to upgrade to version 14. 
I've noticed a problem with custom ports during testing.

**Broken**

```yaml
wg-easy:
  container_name: wg-easy
  image: ghcr.io/wg-easy/wg-easy:latest
  restart: unless-stopped
  environment:
    - WG_HOST=<Myip>
    - WG_PORT=51833
    - WG_MTU=1280
    - WG_DEFAULT_DNS=94.140.14.14,1.1.1.1
    - PASSWORD_HASH=<myPWHash>
    - LANG=nl
    - UI_TRAFFIC_STATS=true
    - UI_CHART_TYPE=2
  ports:
    - "51833:51820/udp"
    - "9005:51821/tcp"
  volumes:
    - /home/wireguard:/etc/wireguard
  cap_add:
    - NET_ADMIN
    - SYS_MODULE
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
```

**Working**

```yaml
wg-easy:
  container_name: wg-easy
  image: ghcr.io/wg-easy/wg-easy:latest
  restart: unless-stopped
  environment:
    - WG_HOST=<Myip>
    - WG_MTU=1280
    - WG_DEFAULT_DNS=94.140.14.14,1.1.1.1
    - PASSWORD_HASH=<myPWHash>
    - LANG=nl
    - UI_TRAFFIC_STATS=true
    - UI_CHART_TYPE=2
  ports:
    - "51833:51820/udp"
    - "9005:51821/tcp"
  volumes:
    - /home/wireguard:/etc/wireguard
  cap_add:
    - NET_ADMIN
    - SYS_MODULE
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
```

### Expected behavior

The only difference is the presence of `WG_PORT` in the environment variables. 
When it's omitted, loading the profile on the client uses the incorrect port. 
You can manually change it and it will **WORK**, but this isn't expected behavior. 

The same issue occurs with the `PORT` setting. 
If it's left out and only set under `ports`, it still works.

In shot, I expect this to work:

 environment:
    - PORT=9005
    - WG_PORT=51833

  ports:
    - "51833:51820/udp"
    - "9005:51821/tcp"

In version 12, this configuration worked correctly.

**Comment by shalafi99** [comment]
I understand the config under "environment" represents the ports to be used by wireguard itself inside the container, while the config under "ports" is the host:container mapping. Slightly different perspectives, port-wise.

So I believe your compose should be like this

environment:
- PORT=51821
- WG_PORT=51820

ports:
- "51833:51820/udp"
- "9005:51821/tcp"

But I must say I only started using this software on v14 - I've never had the chance to see it working differently with v12 in that regard, like you did.

**Comment by shalafi99** [comment]
Let's scratch all my (not relevant to the exact issue described) previous comments... Uncluttered.

I managed to reproduce the issue you encountered.

If a custom port mapping is being used, not including the environment variable for the container compose caused the default WG port to be included during client config generation.

Since I had those ENVs defined from the very beginning of using wg-easy together with custom ports, never noticed the issue like you did.

**Comment by shalafi99** [comment]
(_Two strikes, one chance left, apologies for the clutter generated by my previous responses_)

I have the :latest image (v14), ran some tests while changing my setup in a couple different ways, noticed the WG_PORT environment variable defines both the listening port inside the container and the port to be included into the client config.
So using a custom port mapping for the container can result in a connectivity misconfiguration. It kind of expects you to stick to the same port end-to-end.

I did not test the PORT env because that one is just a http listening port (i.e. not included in the client config). But looking at your "expected to work" setup, if inside the container you're using default TCP 51821 and you want to expose TCP 9005 to the network, you should not declare the "PORT" env.

I am sorry I am unable to understand how it worked correctly for you in v12, I have started using wg-easy while it was already at v14. I suppose WG_PORT might be a "heritage" from the fact wg-easy (at least for now) can be installed/used without Docker?

**Comment by Rekkertt** [comment]
Thanks for your reply!
The documentation says:

_Env            |  Default  | Example | Description 
WG_PORT |   51820   |   12345   | The public UDP port of your VPN server. WireGuard will listen on that (othwise default) inside the 
                                                    Docker container._

This indicates to me that it should work, but does not anymore,
With docker you can just change the image tag:

```yaml
wg-easy:
  container_name: wg-easy
  image: ghcr.io/wg-easy/wg-easy:12
  restart: unless-stopped
  environment:
    - WG_HOST=<MyIP>
    - WG_PORT=51833
    - WG_MTU=1280
    - WG_DEFAULT_DNS=94.140.14.14, 1.1.1.1
    - PASSWORD=<MYPW>
    - LANG=nl
    - UI_TRAFFIC_STATS=true
    - UI_CHART_TYPE=2
  ports:
    - "51833:51820/udp"
    - "9005:.51821/tcp"
  volumes:
    - /home/wiregaurd:/etc/wireguard
  cap_add:
    - NET_ADMIN
    - SYS_MODULE
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
```

If you want you can test it and you will see that it works as I describe.
