### ISSUE TITLE
[Bug]: Unable to upgrade from weejewel/wg-easy:7

### ISSUE THREAD

**Issue by IceflowRE** [wg-easy/wg-easy#1444]
### Describe the bug

Iam unable to upgrade from `weejewel/wg-easy:7`.
Now i tried to upgrade to `ghcr.io/wg-easy/wg-easy:14`, but my clients cannot connect to the internet. The handshake is successful.

| Version | Works |
|---------|---------|
| `weejewel/wg-easy:7` | 🟢 |
| `ghcr.io/wg-easy/wg-easy:7` | 🔴 |
| `ghcr.io/wg-easy/wg-easy:8` | 🔴 |
| `ghcr.io/wg-easy/wg-easy:14` | 🔴 |

Yes it is not a mistake that `ghcr.io/wg-easy/wg-easy:7` is not working.
Was maybe something changed in the PRE/UP default configs?

My docker config (for version 14, i replaced the password with the hash and the correct env variable (i could login))
```yml
services:
  wireguard_easy:
    container_name: wg-easy
    image: weejewel/wg-easy:7
    restart: unless-stopped
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 5000:5000/tcp
    environment:
      LANG: en
      PORT: 5000
      PASSWORD: <password>
      # PASSWORD_HASH: <hash>

      WG_ALLOWED_IPS: 0.0.0.0/0,::/0,192.168.178.0/24
      WG_DEVICE: enp3s0
      WG_HOST: example.com
      WG_PERSISTENT_KEEPALIVE: 25
      WG_PORT: 51820
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /etc/wireguard:/etc/wireguard
```

### Expected behavior

Work just fine!

### Relevant log output

```shell
# weejewel/wg-easy:7

wg-easy  | 2024-09-29T22:25:14.014Z Server Listening on http://0.0.0.0:5000
wg-easy  | 2024-09-29T22:25:14.016Z WireGuard Loading configuration...
wg-easy  | 2024-09-29T22:25:14.018Z WireGuard Configuration loaded.
wg-easy  | 2024-09-29T22:25:14.018Z WireGuard Config saving...
wg-easy  | 2024-09-29T22:25:14.020Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | 2024-09-29T22:25:14.134Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-09-29T22:25:14.171Z WireGuard Config synced.

# ghcr.io/wg-easy/wg-easy:7

wg-easy  | 2024-09-29T22:31:16.148Z Server Listening on http://0.0.0.0:5000
wg-easy  | 2024-09-29T22:31:16.150Z WireGuard Loading configuration...
wg-easy  | 2024-09-29T22:31:16.152Z WireGuard Configuration loaded.
wg-easy  | 2024-09-29T22:31:16.152Z WireGuard Config saving...
wg-easy  | 2024-09-29T22:31:16.154Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | 2024-09-29T22:31:16.271Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-09-29T22:31:16.309Z WireGuard Config synced.
wg-easy  | 2024-09-29T22:31:22.168Z WireGuard Config saving...
wg-easy  | 2024-09-29T22:31:22.170Z WireGuard Config saved.
wg-easy  | 2024-09-29T22:31:22.170Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-09-29T22:31:22.210Z WireGuard Config synced.
wg-easy  | 2024-09-29T22:31:22.851Z WireGuard Config saving...
wg-easy  | 2024-09-29T22:31:22.853Z WireGuard Config saved.
wg-easy  | 2024-09-29T22:31:22.853Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-09-29T22:31:22.891Z WireGuard Config synced.

# ghcr.io/wg-easy/wg-easy:14

wg-easy  | 2024-09-29T22:32:22.313Z Server Listening on http://0.0.0.0:5000
wg-easy  | 2024-09-29T22:32:22.322Z WireGuard Loading configuration...
wg-easy  | 2024-09-29T22:32:22.327Z WireGuard Configuration loaded.
wg-easy  | 2024-09-29T22:32:22.327Z WireGuard Config saving...
wg-easy  | 2024-09-29T22:32:22.330Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | 2024-09-29T22:32:22.509Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-09-29T22:32:22.570Z WireGuard Config synced.
wg-easy  | 2024-09-29T22:32:31.759Z Server New Session: oVa4SMkL80tE9dJe6_fNjhtCFCUsvedP
wg-easy  | 2024-09-29T22:32:34.013Z WireGuard Config saving...
wg-easy  | 2024-09-29T22:32:34.015Z WireGuard Config saved.
wg-easy  | 2024-09-29T22:32:34.015Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-09-29T22:32:34.072Z WireGuard Config synced.
wg-easy  | 2024-09-29T22:32:34.663Z WireGuard Config saving...
wg-easy  | 2024-09-29T22:32:34.664Z WireGuard Config saved.
wg-easy  | 2024-09-29T22:32:34.664Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2024-09-29T22:32:34.725Z WireGuard Config synced.
```
