### ISSUE TITLE
[Bug]: Unable to access WireGuard Web GUI via private WireGuard IP, unless assign new IP

### ISSUE THREAD

**Issue by afunworm** [wg-easy/wg-easy#1475]
### Describe the bug

A bug happened!

I have WireGuard installed as Docker on an Ubuntu 24 server (S). On that same server S, after running WireGuard Docker, I downloaded WireGuard (`apt install wireguard`) and gave it a wg0 profile. This gives S an internal IP of `172.16.0.2`. WireGuard Web UI is listening on `0.0.0.0:51821`. There's no firewall on S. Pinging S using the IP provided by WireGuard will always work.

### Expected behavior

I expected to be able to access the Web UI from a different machine within the network by visiting `172.16.0.2:51821` with the tunnel on. However, it timed out. I can still ping S. If I create a new WireGuard profile and assign it to S, S will get a new IP, say `172.16.0.3`, then I can access the GUI again using `172.16.0.3:51821`.

However, if I reboot S, I won't be able to access the web GUI again. I will have to create a new profile and assign it to wg0 on S for it to work... until the server restarts, then I have to keep create new profile.

I'm not sure where to go from here. Any insights would be highly appreciated.

### Relevant log output

```shell
wg-easy on docker shows no error log.
```

**Comment by kaaax0815** [comment]
I can't follow your description.
Why did you install `wireguard`?
What do you mean by "gave it a wg0 profile".
What do you mean by "within the network"? within the WireGuard Network or Local Network?

Please provide a reproducible description of what you did

**Comment by afunworm** [comment]
> I can't follow your description. Why did you install `wireguard`? What do you mean by "gave it a wg0 profile". What do you mean by "within the network"? within the WireGuard Network or Local Network?
> 
> Please provide a reproducible description of what you did

Hi.

Thanks for the response. I am not the best at explaining, so please bear with me.

Why did you install wireguard? - I would like to access the server S (the server with WireGuard docker installed) through WireGuard VPN. That's why I create a profile (wg0.conf) from the dashboard and install it on that server.

What do you mean by "within the network"? within the WireGuard Network or Local Network? - I mean with VPN on.

Here were what I do:
1. Install wg-easy on server S (listening on 0.0.0.0:51821).
2. Install wireguard on S (`apt`).
3. Go on to wg-easy GUI, add "New".
4. Download the profile to S (`/etc/wireguard/wg0.conf`) and activate the tunnel (`systemctl start wg-quick@wg0`). Now the `wg` interface has the IP of `172.16.0.2`. At this point, from S, I did `curl 0.0.0.0:51821` and it worked perfectly.

After that, I expected to be able to access the WireGuard Web GUI from any machine that has WireGuard configured, by visiting `172.16.0.2:51821`. However, it always times out. If I go to wg-easy Web and create a new `conf` file and replace the current `/etc/wireguard/wg0.conf` and restart the service `systemctl restart wg-quick@wg0`, then I am able to access it through `172.16.0.2:51821`. If I restart the VPS, I will have to repeat these steps in order to access the GUI from another machine.

In the end, my goal is to be able to access the GUI when I have WireGuard turned on by using the server's WireGuard IP.

Thank you again for your time.

**Comment by kaaax0815** [comment]
`wg-easy` already starts a WireGuard Server, there is no need to add a Client and start it on that same server.

If you have a Machine X. And download the Config through the Web UI (has the name of the client (`Maschine-X.conf`) and start in on that Maschine. Everything should work

**Comment by afunworm** [comment]
> `wg-easy` already starts a WireGuard Server, there is no need to add a Client and start it on that same server.
> 
> If you have a Machine X. And download the Config through the Web UI (has the name of the client (`Maschine-X.conf`) and start in on that Maschine. Everything should work

Thank you for the insight. So I don't need to install WireGuard Client on the server I have wg-easy install, am I correct?

If so, what will be the WireGuard IP address of that server S if I want to access it from a different machine? Would it be assigned an IP automatically that came with the wg-easy installation?

I assumed it was 172.16.0.1 (the first of the subnet) but apparently, 172.16.0.1:51821 wouldn't work. From the server S, `0.0.0.0:51721` and `127.0.0.1:51721` will work, but `172.16.0.1:51821` will time out.

Below is my config file:
```
services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:latest
    restart: unless-stopped
    sysctls:
        - net.ipv4.ip_forward=1
        - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
        - SYS_MODULE
        - NET_ADMIN
    ports:
        - '51821:51821/tcp'
        - '51820:51820/udp'
    volumes:
        - './etc/wireguard:/etc/wireguard'
    environment:
        - WG_PORT=51820
        - PORT=51821
        - WG_PERSISTENT_KEEPALIVE=60
        - PASSWORD_HASH=PASSWORD_HASH
        - WG_HOST=MY_PUBLIC_IP_ADDRESS
        - WEBUI_HOST=0.0.0.0
        - WG_DEFAULT_ADDRESS=172.16.0.x
        - WG_ALLOWED_IPS=172.16.0.0/24

networks:
  default:
    external: true
    name: docker_network
```

The docker_network is simply a docker with subnet 172.16.0.0/24.
