### ISSUE TITLE
[Bug]: wg-easy + NGINX manual is outdated

### ISSUE THREAD

**Issue by jursed** [wg-easy/wg-easy#1507]
### Describe the bug

[This Docker Compose file](https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL#docker-composeyml) is invalid, because it uses `PASSWORD` instead of `PASSWORD_HASH`. Running it results errors in the wg-easy container.

1. Simplest fix: change `PASSWORD` -> `PASSWORD_HASH`.
2. Better fix: replace `environment` with  [**`env_file`**](https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#use-the-env_file-attribute).
3. Best fix: use [secrets](https://docs.docker.com/compose/how-tos/use-secrets/#simple).
   ```
   services:
     wg-easy:
       [...]
       secrets:
         - password_hash

   secrets:
     password_hash:
       file: password_hash
   ```
   Then you just put a `password_hash` file alongside the Dockerfile (or wherever it suits the user). Inside the container, it will be accessible in `/run/secrets/password_hash`.

Option 2 enables using the same single-quoted strings that are used for the CLI command, and option 3 doesn't need any quoting at all (just a copy-paste of the raw hash value). In either case, it bypasses the whole YAML-parsing nonsense and the `$$`-escaping described in [the wgpw readme](https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md).
