### ISSUE TITLE
[Bug]: Each time the container is restarted, I get unauthorized from web UI, and require restarting it again

### ISSUE THREAD

**Issue by marco-calautti** [wg-easy/wg-easy#1525]
### Describe the bug

If I stop my containers using docker compose, and then bring again the stack up, the web UI does not allow me to login, getting "unauthorized". I need to do a `docker compose restart` or again `docker compose up -d` and then I can login again.

### Expected behavior

Login should always work, in-between restarts.

### Relevant log output

```shell

```

**Comment by kaaax0815** [comment]
Do you have any more information? What do you use to bring the stack down and up again?

**Comment by marco-calautti** [comment]
I use `docker compose stop` to bring it down, and then `docker compose up -d` to bring it up.

**Comment by kaaax0815** [comment]
There could be some bugs with `docker compose stop` try using `docker compose down` and see if this fixes it

**Comment by luisgcu** [comment]
I got the same problem.
![Image](https://github.com/user-attachments/assets/cbef223f-757a-4753-81e8-5cb2c70ec681)

**Comment by marco-calautti** [comment]
> There could be some bugs with `docker compose stop` try using `docker compose down` and see if this fixes it

I doubt there are bugs in compose stop, as all other services I stop like that are able to restart without issues.

**Comment by kaaax0815** [comment]
There are indeed containers with the same problem. Could you verify that it fixes the problem?

**Comment by rivera2387** [comment]
I'm also encountering the same problems. However, it started after I tried to change the hashed password to a new one. I tried doing the same things, removing the old container and creating a new one. However, I'm still getting unauthorized. I also tried to put the old hash password back in docker compose, but that one is still giving me unauthorized as well.

**Comment by rivera2387** [comment]
> I'm also encountering the same problems. However, it started after I tried to change the hashed password to a new one. I tried doing the same things, removing the old container and creating a new one. However, I'm still getting unauthorized. I also tried to put the old hash password back in docker compose, but that one is still giving me unauthorized as well.

Whoops, my bad. I did not see the part where I had to replace each $ with $$. Once I did that, I can now use passwords in the Web UI.

**Comment by marco-calautti** [comment]
> There are indeed containers with the same problem. Could you verify that it fixes the problem?

I am now using docker compose down and then docker compose up -d, but I still get unauthorized.

**Comment by kaaax0815** [comment]
But with restart you can login?

**Comment by marco-calautti** [comment]
Yes. In case I get unauthorized, then I need to do docker compose restart, and then it works.

**Comment by marco-calautti** [comment]
```yaml
vpn-wg-easy:
    container_name: vpn-wg-easy
    image: ghcr.io/wg-easy/wg-easy
    environment:
      - WG_HOST=${VPN_DOMAIN_FREEDNS}

      # Optional:
      # generated from my password using: sudo docker run -it ghcr.io/wg-easy/wg-easy wgpw <MY_PASSWORD>
      # must replace each $ in the hash with $$ to inject it here with env vars.
      - PASSWORD_HASH=${WIREGUARD_PASSWORD_HASH}
      - WG_DEFAULT_DNS=${WIREGUARD_DNS}
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_MTU=1420
      #-  WG_ALLOWED_IPS=
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

    networks:
      - vpn-net
    volumes:
      - '${BASE_STORAGE_DIR}/${VPN_DATA_DIR}:/etc/wireguard'
    ports:
      - "51820:51820/udp" # must forward this port in router
      - "51821:51821"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Comment by SancteRomualde** [comment]
Pheiduk is the one allowed to hire allow access with Dr Brahmi, Dr Neury, Belle-Idée Hospital, Donald J TRump,and Olivier Wyssa, Dao Scholastica Wyssa and authorized people from the committee. Vonlanthen and Achour can

**Comment by SancteRomualde** [comment]
There's a spy with Motorola in the unit called the cops already but didn't come yet

**Comment by SancteRomualde** [comment]
The guy tries to insult me. To intimidate. Feel stressed.

**Comment by SancteRomualde** [comment]
Junkie or dealer or both

**Comment by PawsFunctions** [comment]
I faced a similar issue, and the solution was to use the `env_file`. I am using Dockge on TrueNAS, and it works perfectly now.

```
version: "3.3"
services:
  wg-easy:
    env_file: .env
    container_name: wg-easy
    volumes:
      - /mnt/POOL/apps-data/wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    image: ghcr.io/wg-easy/wg-easy
    networks:
      - unifi-network-application_unifi-network-application
networks:
  unifi-network-application_unifi-network-application:
    external: true
```
env file ".env"
```
# VARIABLE=value #comment
PASSWORD_HASH='HASH here'
LANG=en
WG_HOST=my_publick_ip
PORT=51821
WG_PORT=51820
```

NOTE : I had different ports in use, but for simplicity, I changed them to the default ones. However, I still recommend changing them to new, random ports.
