### ISSUE TITLE
[Bug]: wg0 interface not created

### ISSUE THREAD

**Issue by lukekroon** [wg-easy/wg-easy#1565]
### Describe the bug

I have the following script to deploy a new service in our docker swarm. The goal is to remotely access services in the docker swarm.

`
version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    networks:
      - global
    environment:
      LANG: en
      WG_HOST: xxx.xxx.xxxx.xxx
      WG_DEFAULT_ADDRESS: 10.6.0.x
      WG_DEFAULT_DNS: 1.1.1.1
      WG_ALLOWED_IPS: 10.6.0.0/24
      WG_DEVICE: eno1
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
        reservations:
          memory: "128M"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv4.conf.all.src_valid_mark: "1"

volumes:
  etc_wireguard:
    external: true

networks:
  global:
    external: true
`

The service starts up with the following logs:

`
2024-12-13T09:26:21.213Z Server Listening on http://0.0.0.0:51821
2024-12-13T09:26:21.223Z WireGuard Loading configuration...
2024-12-13T09:26:21.227Z WireGuard Configuration loaded.
2024-12-13T09:26:21.227Z WireGuard Config saving...
2024-12-13T09:26:21.236Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
2024-12-13T09:26:21.640Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2024-12-13T09:26:21.831Z WireGuard Config synced.
`

I can then access the web interface, create a new client and connect. I can verify on the UI that the client is connected and there is traffic moving. However I cannot access any of the services running on the server and there is no `wg0` interface on the host.

### Expected behavior

I copied the `wg0.conf` from the docker volume and used that to start wireguard directly from the host (`wg-quick up wg0`) and that allows me to connect with the same client config and access the services. I can also then see the `wg0` interface.

### Relevant log output

```shell

```

**Comment by kaaax0815** [comment]
This is expected as the `wg0` interface exists inside the docker container.
`WG_DEVICE` should probably be `eth0` as you have to check what the interface inside the container is named.

The host networking doesn't matter as you are using docker

**Comment by kvietcong** [comment]
I found it easier to make it so the container runs directly w/ the host's network using the `network_mode` directive. This way the container would be creating a network relevant to the whole machine and commands like `wg show` outside the container actually show the interface.

The default dns just allows me to reach various devices w/ user friendly names provided by the internal DNS server I have on the Wireguard server.

Here's my minimal config example

```
volumes:
  etc_wireguard: null
services:
  wg-easy:
    network_mode: host
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy
    environment:
      WG_HOST: ${WG_HOST}
      WG_MTU: 1280
      WG_DEVICE: ${WG_DEVICE}
      WG_DEFAULT_DNS: ${WG_SERVER_IP}
      WG_DEFAULT_ADDRESS: 10.1.1.x
      WG_ALLOWED_IPS: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
    volumes:
      - ${DATA_PATH}:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
```
