### ISSUE TITLE
[Bug]: Client's public IP does not change when connected

### ISSUE THREAD

**Issue by androslavic** [wg-easy/wg-easy#1639]
### Describe the bug

When I was using stock Wireguard I would connect to server and my public IP would be the same as the host's public IP. With current configuration I am able to access local network and DNS server.

I am using Pi-hole for DNS in separate docker container with macvlan interface.

I can ping from client into the local network. I can ping client from wg-easy and pihole container. I cannot ping client from other devices in local network.

```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=######.duckdns.org
      - WG_DEFAULT_ADDRESS=192.168.2.x
      - WG_DEFAULT_DNS=192.168.2.149 # pihole dns
      - WG_ALLOWED_IPS=192.168.2.0/24
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      - 
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      pihole_pihole_network:
        ipv4_address: '192.168.2.150' # router forwards udp/51820 here

networks:
  pihole_pihole_network:
    external: true
```

### Expected behavior

Client's public IP should be the same as the host's public IP. 

### Relevant log output

```shell
wg-easy    | 2025-02-03T00:26:09.860Z Server Listening on http://0.0.0.0:51821
wg-easy    | 2025-02-03T00:26:09.881Z WireGuard Loading configuration...
wg-easy    | 2025-02-03T00:26:09.893Z WireGuard Configuration loaded.
wg-easy    | 2025-02-03T00:26:09.894Z WireGuard Config saving...
wg-easy    | 2025-02-03T00:26:09.904Z WireGuard Config saved.
wg-easy    | $ wg-quick down wg0
wg-easy    | $ wg-quick up wg0
wg-easy    | 2025-02-03T00:26:10.421Z WireGuard Config syncing...
wg-easy    | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy    | 2025-02-03T00:26:10.602Z WireGuard Config synced.

{
  "server": {
    "privateKey": "KPkJ3b8fBVFhfGSbTe3JQGPUeMKg74u1yeeyy5GYjl0=",
    "publicKey": "wu+8TyVpx8jlWi2fd2RIUHqwlvBSDcJjQMw1qoBuHjc=",
    "address": "192.168.3.1"
  },
  "clients": {
    "xxxx": {
      "id": "xxxx",
      "name": "Samsung A54",
      "address": "192.168.2.2",
      "privateKey": "xxxx",
      "publicKey": "xxxx",
      "preSharedKey": "xxxx",
      "createdAt": "2025-02-03T00:22:09.796Z",
      "updatedAt": "2025-02-03T00:23:30.542Z",
      "enabled": true
    }
  }
}
```
