### ISSUE TITLE
[Bug]: running in podman results in sub mbit/s on LAN, `/usr/bin/pasta` uses 100% of CPU

### ISSUE THREAD

**Issue by jmakov** [wg-easy/wg-easy#1650]
### Describe the bug

Following https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Podman#run-with-podman-compose, I see less than 1mbit/s download speeds on LAN. Server Ryzen 5900x, client Pixel 9 Pro.

config.yaml:
```
  GNU nano 8.1                                                                                                                                                                                                                                                                                                          docker-compose.yml                                                                                                                                                                                                                                                                                                                   
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=my_pub_ip

      # Optional:
      - PASSWORD_HASH=myhash
      - PORT=51821
      - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
#      - WG_DEFAULT_DNS=
      - WG_MTU=1280
      - WG_ALLOWED_IPS=0.0.0.0/1, 128.0.0.0/1
      - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

### Expected behavior

Would expect at least 50% of the available bandwidth.

### Relevant log output

```shell

```
