### ISSUE TITLE
[Bug]: Help with the API, how to resolve a 500 error?

### ISSUE THREAD

**Issue by ttmaks** [wg-easy/wg-easy#1664]
### Describe the bug

When accessing the API, I receive a 500 error with any commands. I can't figure out what the issue is and I'm asking for help from specialists.

Here is an example of a request:
```shell
root@server:/var/www/vpn.com# curl -H "Authorization: Bearer 1ba388ebd03fe737be3d28c12fd4c35957d88527a432dc5403e6383736a2a5bc8" http://localhost:51821/api/stats  
{ "statusCode": 500, "stack": [] }
```

Here is my docker-compose.yml:
```yaml
version: '3.8'
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - WG_HOST=vpn.com
      - WG_PORT=51820     
      - PORT=51821           
      - PASSWORD_HASH=<your_password_hash>
      - WG_API_ENABLED=true  
      - WG_API_SECRET=<your_api_token>
    volumes:
      - ./data:/etc/wireguard 
    ports:
      - "51820:51820/udp"      
      - "51821:51821/tcp"   
    cap_add:
      - NET_ADMIN             
      - SYS_MODULE 
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1 
    restart: unless-stopped
```
### Expected behavior

Work just fine!

### Relevant log output

```shell

```
