### ISSUE TITLE
[Bug]: Cannot access AGH admin panel

### ISSUE THREAD

**Issue by EvgeniyDoctor** [wg-easy/wg-easy#1694]
### Describe the bug

I use it with Adguard home. It worked perfectly with normal wireguard, but with wgeasy i cannot access the AGH admin panel. Do you know why? Because wgeasy does not have normal PEERDNS parameter. And yes, i already wasted my time, triying to make it work using this guide for pihole: https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole
In normal wireguard i just had `- PEERDNS=10.2.0.100 # Set it to point to adguard home` and everything worked.

Part of my yml:
```
services:
  wgeasy:
    image: weejewel/wg-easy:latest
    container_name: wgeasy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=host
      - PASSWORD=pass
      - WG_DEFAULT_DNS=10.2.0.100
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3
    deploy:
      resources:
        limits:
          memory: 32m

  adguard:
    container_name: ag
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work"
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100
    deploy:
      resources:
        limits:
          memory: 64m

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
```

### Expected behavior

I should have been able to open the AGH admin panel.

### Relevant log output

```shell

```
