### ISSUE TITLE
[Bug]: Cant get the password to work - UI password screen doesnt show

### ISSUE THREAD

**Issue by roycw** [wg-easy/wg-easy#1708]
### Describe the bug

Guys, 
Putting in my docker PASSWORD AND PASSOWRD HASH. nothing works i dont get the login screen and go straight to the ui. is that a know issue.?

**Comment by kaaax0815** [comment]
If you set the password as documented in the `production` branch. with the `PASSWORD_HASH` env var this should not happen.

please post your docker compose file or docker run command

**Comment by pirmax** [comment]
Me too, this issue is weird. Docker config:

```
services:
  wg-easy:
    image: 'ghcr.io/wg-easy/wg-easy:latest'
    environment:
      - 'WG_HOST=https://vpn.domain.com'
      - LANG="en"
      - PORT=8000
      - WG_PORT=51820
      - PASSWORD_HASH='$$2a$$12$$...'
    volumes:
      - 'wg-easy:/etc/wireguard'
    ports:
      - '51820:51820/udp'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
```
