### ISSUE TITLE
Container cannot start

### ISSUE THREAD

**Issue by morvy** [wg-easy/wg-easy#174]
Hi,
since v5 release my container won't start. I tried :latest, :5, :4 and :nightly ..all of them with same result on RPi3. Latest docker, kernel etc.. Portainer, Watchtower and Pi-hole are on the same RPi3 and those are running fine so it shouln't be an issue with docker or RPi, right?

```
#FailureMessage Object: 0x7e87753c


#
# Fatal error in , line 0
# unreachable code
#
#
#
```

my docker-compose.yml

```
version: "3.1"

services:
  wg-easy:
    environment:
      # Change this to your host's public address
      - WG_HOST=IP_address

      # Optional:
      - PASSWORD=123456
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=192.168.11.x
      - WG_DEFAULT_DNS=1.1.1.1,8.8.8.8
      - WG_ALLOWED_IPS=192.168.11.0/24,172.17.0.0/16

    image: weejewel/wg-easy:5
    container_name: wg-easy
    volumes:
      - /home/pi/wg-easy/data:/etc/wireguard
    network_mode: bridge
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
