### ISSUE TITLE
[Bug]: Not Working

### ISSUE THREAD

**Issue by yhl452493373** [wg-easy/wg-easy#1742]
### Describe the bug

I come from china, here is my docker-compose.yml
```yml
services:
  wg-easy:
    environment:
      - PORT=51821
      - HOST=0.0.0.0
      - INSECURE=true
      - INIT_ENABLED=true
      - INIT_USERNAME=myusername
      - INIT_PASSWORD=MyPassword@123
      - INIT_HOST=HostIP
      - INIT_PORT=21820
      - INIT_DNS=223.5.5.5,2400:3200::1
      - INIT_IPV4_CIDR=10.10.10.0/24
      - INIT_IPV6_CIDR=fd0a:a:a::/112

    image: ghcr.nju.edu.cn/wg-easy/wg-easy:15.0.0-beta.10
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fd0a:2a:2a::2a
    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - 21820:51820/udp
      - 21821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fd0a:2a:2a::/112
```

When the docker started, i can access to the management page with http://HostIP:21821 . But after i create a new client, and download the config file to my windows pc , then import it into WireGuard. But from the management page, it appears that the client is not connected to the server and cannot ping to server.

This happend after pull request [Feat: Initial Setup through env vars](https://github.com/wg-easy/wg-easy/commit/86bdbe4c3d7f8b6d742acfdfc017917e656953ea)

### Expected behavior

Work just fine!

### Relevant log output

```shell

```
