### ISSUE TITLE
[Bug]: Backed config files and QR codes

### ISSUE THREAD

**Issue by colotoon** [wg-easy/wg-easy#1793]
### Describe the bug

A bug happened!

Hello everyone
Today I was glad that coolify has a simple VPN setup
Installed it
Opened the dashboard and created a client

I open the QR code, try to import it first through the android app v2ray-error, it is not possible to recognize the endpoint!
Download from Google Play Market - Wireguard
I open it, select import from QR - the same error!

I download the latest version for Windows, try to import the configuration file and?
The same error!
But with explanations:
unable to import the configuration, the IPv6 address must be in parentheses!

Guys, what's wrong with your GUI and why is it giving out broken configuration files??

Config file:
```
[Interface]
PrivateKey = cL61Q4XxibXcyKRJOvVRubolI1RQ3kz++XQTrdRs/E4=
Address = 10.8.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = HfiyJ9YY8V7KC/JURM3y4crM5p+br07Gcy+DKJEyf3E=
PresharedKey = TpljpFz64Jk1dvGtq5IFnIoXZxvSjmtYHe4A4RL/VIk=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = http://wireguardeasy-e4goww8k8go4ogc4sg4cg8cw.3.3.3.3.sslip.io:51820
```

Docker compose file:
```
services:
  wg-easy:
    image: 'ghcr.io/wg-easy/wg-easy:latest'
    environment:
      - SERVICE_FQDN_WIREGUARDEASY_8000
      - 'WG_HOST=${SERVICE_FQDN_WIREGUARDEASY}'
      - 'LANG=${LANG:-en}'
      - PORT=8000
      - WG_PORT=51820
    volumes:
      - 'wg-easy:/etc/wireguard'
    ports:
      - '51820:51820/udp'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

```

### Expected behavior

Work just fine!

### Relevant log output

```shell

```
