### ISSUE TITLE
[Feat]: Relative path for web GUI

### ISSUE THREAD

**Issue by kalle-crystalspace** [wg-easy/wg-easy#1802]
### Description

Currently the web GUI is hard coded to use `"/"` as the base path, making it impossible to reverse proxy it to other sub folders i.e. `localhost/wg-easy`. It should be relatively simple to fix this by setting the base/public paths in nuxt and vue.

### Suggested Solution

Documentation here:
https://cli.vuejs.org/config/#publicpath
https://vite.dev/guide/build#relative-base

**Comment by kaaax0815** [comment]
this doesn't work with middlewares therefore is not implemented. see this comment https://github.com/wg-easy/wg-easy/issues/1704#issuecomment-2705873936

if you find a good way to handle this please let me know

**Comment by IceflowRE** [comment]
But you can still force a subpath with an NGINX proxy? or not.

**Comment by kalle-crystalspace** [comment]
@kaaax0815 thanks I'll if using `NUXT_APP_BASE_URL` fixes my issue

**Comment by kaaax0815** [comment]
`NUXT_APP_BASE_URL` should not work. as redirections through middlewares do not use it

**Comment by IceflowRE** [comment]
> [@IceflowRE](https://github.com/IceflowRE) I'm using an nginx front-end currently but the problem is that all assets are still referencing the root path.

I am using v14 behind a Nginx proxy and a subpath, not clue about v15.

**Comment by IceflowRE** [comment]
```
location /wireguard/ {
	rewrite ^/wireguard/(.*) /$1 break;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header Host $http_host;
	proxy_redirect off;
	proxy_cookie_path / /wireguard/;
	proxy_pass http://127.0.0.1:5000;
}
```
With wg-easy running at port `5000` and subpath `/wireguard`

**Comment by IceflowRE** [comment]
Just to clarify, this problem is also in v15 and is not fixable with a proxy.
So if you want to serve it in a sub path stay at v14.

**Comment by martinarisk** [comment]
prease fix this

**Comment by Kenya-West** [comment]
This somehow works for me with [homeall/caddy-reverse-proxy-cloudflare](https://github.com/homeall/caddy-reverse-proxy-cloudflare) and this docker-compose,yml (notice the `labels` section):

```yaml
---

services:
  wg:
    image: ghcr.io/wg-easy/wg-easy
    container_name: ${SERVICE_NAME}
    volumes:
      - ./wg-easy:/etc/wireguard
    networks:
      - caddy
    ports:
      - "${WG_PORT}:51920/udp"
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      caddy: "${SERVICE_DOMAIN}:${EXTERNAL_PORT:-443}"
      caddy.handle_path: "/internal-network/predefined/${SERVICE_NAME}/*"
      caddy.handle_path.reverse_proxy: "{{ upstreams ${SERVICE_PORT_INTERNAL} }}"

networks:
  caddy:
    external: true

volumes:
  etc_wireguard:
```

![Image](https://github.com/user-attachments/assets/1a68d3ad-0aa5-4f74-8546-4cd507fc810f)

The `<head>` section of webserver response has relative paths and open every asset on relative path:

```html
<head><style data-merge-styles="true"></style>
  <style data-merge-styles="true"></style><style data-merge-styles="true"></style><title>WireGuard</title>
  <meta charset="utf-8">
  <link href="./css/app.css" rel="stylesheet">
  <link rel="manifest" href="./manifest.json">
  <link rel="icon" type="image/png" href="./img/favicon.png">
  <link rel="apple-touch-icon" href="./img/apple-touch-icon.png">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<style>
  [v-cloak] {
    display: none;
  }
  .line-chart .apexcharts-svg{
    transform: translateY(3px);
  }
</style></head>
```

If somebody has explanation why this works for me but for people above it does not, please write down. I hope I don't break things!
