### ISSUE TITLE
[Bug]: Web UI allows login over HTTP even with INSECURE=false

### ISSUE THREAD

**Issue by B-X-Y** [wg-easy/wg-easy#1841]
### Describe the bug

When running Wg-Easy with INSECURE=false, the documentation and expected behavior suggest that login over HTTP should be blocked (https://github.com/wg-easy/wg-easy/issues/1755#issuecomment-2747048368). However, I'm able to log in via both:

https and nginx-port (expected)
http and raw raw-port (unexpected)

I have a web UI port exposed to 0.0.0.0:51823 and the other port to 0.0.0.0:51822 and I'm using Nginx as a reverse proxy to serve the UI securely on another port with HTTPS. Despite INSECURE=false, logging in over plain HTTP still succeeds.

Environment Information:

Docker Version: Docker version 27.5.1
Wg-Easy Version: ghcr.io/wg-easy/wg-easy:14
Host OS: Ubuntu 24.04.1 LTS
Reverse Proxy: nginx version: nginx/1.24.0 (Ubuntu) with Let's Encrypt

### Expected behavior

Web UI may be accessible over HTTP, but should not allow login unless:

The connection is over HTTPS
INSECURE=true is set

### Relevant log output

```shell
2025-05-03T18:08:01.135Z Server Listening on http://0.0.0.0:51823
2025-05-03T18:08:01.141Z WireGuard Loading configuration...
2025-05-03T18:08:01.145Z WireGuard Configuration loaded.
2025-05-03T18:08:01.145Z WireGuard Config saving...
2025-05-03T18:08:01.148Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
2025-05-03T18:08:01.273Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2025-05-03T18:08:01.310Z WireGuard Config synced.
2025-05-03T18:08:10.784Z Server New Session: [REDACTED]
2025-05-03T18:08:18.269Z Server New Session: [REDACTED]
```

**Comment by B-X-Y** [comment]
I understand that I can prevent login over HTTP by simply not exposing the port.
However, the current behavior contradicts both the documentation and previous maintainer comments, which indicate that INSECURE=false should block login even if the port is exposed.
If that's no longer true, the docs should be updated accordingly. If it is still intended, then it may be a regression.

**Comment by kaaax0815** [comment]
`INSECURE=false` just means that the secure option for the cookie is not set. therefore the browser should reject the cookie if the connection is not secure. if you access the site over e.g. localhost it would still work

**Comment by B-X-Y** [comment]
When `INSECURE=false`, the expected behavior is that the session cookie should include the `Secure` attribute so that browsers reject it over HTTP. I verified the `Set-Cookie` headers using both `curl` and Chrome DevTools, and the results are the same regardless of the `INSECURE` value:

`INSECURE=true`: `Set-Cookie: connect.sid=...; Path=/; HttpOnly`
`INSECURE=false`: `Set-Cookie: connect.sid=...; Path=/; HttpOnly`

The `Secure` flag is missing in both cases. This indicates that the environment variable is either not being read correctly or not being applied properly in the cookie configuration logic. As a result, logging in over HTTP is possible even when `INSECURE=false`, which goes against the documented and expected behavior.

Can you confirm whether the cookie configuration correctly respects the `INSECURE` setting?

**Comment by kaaax0815** [comment]
Could you share the way you set the env var? your docker compose file or docker run command?

**Comment by B-X-Y** [comment]
Each configuration was tested independently in its own container to avoid cross-contamination. I also verified via `docker exec <container> env` that the `INSECURE` variable is correctly set (or unset) in each case. Despite this, the `Set-Cookie` header never includes the `Secure` flag, regardless of the value of `INSECURE`.

For `INSECURE=true`:
```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=[REDACTED]

      - PORT=51825
      - WG_PORT=51824
      - PASSWORD_HASH=[REDACTED]
      - INSECURE=true
      # Optional:
      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy-insecure-true
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51824:51824/udp"
      - "51825:51825/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
volumes:
  etc_wireguard:
```
For `INSECURE=false`:
```
services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=[REDACTED]

      - PORT=51827
      - WG_PORT=51826
      - PASSWORD_HASH=[REDACTED]
      - INSECURE=false
      # Optional:
      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy-insecure-false
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51826:51826/udp"
      - "51827:51827/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
volumes:
  etc_wireguard:
```
For `INSECURE` not set:
```
services:
  wg-easy:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=[REDACTED]

      - PORT=51829
      - WG_PORT=51828
      - PASSWORD_HASH=[REDACTED]
      # Optional:
      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wg-easy-insecure-none
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51828:51828/udp"
      - "51829:51829/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
