### ISSUE TITLE
[Bug]: Unable to start wg-easy 15

### ISSUE THREAD

**Issue by cabaucom376** [wg-easy/wg-easy#1842]
### Describe the bug

The container fails to start and gets stuck in an unhealthy state:

wg-easy compose:
```yaml
# --------- #
#  WG-easy  #
# --------- #
# version: 1

services:
  wg-easy:
    container_name: wg-easy
    hostname: wg-easy
    image: ghcr.io/wg-easy/wg-easy:${CONTAINER_TAG:-latest}

    environment:
      - LANG=en  # [en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi]
      - WG_HOST=${PUBLIC_DOMAIN:?}
      # (Optional):
      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS:?}
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # [0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart]

    volumes:
      - ./data:/etc/wireguard

    ports:
      # Tunnel
      - 51820:51820/udp
      # WebUI
      - 51821:51821/tcp

    networks:
      - public

    # (Optional) Configure Traefik labels for reverse proxy integration.
    # Requires Traefik to be set up and connected to the `public` network.
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.services.wg-easy.loadbalancer.server.port=51821
      - traefik.http.services.wg-easy.loadbalancer.server.scheme=http
      - traefik.http.routers.wg-easy-https.entrypoints=websecure
      - traefik.http.routers.wg-easy-https.rule=Host(`${PUBLIC_DOMAIN:?}`)
      - traefik.http.routers.wg-easy-https.tls=true
      - traefik.http.routers.wg-easy-https.tls.certresolver=namecheap # <─── (Required) update to your DNS resolver.
      # - com.centurylinklabs.watchtower.enable=true  # <─── (Optional) to enable updates for this service via Watchtower.

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW  # <─── (Required) if using Podman.

    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

    restart: unless-stopped

networks:
  public:
    external: true
```

traefik compose:
```yaml
# --------- #
#  Traefik  #
# --------- #
# version: 1

services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:${CONTAINER_TAG:-latest}

    environment:
      - NAMECHEAP_API_USER=${NAMECHEAP_API_USER:?}  # <─┬─ (Optional) if resolving certificates with Namecheap
      - NAMECHEAP_API_KEY=${NAMECHEAP_API_KEY:?}    # <─┘

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Configuration
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      # Certificates
      - ./data/certs/:/var/traefik/certs/:rw

    ports:
      # HTTP
      - 80:80
      # HTTPS
      - 443:443
      - 8080:8080  # <─── (Optional) to expose the dashboard.

    networks:
      - public

    restart: unless-stopped

networks:
  public:
    external: true
```

traefik config:
```yaml
# --------- #
#  Traefik  #
# --------- #
# version: 1

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# (Optional) Change log level and format
log:
 level: INFO  # [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]

# (Optional) Enable API and Dashboard, don't do in production
api:
  dashboard: true
  insecure: true

# EntryPoints
entryPoints:
  # (Optional) Enables http
  web:
    address: :80
    # (Optional) Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  # HTTPS
  websecure:
    address: :443

# CertificateResolver Configuration
certificatesResolvers:
  # This is the name for your Traefik resolver, change it to match your DNS provider:
  # https://doc.traefik.io/traefik/https/acme/#providers
  namecheap:
    acme:
      email: [REDACTED]  # <─── (Required) Change this to your email
      storage: /var/traefik/certs/namecheap-acme.json  # <─── (Required) Update based on your DNS provider
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: EC256
      dnsChallenge:
        provider: namecheap  # <─── (Required) Change this to your DNS provider
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # <─── (Optional) Change this to true if you want to expose all services
  file:
    directory: /etc/traefik
    watch: true
```

### Expected behavior

Container to start with no errors and for Traefik to fetch an ssl certificate like my other containers on my server.

### Relevant log output

```shell
wg-easy  | Migrating database...
wg-easy  | ====================================================
wg-easy  |     wg-easy - https://github.com/wg-easy/wg-easy    
wg-easy  | ====================================================
wg-easy  | | wg-easy:  v15.0.0-beta.12                        |
wg-easy  | | Node:     v22.15.0                               |
wg-easy  | | Platform: linux                                  |
wg-easy  | | Arch:     arm64                                  |
wg-easy  | ====================================================
wg-easy  | Migration complete
wg-easy  | Starting WireGuard...
wg-easy  | Generating new Wireguard Keys...
wg-easy  | $ wg genkey
wg-easy  | Listening on http://0.0.0.0:51821
wg-easy  | $ echo ***hidden*** | wg pubkey
wg-easy  | New Wireguard Keys generated successfully.
wg-easy  | Starting Wireguard Interface wg0...
wg-easy  | Saving Config...
wg-easy  | Config saved successfully.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | [unhandledRejection] Error: Command failed: wg-quick up wg0
wg-easy  | [#] 
wg-easy  | [#] ip link add wg0 type wireguard
wg-easy  | [#] wg setconf wg0 /dev/fd/63
wg-easy  | [#] ip -4 address add 10.8.0.1/24 dev wg0
wg-easy  | [#] ip -6 address add fdcc:ad94:bacf:61a4::cafe:1/112 dev wg0
wg-easy  | [#] ip link set mtu 1420 up dev wg0
wg-easy  | [#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -s fdcc:ad94:bacf:61a4::cafe:0/112 -o eth0 -j MASQUERADE; ip6tables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -A FORWARD -o wg0 -j ACCEPT;
wg-easy  | modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/6.12.20+rpt-rpi-v8
wg-easy  | ip6tables v1.8.11 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
wg-easy  | Perhaps ip6tables or your kernel needs to be upgraded.
wg-easy  | [#] ip link delete dev wg0
wg-easy  | 
wg-easy  |     at genericNodeError (node:internal/errors:983:15)
wg-easy  |     at wrappedFn (node:internal/errors:537:14)
wg-easy  |     at ChildProcess.exithandler (node:child_process:414:12)
wg-easy  |     at ChildProcess.emit (node:events:518:28)
wg-easy  |     at maybeClose (node:internal/child_process:1101:16)
wg-easy  |     at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
wg-easy  |   code: 3,
wg-easy  |   killed: false,
wg-easy  |   signal: null,
wg-easy  |   cmd: 'wg-quick up wg0'
wg-easy  | }
```
