### ISSUE TITLE
[Bug]: No connection to multible docker subnets

### ISSUE THREAD

**Issue by worldwidehigh** [wg-easy/wg-easy#1877]
### Describe the bug

I would like to connect to my Docker server using the VPN connection. This works so far. However, I have several Docker subnets there that I cannot or can only partially reach.

Here is my compose file:

```
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15.0.0-beta.12
    container_name: ${NAME}
    environment:
      - PORT=${PORT}
      - INSECURE=true
    volumes:
      - daten:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "${WGPORT}:${WGPORT}/udp"
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

    networks:
      default:
        ipv4_address: ${IP}
        driver_opts:
          com.docker.network.endpoint.ifname: eth0
       
volumes:
  daten:
    name: ${NAME}-daten
    
networks:
  default:
    name: ${NETEXTERN}
    ipam:
      config:
        - subnet: 192.250.90.0/24
          gateway: 192.250.90.1
```

Here is the client config:

```
[Interface]
Address = 192.251.90.3/24, fdcc:ad94:bacf:61a4::cafe:3/112
PrivateKey = ???
DNS = 1.1.1.1
MTU = 1420

[Peer]
Endpoint = ??
PublicKey = ??
PresharedKey = ??
PersistentKeepalive = 25
AllowedIPs = 0.0.0.0/0
```

I can ping individual containers on the client in the different subnets but cannot reach the web interfaces. If the containers are in the same Docker subnet as the VPN, the web interfaces are accessible.

### Expected behavior

I want to reach all Docker subnets (IP + ports) with the VPN connection.

### Relevant log output

```shell

```
