### ISSUE TITLE
[Bug]: Doesn't listen on localhost when changing the optional environment variables

### ISSUE THREAD

**Issue by agathakazar** [wg-easy/wg-easy#1899]
### Describe the bug

With config modified like so:
```
services:
  wg-easy:
    environment:
    #  Optional:
      - PORT=51821
      - HOST=localhost
    #  - INSECURE=false
```
It doesn't listen on localhost
Putting 127.0.0.1 instead of localhost doesn't work
Putting the external IP doesn't work

Uncommenting `Optional:` results in an error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.wg-easy.environment.Optional contains ["PORT=51821", "HOST=localhost"], which is an invalid type, it should be a string, number, or a null

```
Config modified like so:
```
services:
  wg-easy:
    environment:
      Optional:
      PORT: 51821
      HOST: 127.0.0.1
    #  - INSECURE=false

```
Produces no errors, and no changes in behavior. 
I am assuming that the changes to these parameters should affect what IP it listens on.

### Expected behavior

I should be able to change the ip it listens on. 

It would be even better if it will, as a sane default, setup the reverse proxy with a self-signed certificate. 

### Relevant log output

```shell

```

**Comment by kaaax0815** [comment]
when having something like this

```yaml
wg-easy:
    environment:
    #  Optional:
    #  - PORT=51821
      - HOST=127.0.0.1
    #  - INSECURE=false
```

I get the log `Listening on http://127.0.0.1:51821` indicating it to work
