### ISSUE TITLE
[Bug]: `wg-easy` returns "connection reset" on port 51821 despite healthy status and correct config

### ISSUE THREAD

**Issue by warioishere** [wg-easy/wg-easy#1916]
### Describe the bug

**Description:**

I'm trying to run `wg-easy` behind a local Nginx reverse proxy on the same host. Everything seems configured correctly, and the container reports a healthy status. However, I get a connection reset when accessing the configured HTTP port (`51821`), even locally via `curl`.

### Logs:

```
Migrating database...
====================================================
    wg-easy - https://github.com/wg-easy/wg-easy    
====================================================
| wg-easy:  v15.0.0                                |
| Node:     v22.16.0                               |
| Platform: linux                                  |
| Arch:     x64                                    |
====================================================
Migration complete
Starting WireGuard...
Starting Wireguard Interface wg0...
Saving Config...
Listening on http://0.0.0.0:51821
Config saved successfully.
...
Wireguard Interface wg0 started successfully.
Starting Cron Job...
Cron Job started successfully.
```

```
e7e9042caca0   ghcr.io/wg-easy/wg-easy:15   "docker-entrypoint.s…"   8 minutes ago   Up 8 minutes (healthy)   0.0.0.0:51820->51820/udp, [::]:51820->51820/udp, 0.0.0.0:51821->51821/tcp, [::]:51821->51821/tcp   wg-easy
```

Despite the message `Listening on http://0.0.0.0:51821`, the following request fails:

```bash
curl http://127.0.0.1:51821
# → curl: (56) Recv failure: Connection reset by peer
```

### `docker-compose.yml` (excerpt):

```yaml
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    environment:
      - PORT=51821
      - HOST=0.0.0.0
      - INSECURE=true
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg:
        ipv4_address: 10.8.0.2

networks:
  wg:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
```

### What I’ve verified:

* The container is healthy (`docker ps` shows `(healthy)`)
* The logs state the service is listening on `0.0.0.0:51821`
* Port 51821 is published and mapped to the host
* `curl` from the host returns a connection reset
* Nginx reverse proxy (`proxy_pass http://127.0.0.1:51821`) results in 502

### Environment:

* Host OS: Ubuntu 24.04.2
* Docker: latest stable
* wg-easy: `v15.0.0`

**Nginx Config**

```
server {
    server_name wireguard.yourdevice.ch;

    location / {
        proxy_pass http://127.0.0.1:51821;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/wireguard.yourdevice.ch/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/wireguard.yourdevice.ch/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = wireguard.yourdevice.ch) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name wireguard.yourdevice.ch;
    return 404; # managed by Certbot


}
```

Any Ideas what I am doing wrong?

### Expected behavior

The service should be accessible on port `51821` as per the logs and exposed ports.

**Comment by kaaax0815** [comment]
It could be that the subnet of your network collides with the one that WireGuard creates. try the one from the docker compose file

**Comment by mrgzi** [comment]
same issue

```
curl http://0.0.0.0:51821
curl: (56) Recv failure: Connection reset by peer
```

**Comment by mrgzi** [comment]
> It could be that the subnet of your network collides with the one that WireGuard creates. try the one from the docker compose file

You were right about the subnet of network but in the docker compose file didn't worked for me.

@warioishere I tried this and it worked;

```
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.8.1.2
        ipv6_address: fd00:8:1::2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    environment:
      - INIT_ENABLED=true
      - INIT_USERNAME=admin
      - INIT_PASSWORD=admin
      - INIT_HOST=your server adress
      - INIT_PORT=51820
      - INIT_DNS=1.1.1.1,8.8.8.8
      - INIT_IPV4_CIDR=10.8.0.0/24
      - INIT_IPV6_CIDR=fd00:8::/64
      - PORT=51821
      - HOST=0.0.0.0
      - INSECURE=true
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - ./wireguard-config:/etc/wireguard
      - /lib/modules:/lib/modules:ro

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.8.1.0/24
        - subnet: fd00:8:1::/64
```
