### ISSUE TITLE
[Bug]: v15 bug: set INSECURE=true give error when compose

### ISSUE THREAD

**Issue by Zygot** [wg-easy/wg-easy#1929]
### Describe the bug

Hello, 

When set INSECURE=true it give error when compose container

```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      Optional:
    #  - PORT=51821
    #  - HOST=0.0.0.0
      - INSECURE=true
```
 

### Expected behavior

Should accept

### Relevant log output

```shell
services.wg-easy.environment.optional contains ["INSECURE=true"], which is an invalid type, it should be a string, number, or a null
```

**Comment by ThibautPlg** [comment]
Remove the `Optional:` line. This is a comment, this should not be part of the compose.

```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
    # Optional:
    #  - PORT=51821
    #  - HOST=0.0.0.0
      - INSECURE=true
```
