### ISSUE TITLE
[Bug]: wg-easy fails with "RTNETLINK answers: Permission denied" on Synology DS224+

### ISSUE THREAD

**Issue by bobrom1** [wg-easy/wg-easy#1931]
### Describe the bug

WireGuard is trying to create the network interface wg0
The system (or container) denies it, because the necessary kernel-level permissions or support are missing

Log:
[#] ip link add wg0 type wireguard
RTNETLINK answers: Permission denied
[unhandledRejection] Error: Command failed: wg-quick up wg0

### Expected behavior

I expected the wg-easy container to successfully create the WireGuard interface (wg0) and start the VPN server without errors.

### Relevant log output

```shell

```

**Comment by kaaax0815** [comment]
please share your docker compose file or run command.

can you load the wireguard kernel module on the host? `modprobe wireguard`

**Comment by carlhansson** [comment]
I have this same problem, when running modprobe wireguard I get `modprobe: FATAL: Module wireguard not found.`

**Comment by carlhansson** [comment]
I have the same problem running on a Synology DS220+

My compose. took the one from the docs and just removed all the IPv6 stuff and changed the volumes (i have tested with the normal volumes also but it doesn't work either):
```yml
services:
  wg-easy:
    #environment:
    #  Optional:
    #  - PORT=51821
    #  - HOST=0.0.0.0
    #  - INSECURE=false

    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.42.42.42
    volumes:
      - /volume2/docker/wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  wg:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
```

Docker logs:
```
Migrating database...
====================================================
    wg-easy - https://github.com/wg-easy/wg-easy
====================================================
| wg-easy:  v15.0.0                                |
| Node:     v22.16.0                               |
| Platform: linux                                  |
| Arch:     x64                                    |
====================================================
Migration complete
Starting WireGuard...
Generating new Wireguard Keys...
$ wg genkey
Listening on http://0.0.0.0:51821
$ echo ***hidden*** | wg pubkey
New Wireguard Keys generated successfully.
Starting Wireguard Interface wg0...
Saving Config...
Config saved successfully.
$ wg-quick down wg0
$ wg-quick up wg0
[unhandledRejection] Error: Command failed: wg-quick up wg0
[#]
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip -6 address add fdcc:ad94:bacf:61a4::cafe:1/112 dev wg0
RTNETLINK answers: Permission denied
[#] ip link delete dev wg0

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 2,
  killed: false,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

The container is created and I can access the webui and create a setup and log in an all that. However the ui seems to be in the loading state as there is a loading animation in the list of clients (which should just be empty) and when trying to create a client or change anything in the config i get "Error: Server error" (see picture)

<img width="1198" alt="Image" src="https://github.com/user-attachments/assets/91242e7d-8687-4e09-97af-35aa7f1cd8db" />

**Comment by ManuProd** [comment]
Same here (DS220+ and same logs as above), no problem with v13 and v14 but "Server Error" on v15.

**Comment by kaaax0815** [comment]
Please try `ghcr.io/wg-easy/wg-easy:development` and set the env var `DISABLE_IPV6` to true. and see if that fixes the problem

**Comment by garanda21** [comment]
> Please try `ghcr.io/wg-easy/wg-easy:development` and set the env var `DISABLE_IPV6` to true. and see if that fixes the problem

Same error with:

```yml
sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

But works perfect with:

```yml
sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
```

```log
Migrating database...
====================================================
    wg-easy - https://github.com/wg-easy/wg-easy    
====================================================
| wg-easy:  v15.0.0                                |
| Node:     v22.16.0                               |
| Platform: linux                                  |
| Arch:     x64                                    |
====================================================
Migration complete
Warning: Disabling IPv6...
IPv6 Post Up hooks already disabled, skipping...
IPv6 Post Down hooks already disabled, skipping...
Starting WireGuard...
Starting Wireguard Interface wg0...
Saving Config...
Listening on http://0.0.0.0:51821
Config saved successfully.
$ wg-quick down wg0
$ wg-quick up wg0
Syncing Config...
$ wg syncconf wg0 <(wg-quick strip wg0)
Config synced successfully.
Wireguard Interface wg0 started successfully.
Starting Cron Job...
Cron Job started successfully.
```

Tested on a Synology 923+

**Comment by grigsby** [comment]
I was having the same problem on Debian 12. It seems to be caused by an issue with ipv6. Updating to ghcr.io/wg-easy/wg-easy:development and changing the following lines in my compose.yaml fixed the problem.

```
  networks:
    wg:
       ipv4_address: 10.42.42.4
#       ipv6_address: fdcc:ad94:bacf:61a3::2a  # CHANGE: Commented out ipv6 address
  sysctls:
     - net.ipv4.ip_forward=1
     - net.ipv4.conf.all.src_valid_mark=1
     - net.ipv6.conf.all.disable_ipv6=0    # CHANGE: Disable ipv6
     - net.ipv6.conf.all.forwarding=1
     - net.ipv6.conf.default.forwarding=1

```
The container starts up now!

**Comment by kaaax0815** [comment]
@grigsby could you post your full docker compose? so i can add it to the docs

**Comment by BobWs** [comment]
I'm running the previous version with docker macvlan network, can I still do that with this (15) upgraded version?
Could you please share some insight how to do the upgraded version with macvlan!
TIA

**Comment by BobWs** [comment]
Figured it out, it is working with mcvlan network!

Below my `docker-compose.yml` is someone is looking for a macvlan solution. (running on a Synology NAS within docker)

```
version: "3.8"
services:
  wireguard-server:
    image: ghcr.io/wg-easy/wg-easy:development
    container_name: wg-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    hostname: wg-server
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    mem_reservation: 128m
    volumes:
      - /volume1/docker/wireguard/server:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    environment:
      TZ: "Europe/Berlin"
      INSECURE: true
      DISABLE_IPV6: true
    restart: "always"
    mac_address: 02:47:c0:a8:b2:46
    networks:
      macvlan0:
        ipv4_address: 192.168.178.10     
      
networks:
  macvlan0:
    external: true
```

**Comment by grigsby** [comment]
> [@grigsby](https://github.com/grigsby) could you post your full docker compose? so i can add it to the docs

Of course!

```

volumes:
  etc_wireguard:

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:development
    container_name: wg-easy
    hostname: wg-easy
    environment:
#      Optional:
      - PORT=51821
      - HOST=0.0.0.0
      - INSECURE=false
    networks:
      wg:
        ipv4_address: 10.42.42.4
#        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

networks:
  wg:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
#        - subnet: fdcc:ad94:bacf:61a3::/64
```

**Comment by andreatondo** [comment]
Unfortunately the same is still not working for me on QNAP-TS-251

```
Migrating database...
====================================================
    wg-easy - https://github.com/wg-easy/wg-easy
====================================================
| wg-easy:  v15.0.0                                |
| Node:     v22.16.0                               |
| Platform: linux                                  |
| Arch:     x64                                    |
====================================================
Migration complete
Starting WireGuard...
Starting Wireguard Interface wg0...
Saving Config...
Listening on http://0.0.0.0:51821
Config saved successfully.
$ wg-quick down wg0
$ wg-quick up wg0
[unhandledRejection] Error: Command failed: wg-quick up wg0
[#] ip link add dev wg0 type wireguard
[#]
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip -6 address add fdcc:ad94:bacf:61a4::cafe:1/112 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -s fdcc:ad94:bacf:61a4::cafe:0/112 -o eth0 -j MASQUERADE; ip6tables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -A FORWARD -o wg0 -j ACCEPT;
ip6tables v1.8.11 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
[#] ip link delete dev wg0

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 3,
  killed: false,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

**Comment by grigsby** [comment]
> Unfortunately the same is still not working for me on QNAP-TS-251
> 
> ```
> ...
> ip6tables v1.8.11 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
> Perhaps ip6tables or your kernel needs to be upgraded.
>  ```


I'm not sure this is the same issue. To me, this error looks like either your kernel or iptables package isn't configured to handle ipv6 rules.

Does it work if you disable the ipv6-related wg-easy docker container variables?

Can you manually create ipv6 rules from the command line (i.e. outside of docker) using iptables?

**Comment by BobWs** [comment]
@andreatondo you need to disable ipv6, I was having the same error message in my logs trying to install it on my Synology, and after disabling ipv6 everything started working and no more errors.

**Comment by andreatondo** [comment]
You are correct, I shared tje output from one of the multiple attempts and the error was different. 
Unfortunately even removing all the IPv6 configuration I'm getting the same failure of the above thread (`RTNETLINK answers: Permission denied`). This only happens on v15, while I'm able to properly run v14.

Output:
```
Migrating database...
====================================================
    wg-easy - https://github.com/wg-easy/wg-easy
====================================================
| wg-easy:  v15.0.0                                |
| Node:     v22.16.0                               |
| Platform: linux                                  |
| Arch:     x64                                    |
====================================================
Migration complete
Starting WireGuard...
Starting Wireguard Interface wg0...
Saving Config...
Listening on http://0.0.0.0:51821
Config saved successfully.
$ wg-quick down wg0
$ wg-quick up wg0
[unhandledRejection] Error: Command failed: wg-quick up wg0
[#] ip link add dev wg0 type wireguard
[#]
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip -6 address add fdcc:ad94:bacf:61a4::cafe:1/112 dev wg0
RTNETLINK answers: Permission denied
[#] ip link delete dev wg0

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:351:12) {
  code: 2,
  killed: false,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

Docker compose file:
```
volumes:
  etc_wireguard:

services:
  wg-easy:
    #  Optional:
    #  - PORT=51821
    #  - HOST=0.0.0.0
    #  - INSECURE=false
    image: ghcr.io/wg-easy/wg-easy:development
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 192.168.11.211
    mac_address: 02:42:AC:11:00:02
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  wg:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.11.0/24
```

**Comment by kaaax0815** [comment]
@andreatondo try the `DISABLE_IPV6` env var as described here https://wg-easy.github.io/wg-easy/development/advanced/config/optional-config/

**Comment by andreatondo** [comment]
@kaaax0815 Thank you, I tried that as well, still the same error even if the IPv3 seems to have been disabled
```
Migration complete
Warning: Disabling IPv6...
Disabling IPv6 in Post Up hooks...
Disabling IPv6 in Post Down hooks...
Starting WireGuard...
Starting Wireguard Interface wg0...
Saving Config...
Listening on http://0.0.0.0:51821
Config saved successfully.
$ wg-quick down wg0
$ wg-quick up wg0
[unhandledRejection] Error: Command failed: wg-quick up wg0
[#] ip link add dev wg0 type wireguard
[#]
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip -6 address add fdcc:ad94:bacf:61a4::cafe:1/112 dev wg0
RTNETLINK answers: Permission denied
[#] ip link delete dev wg0

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:414:12)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:351:12) {
  code: 2,
  killed: false,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

**Comment by andreatondo** [comment]
Ok, I found my mistake, I was missing 
```
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
```
Adding that + the `DISABLE_IPV6` works! Thanks!

**Comment by kaaax0815** [comment]
@andreatondo could you try if the disable ipv6 env var is even needed?

**Comment by andreatondo** [comment]
@kaaax0815 You are right... it's not needed, I was sure to have tested this configuration yesterday, but apparently I might have messed up with it!
To confirm this is my working compose file on QNAP using macvlan
```
volumes:
  etc_wireguard:

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      macvlan-lan:
        ipv4_address: 192.168.11.211
    mac_address: 02:42:AC:11:00:02
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0

networks:
  macvlan-lan:
    external: true
```

**Comment by BobWs** [comment]
@kaaax0815 
also tested `version 15` without the `env: DISABLE_IPV6=true` and for me it is also working!
Below my working `docker-compose.yml` on a Synology NAS.

```
version: "3.8"
services:
  wireguard-server:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    hostname: wg-server
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    mem_reservation: 128m
    volumes:
      - /volume1/docker/wireguard/server:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      TZ: "Europe/Berlin"
      INSECURE: false
    restart: "always"
    mac_address: 02:47:c0:a8:b2:46
    networks:
      macvlan0:
        ipv4_address: 192.168.178.10     
      
networks:
  macvlan0:
    external: true
```
