### ISSUE TITLE
[Bug]: Can't bind custom IPs / ranges anymore in v15

### ISSUE THREAD

**Issue by Mavrag** [wg-easy/wg-easy#1974]
### Describe the bug

Hi 👋 — thank you for your work on this awesome project. I’ve been using `wg-easy` for a while and really appreciate the improvements in v15.

However, after updating, I’m hitting what looks like a **regression** — my previous setup with **custom subnets and multiple containers** no longer works as expected.

---

### 📋 Old Working Config (pre-v15)

I used to run **two separate `wg-easy` containers** using different subnets:

```yaml
services:
  wg-easy:
    container_name: wg-easy-2
    image: ghcr.io/wg-easy/wg-easy
    environment:
      - LANG=en
      - WG_HOST=*redacted*
      - PASSWORD_HASH=*redacted*
      - PORT=52821
      - WG_PORT=52820
      - WG_DEFAULT_ADDRESS=10.9.0.x
    volumes:
      - ./data:/etc/wireguard
    ports:
      - 52820:52820/udp
      - 52821:52821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
```

- One used subnet `10.8.0.0/24`
- The other used `10.9.0.0/24`

Both worked fine and allowed for multiple isolated WireGuard VPNs on the same host.

---

### ❌ Current Config in v15 (Fails to Start Properly)

After updating to v15 and trying to use custom static IPs and subnets, the container launches but:

- The Web UI is inaccessible
- Nothing useful shows up in the logs
- WireGuard tunnels fail to function unless I revert to defaults

Example config that fails:

```yaml
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.8.0.2
#        ipv6_address: fdcc:ad94:bacf:61a3::2a
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    restart: unless-stopped

networks:
  wg:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.8.0.0/24
#        - subnet: fdcc:ad94:bacf:61a3::/64
```

---

### 🧪 Troubleshooting Attempted

I’ve tried:
- Disabling IPv6
- Changing subnets

But nothing helps unless I fall back to default Docker bridge network settings.

---

### 💬 Questions

1. Why does the app silently fail when using custom static IPs or custom subnets?
2. Is IPv6 required in v15? Can it be safely disabled?
3. What’s the proper way to isolate multiple `wg-easy` containers with different VPN ranges now?

I’d love to keep using v15 with the new features, but the loss of customizability is breaking my setup. Happy to provide full logs, test config changes, or help debug if needed!

Thanks again 🙏

### Expected behavior

Allow setting custom bridge subnets and static IPs per container

Let the HOST env var work for config generation and peer connection, but not force binding to that IP on the Docker host

### Relevant log output

```shell
Migrating database...
====================================================
    wg-easy - https://github.com/wg-easy/wg-easy
====================================================
| wg-easy:  v15.0.0                                |
| Node:     v22.16.0                               |
| Platform: linux                                  |
| Arch:     x64                                    |
====================================================
Migration complete
Starting WireGuard...
Starting Wireguard Interface wg0...
Saving Config...
Listening on http://0.0.0.0:51821
Config saved successfully.
$ wg-quick down wg0
$ wg-quick up wg0
Syncing Config...
$ wg syncconf wg0 <(wg-quick strip wg0)
Config synced successfully.
Wireguard Interface wg0 started successfully.
Starting Cron Job...
Cron Job started successfully.
```

**Comment by Mavrag** [comment]
Hey again — quick update:

I found that the WireGuard CIDR (`10.8.0.0/24` by default) can now be changed directly from the **Admin Panel → Interface tab**, which is great 🎉

But now I’m wondering: what’s the purpose of the `networks` section in the `docker-compose.yml`?

```yaml
networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
```

And this part under the service:

```yaml
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
```

- What are these IPs for (especially `10.42.42.42`)?
- Are they required for proper operation?
- Should we still be customizing Docker network subnets, or is that unrelated to the WireGuard configuration now?

Just want to understand if this is internal Docker plumbing, or something important for multi-container setups. Thanks.
