### ISSUE TITLE
[Bug]: Imported clients cannot be edited in v15

### ISSUE THREAD

**Issue by BeansIsFat** [wg-easy/wg-easy#1985]
### Describe the bug

On a fresh install of v15 with clients imported from a working v14 installation, no edits are possible to the imported clients. When clicking save the popup message says:

```
Error 
Server Error
```

### Expected behavior

Imported clients should be editable.

### Relevant log output

```shell

```

**Comment by kaaax0815** [comment]
please provide the relevant config files and logs

**Comment by BeansIsFat** [comment]
Here's the error from the log when attempting to edit an imported client:

```
[request error] [unhandled] [POST] http://_redacted_/api/client/2
 H3Error: IPv4 address is not within the CIDR range
    at file:///app/server/chunks/nitro/nitro.mjs:6273:15
    ... 5 lines matching cause stack trace ...
    at async Server.toNodeHandle (file:///app/server/chunks/nitro/nitro.mjs:2705:7) {
  cause: Error: IPv4 address is not within the CIDR range
      at file:///app/server/chunks/nitro/nitro.mjs:6273:15
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async LibSQLSession.transaction (file:///app/server/node_modules/drizzle-orm/libsql/session.js:65:22)
      at async file:///app/server/chunks/routes/api/client/index.post.mjs:45:5
      at async Object.handler (file:///app/server/chunks/nitro/nitro.mjs:6986:22)
      at async Object.handler (file:///app/server/chunks/nitro/nitro.mjs:2434:19)
      at async Server.toNodeHandle (file:///app/server/chunks/nitro/nitro.mjs:2705:7),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```

Here's my compose.yaml file:

```
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      - INSECURE=true

    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.2.0.100
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "80:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
```

And here's the exported wg0.json from my v14 installation

```
{
  "server": {
    "privateKey": "_redacted_",
    "publicKey": "jtJuMsiTUHWNzEPWqxMC6ZToBk89nSXbV2DLZT3IUAc=",
    "address": "10.8.0.1"
  },
  "clients": {
    "817e2236-e2b3-49e2-b3c0-943de9dcbe59": {
      "id": "817e2236-e2b3-49e2-b3c0-943de9dcbe59",
      "name": "Laptop",
      "address": "10.6.0.2",
      "privateKey": "_redacted_",
      "publicKey": "0WYDU6PPIJ/SQALxluj248lOTrGF1xIRHv4S76UCn1M=",
      "preSharedKey": "_redacted_",
      "createdAt": "2025-05-24T21:55:39.976Z",
      "updatedAt": "2025-05-24T21:55:39.976Z",
      "enabled": true
    }
  }
}
```
