### ISSUE TITLE
AllowedIPs seems not working

### ISSUE THREAD

**Issue by hanbo1990** [wg-easy/wg-easy#363]
**Describe the bug**
Setting `WG_ALLOWED_IPS` in the docker-compose does not generate right allowed IPs.
```
version: "3"
services:
  wg-easy:
    environment:
      - WG_HOST=localhost
      - WG_DEFAULT_ADDRESS=10.8.1.x
      - PASSWORD=123456
      - WG_ALLOWED_IPS=192.168.1.0/24, 10.8.1.0/24
    image: weejewel/wg-easy:latest
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

The generated wg0.conf only contain below allowed ip
```
[Peer]
PublicKey = xxxxxxxx
PresharedKey = xxxx
AllowedIPs = 10.8.1.2/32
```

Am I missing something?
