### ISSUE TITLE
Cannot access other Docker services

### ISSUE THREAD

**Issue by zero-thermo** [wg-easy/wg-easy#397]
**Describe the bug**
Client successfully connects to wg-easy server, and can access the wg-easy Web UI via `http://10.20.20.1:51821`. However, client cannot access any other Docker services using `http://10.20.20.1:PORT`. All containers are part of the same `nginx_proxy` Docker network.

I am switching the server from WireGuard installed on the host to this wg-easy Docker setup. Access to other Docker containers works fine when connected to WireGuard host install. Could any of that be interfering with wg-easy, and what should I change/undo?

**To Reproduce**
1. Setup wg-easy via docker-compose on Debian GNU/Linux 11 (bullseye) server
2. Download `wireguard.conf` to client and connect to wg-easy server
3. Accessing other Docker containers via `http://10.20.20.1:PORT` does not work, but accessing the wg-easy Web UI at `http://10.20.20.1:51821` is fine
4. When connecting to WireGuard host install, access to other containers works

**Expected behavior**
Expected access to other Docker containers just like accessing the wg-easy Web UI

<details>
  <summary>docker-compose.yaml</summary>
  
```
version: "3.7"
services:
  wg-easy:
    environment:
      # Required:
      # Change this to your host's public address
      - WG_HOST=<PUBLIC IP>

      # Optional:
      - PASSWORD=<PASSWORD>
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.20.20.x
      - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=10.20.20.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  default:
    external:
      name: nginx_proxy
```
</details>
