### ISSUE TITLE
[feature request] PASSWORD_FILE instead of PASSWORD

### ISSUE THREAD

**Issue by czocher** [wg-easy/wg-easy#401]
**Describe the feature**
Add the possibility to load the `PASSWORD` from a mounted `docker` or `podman` secret.

Currently the only way to set the `PASSWORD` is to define it as a environmental variable. This is not considered secure, secrets should (and by default often are) defined as files mounted in the running container.

`wg-easy` should still allow for the `PASSWORD` environmental variable to be defined, but should also have the possibility to define a `PASSWORD_FILE` environmental variable, which would hold the path to the mounted file containing the secret. If both are defined it should either error out or prefer the `PASSWORD_FILE` as the more secure of the two.

**Comment by m4heshd** [comment]
I'd love this with hashed passwords. You can use a `.env` file for the moment BTW.

**Comment by Czocher** [comment]
@m4heshd I didn't notice any indication of support for `.env` files in the documentation, is there some hidden option to load them? Adding this information to the `README.md` file would be a good idea as well.

**Comment by m4heshd** [comment]
I meant with a compose file. Here's how I'm doing it at the moment.

```yaml

```

**Comment by m4heshd** [comment]
I meant with a compose file. Here's how I'm doing it at the moment.

**docker-compose.yaml:**
```yaml
version: '3'

services:
  wg-easy:
    image: weejewel/wg-easy:7
    container_name: wg-easy
    restart: unless-stopped
    environment:
      WG_HOST: "${SERVER_PUB_IP}"
      PASSWORD: "${ACCESS_PW}"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "51820:51820/udp"
      - "5862:51821"
    volumes:
      - ./wireguard/data:/etc/wireguard
```

.env
```sh
SERVER_PUB_IP=xxx.xxx.xxx.xxx
ACCESS_PASS=MyPass
```

**Then run:**
```sh
docker compose --env-file .env up --detach
```

`.env` file actually gets automatically detected if it's in the same dir as the compose file. But added the arg just in case.
