### ISSUE TITLE
Client Configuration file format is wrong

### ISSUE THREAD

**Issue by XxAcielxX** [wg-easy/wg-easy#417]
Hello,

I'm using your wg-easy docker container, when I click the download button to get the clients' config, the file format comes with a `.txt`. Which is not the format accepted by WireGuard Software/App. The correct file format should be `.conf`.

Kindly look into to this.

**Comment by eandersons** [comment]
For me client configuration file is downloaded with the extension `.conf`. At least in Firefox (Developer Edition) and Chromium.

Additional information (like operating system, browser, possibly `docker run` command or `docker-compose.yml` that was used to create the WireGuard Easy container, reverse-proxy in use (if any) and its configuration) could help others to possibly recreate the issue and spot the problem that is causing to download client configuration with the extension `.txt` instead of `.config`.

**Comment by XxAcielxX** [comment]
Using Firefox on Android Phone.
![Screenshot_20221115-151259~2](https://user-images.githubusercontent.com/21063358/201893945-1e2c1472-7115-4bb5-a2b4-83328a4c0f5a.jpg)


docker-compose
```
...
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      adnio:
        ipv4_address: ${SUBNET}${WG_EASY_IP}
    ports:
      - ${WG_PORT}:51820/udp
    environment:
      - PASSWORD=${WG_EASY_PASSWD}
      - WG_HOST=${WG_SUBDOMAIN}
      - WG_ALLOWED_IPS=${WG_ALLOWED}
      - WG_DEFAULT_ADDRESS=${WG_SUBNET}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_DNS=${SUBNET}${PIHOLE_IP}
    volumes:
      - ${APP_CONF}/wg-easy:/etc/wireguard
    restart: unless-stopped
```

Using LSIO SWAG as Reverse-Proxy. And I access wg-easy as `https://wg.mydomain.ltd`
