### ISSUE TITLE
SSL for gui

### ISSUE THREAD

**Issue by MiRen76** [wg-easy/wg-easy#425]
Hi, I have a question how to integrate SSL accessing the GUI. Ist there a way to configure IT?

Thx.

**Comment by eandersons** [comment]
There is a Wiki page [Using WireGuard Easy with nginx SSL](/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL) regarding this which is listed in the section [Common Use Cases](/WeeJeWel/wg-easy#common-use-cases).

If you are not using Nginx, the basic idea is the same - use reverse proxy and configure SSL against it with Certbot or other means.

**Comment by MiRen76** [comment]
I am using traefik and I am not able to get the right configuration for the lables. Any ideas are welcome. Thx

**Comment by MiRen76** [comment]
Is there any possibility to keep the web gui local with SSL?

**Comment by eandersons** [comment]
> I am using traefik and I am not able to get the right configuration for the lables. Any ideas are welcome. Thx

Did you take a look at the article [Let's Encrypt](https://doc.traefik.io/traefik/https/acme/) in Traefik's documentation?

> Is there any possibility to keep the web gui local with SSL?

As far as I know, self-signed certificates have to be used for local only use. Or a domain can be configured with SSL and then access to it could be granted only from internal IP addresses.

**Comment by gjdoornink** [comment]
I am using this docker compose file which enables access to wg-easy through https://myhost.example.org/wg-easy/
The value of environment variables below have to be changed, of course.

```
version: "3.8"

services:

  wg-easy:
    image: weejewel/wg-easy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - "TZ=..."
      - "WG_HOST=..."
      - "PASSWORD=..."
      - "WG_PORT=51820"
      - "WG_DEFAULT_ADDRESS=..."
      - "WG_DEFAULT_DNS=..."
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    volumes:
      - "/data/docker/wg-easy:/etc/wireguard"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"
      - "traefik.http.routers.wg-easy-pathprefix-http.entrypoints=web"
      - "traefik.http.routers.wg-easy-pathprefix-http.rule=PathPrefix(`/wg-easy`)"
      - "traefik.http.routers.wg-easy-pathprefix-http.service=wg-easy"
      - "traefik.http.routers.wg-easy-pathprefix-http.middlewares=wg-easy-redirect-https"
      - "traefik.http.routers.wg-easy-pathprefix-https.entrypoints=websecure"
      - "traefik.http.routers.wg-easy-pathprefix-https.tls=true"
      - "traefik.http.routers.wg-easy-pathprefix-https.rule=PathPrefix(`/wg-easy`) || HeadersRegexp(`Referer`, `https://[^/]+/wg-easy/`)"
      - "traefik.http.routers.wg-easy-pathprefix-https.service=wg-easy"
      - "traefik.http.routers.wg-easy-pathprefix-https.middlewares=wg-easy-stripprefix"
      - "traefik.http.middlewares.wg-easy-stripprefix.stripprefix.prefixes=/wg-easy"
      - "traefik.http.middlewares.wg-easy-stripprefix.stripprefix.forceslash=true"
      - "traefik.http.middlewares.wg-easy-redirect-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.wg-easy-redirect-https.redirectscheme.port=443"

networks:
  traefik:
    external: true
```

**Comment by Privatecoder** [comment]
another approach using `nginx-proxy` and its `nginx-proxy-acme` helper – without docker-compose:

```
docker run --detach \
	--name nginx-proxy \
	--publish 80:80 \
	--publish 443:443 \
	--volume certs:/etc/nginx/certs \
	--volume vhost:/etc/nginx/vhost.d \
	--volume html:/usr/share/nginx/html \
	--volume /var/run/docker.sock:/tmp/docker.sock:ro \
	nginxproxy/nginx-proxy
```
```
 docker run --detach \
	--name nginx-proxy-acme \
	--volumes-from nginx-proxy \
	--volume /var/run/docker.sock:/var/run/docker.sock:ro \
	--volume acme:/etc/acme.sh \
	--env "DEFAULT_EMAIL=admin@example.com" \
	nginxproxy/acme-companion
```
```
docker run -d \
	--name=wg-easy \
	-e WG_HOST=wgeasy.example.com \
	-e PASSWORD=YourAdminSecret \
	-e VIRTUAL_HOST=wgeasy.example.com \
	-e LETSENCRYPT_HOST=wgeasy.example.com \
    -e VIRTUAL_PORT=51821 \
	-v ~/.wg-easy:/etc/wireguard \
	-p 51820:51820/udp \
	--cap-add=NET_ADMIN \
	--cap-add=SYS_MODULE \
	--sysctl="net.ipv4.conf.all.src_valid_mark=1" \
	--sysctl="net.ipv4.ip_forward=1" \
	--restart unless-stopped \
	weejewel/wg-easy
```

**Comment by x066it** [comment]
I prefer using caddy with docker-compose:

```yaml
caddy:
    image: caddy:2.6.1-alpine
    container_name: wg-caddy
    restart: unless-stopped
    command: caddy reverse-proxy --from https://wg.host.com:443 --to http://wg-easy:51821
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ~/.caddy:/data
```
