### ISSUE TITLE
Config issues

### ISSUE THREAD

**Issue by dm9tr0** [wg-easy/wg-easy#460]
1. If you use custom port instead of 51820 - generated client config from UI will have anyway 51820, need to fix manually for each client.
2. I setup host path for config as '/opt/wireguard-easy/config' folder created when container running, but always empty, have no idea where config stored.

```
---
version: "2.1"
services:
  wireguard:
    image: weejewel/wg-easy
    container_name: wireguard_easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST=<my_IP>
      - PASSWORD=<my_pass>
    volumes:
      - /opt/wireguard-easy/config:/.wg-easy
    ports:
      - 4111:51820/udp
      - 41112:51821/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: always
```
