### ISSUE TITLE
Nginx proxy manager

### ISSUE THREAD

**Issue by RobotsAreCrazy** [wg-easy/wg-easy#499]
Hi, would it be difficult to use nginx proxy manager in place of nginx and if so how and what needs to be changed?

Thankyou

**Comment by eandersons** [comment]
Just took a look at what Nginx Proxy Manager is, and it is fairly easy - WireGuard Easy container can be started with the default `docker run` command or `docker-compose.yml`, then in Nginx Proxy Manager a new proxy host should be added that points a domain (for example: wg-easy.example.org) to the server's local IP address (for example: 192.168.1.2) and port 51821.

A bit more advanced and recommended approach is to create a custom Docker network (with [`docker network create`](https://docs.docker.com/engine/reference/commandline/network_create/) or in [Compose file](https://docs.docker.com/compose/compose-file/compose-file-v3/#networks)), connect (with [`docker network connect`](https://docs.docker.com/engine/reference/commandline/network_connect/) or in [Compose file](
https://docs.docker.com/compose/compose-file/compose-file-v3/#networks)) WireGuard Easy and Nginx Proxy Manager containers to it, and then in Nginx Proxy Manager `wg-easy` can be used as the target address. In such case there is no need to map port 51821 to host's network.

By the way, this question belongs in [Discussions](/WeeJeWel/wg-easy/discussions).

**Comment by RobotsAreCrazy** [comment]
so what needs changing in the compose file?

from here https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL

doesn't look too easy, especially when you have to then run
Then run once:

`$ docker exec -it nginx /bin/sh

cp wg-easy.conf /etc/nginx/conf.d/.

$ certbot --nginx --non-interactive --agree-tos -m webmaster@google.com -d ⚠️wg-easy.myhomelab.com
$ nginx -s reload
$ exit`


maybe I would just be better off doing everything your way, but guessing i lose the nginx proxy manager web gui etc

**Comment by RobotsAreCrazy** [comment]
made some alts.....hope this looks ok not an expert had to piece this altogether


```
version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=random.com

      # ⚠️ Change the Web UI Password:
      - PASSWORD=randompasword
      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    networks:
      - backend         # internal communications
    ipv4_address: 10.8.1.2
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    networks:
      - backend       # internal communications
      - npm_proxynet  # external communications
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80/tcp' # Public HTTP Port
      - '443:443/tcp' # Public HTTPS Port
      - '81:81/tcp' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - ~/.proxy/data:/data
      - ~/.proxy/letsencrypt:/etc/letsencrypt

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      # ⚠️ Change the Web UI Password:
      - WEBPASSWORD=randompassword
    volumes:
      - '~/.pihole/etc-pihole:/etc/pihole'
      - './.pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: 10.8.1.3

networks:

  backend:
    ipam:
      config:
        - subnet: 10.8.1.0/24
    driver: bridge
  npm_proxynet:
    external: true

```

**Comment by RobotsAreCrazy** [comment]
> Just took a look at what Nginx Proxy Manager is, and it is fairly easy - WireGuard Easy container can be started with the default `docker run` command or `docker-compose.yml`, then in Nginx Proxy Manager a new proxy host should be added that points a domain (for example: wg-easy.example.org) to the server's local IP address (for example: 192.168.1.2) and port 51821.
> At least this is what worked for me on a Linux (Debian) machine.
> 
> A bit more advanced and [recommended](https://nginxproxymanager.com/advanced-config/#best-practice-use-a-docker-network) approach is to create a custom Docker network (with [`docker network create`](https://docs.docker.com/engine/reference/commandline/network_create/) or in [Compose file](https://docs.docker.com/compose/compose-file/compose-file-v3/#networks)), connect (with [`docker network connect`](https://docs.docker.com/engine/reference/commandline/network_connect/) or in [Compose file](
> https://docs.docker.com/compose/compose-file/compose-file-v3/#networks)) WireGuard Easy and Nginx Proxy Manager containers to it, and then in Nginx Proxy Manager `wg-easy` can be used as the target address. In such case there is no need to map the port 51821 to host's network.
> 
> By the way, this question belongs in [Discussions](/WeeJeWel/wg-easy/discussions).

Hi, can you tell me if what I have in the updated docker-compose will work or if any corrections are needed could you point me in the direction of fixing it please?

**Comment by eandersons** [comment]
Did you try out if the `compose.yaml` you came up with works?
If it works, then I guess it is fine, especially if those will be only services, although there are some things to point at.

Default `docker-compose.yml` of both Nginx Proxy Manager and WireGuard Easy should work, as I described earlier.

The recommended approach would be to use a common network that joins Nginx Proxy Manager and WireGuard Easy:

1. `nginx-proxy-manager/compose.yaml` (this stack must be started first):

   ```yaml
   version: '3.9'
 
   networks:
     wg-easy:
     # Define more service specific networks here if needed

   services:
     app:
       image: jc21/nginx-proxy-manager:latest
       networks:
         - default
         - wg-easy
         # Additional networks defined in top level `networks` should be added here as well
       ports:
         # These ports are in format <host-port>:<container-port>
         - '80:80'  # Public HTTP Port
         - '81:81'  # Admin Web Port
         - '443:443'  # Public HTTPS Port
       restart: unless-stopped
       volumes:
         - ./data:/data
         - ./letsencrypt:/etc/letsencrypt
 
   ```

2. `wg-easy/compose.yaml` (must be started after Nginx Proxy Manager's stack is created):

   ```yaml
   version: '3.9'

   networks:
     nginx-proxy-manager_wg-easy:
       external: true

   services:
     wg-easy:
       cap_add:
         - NET_ADMIN
         - SYS_MODULE
       environment:
         # ⚠️ Required:
         # Change this to your host's public address
         - WG_HOST=wg-easy.local
         # Optional:
         - PASSWORD=foobar123
       image: weejewel/wg-easy
       networks:
         - default
         - nginx-proxy-manager_wg-easy
       ports:
         - `51820:51820/udp`
       restart: unless-stopped
       sysctls:
         - net.ipv4.ip_forward=1
         - net.ipv4.conf.all.src_valid_mark=1
       volumes:
         - .:/etc/wireguard

   ```

Note that common network's name in WireGuard Easy's Compose file (`nginx-proxy-manager_wg-easy`) is prefixed with the stack name of Nginx Proxy Manager and underscore (`nginx-proxy-manager_`; by default it is the name of the directory where Compose file is located).

When both stacks are up and running, then in Nginx Proxy Manager's user interface proxy must be pointed to the WireGuard Easy service (`wg-easy`) and its admin interface's port.
![image](https://user-images.githubusercontent.com/9976861/221517116-1f1f2edc-3720-48d4-9c3e-2675d4145c49.png)

**Comment by RobotsAreCrazy** [comment]
> Did you try out if the `compose.yaml` you came up with works?
> If it works, then I guess it is fine, especially if those will be only services, although there are some things to point at.
> 
> Default `docker-compose.yml` of both Nginx Proxy Manager and WireGuard Easy should work, as I described earlier.
> 
> The recommended approach would be to use a common network that joins Nginx Proxy Manager and WireGuard Easy:
> 
> 1. `nginx-proxy-manager/compose.yaml` (this stack must be started first):
> 
>    ```yaml
>    version: '3.9'
>  
>    networks:
>      wg-easy:
>      # Define more service specific networks here if needed
> 
>    services:
>      app:
>        image: jc21/nginx-proxy-manager:latest
>        networks:
>          - default
>          - wg-easy
>          # Additional networks defined in top level `networks` should be added here as well
>        ports:
>          # These ports are in format <host-port>:<container-port>
>          - '80:80'  # Public HTTP Port
>          - '81:81'  # Admin Web Port
>          - '443:443'  # Public HTTPS Port
>        restart: unless-stopped
>        volumes:
>          - ./data:/data
>          - ./letsencrypt:/etc/letsencrypt
>  
>    ```
> 
> 2. `wg-easy/compose.yaml` (must be started after Nginx Proxy Manager's stack is created):
> 
>    ```yaml
>    version: '3.9'
> 
>    networks:
>      nginx-proxy-manager_wg-easy:
>        external: true
> 
>    services:
>      wg-easy:
>        cap_add:
>          - NET_ADMIN
>          - SYS_MODULE
>        environment:
>          # ⚠️ Required:
>          # Change this to your host's public address
>          - WG_HOST=wg-easy.local
>          # Optional:
>          - PASSWORD=foobar123
>        image: weejewel/wg-easy
>        networks:
>          - default
>          - nginx-proxy-manager_wg-easy
>        ports:
>          - `51820:51820/udp`
>        restart: unless-stopped
>        sysctls:
>          - net.ipv4.ip_forward=1
>          - net.ipv4.conf.all.src_valid_mark=1
>        volumes:
>          - .:/etc/wireguard
> 
>    ```
> 
> Note that common network's name in WireGuard Easy's Compose file (`nginx-proxy-manager_wg-easy`) is prefixed with the stack name of Nginx Proxy Manager and underscore (`nginx-proxy-manager_`; by default it is the name of the directory where Compose file is located).
> 
> When both stacks are up and running, then in Nginx Proxy Manager's user interface proxy must be pointed to the WireGuard Easy service (`wg-easy`) and its admin interface's port.
> ![image](https://user-images.githubusercontent.com/9976861/221517116-1f1f2edc-3720-48d4-9c3e-2675d4145c49.png)
> 

Tbh I've not tried it yet as I was waiting to get feedback if it looked like it could work are you saying I need to swap nginx and wg-easy in the compose file?

**Comment by eandersons** [comment]
No, the network `nginx-proxy-manager_wg-easy` is the one that links together Nginx Proxy Manager and WireGuard Easy. The network `default` is project specific (after running `docker compose up` for each server actually two different Docker networks will be created - [`nginx-proxy-manager_default` and `wg-easy_default`](https://docs.docker.com/compose/networking/)).
When a Docker stack is created with Compose, then by default name of every component (container, network, volume) will be prefixed with the project name which by default is the name of the directory where the Compose file resides [if not specified otherwise](https://docs.docker.com/engine/reference/commandline/compose/#use--p-to-specify-a-project-name). Therefore in Nginx Proxy Manager Compose file simply `wg-easy` is used, but in WireGuard Easy Compose file `nginx-proxy-manager_wg-easy` - it has to be referenced by the full name as this network is external to the WireGuard Easy stack.

**Comment by RobotsAreCrazy** [comment]
> No, the network `nginx-proxy-manager_wg-easy` is the one that links together Nginx Proxy Manager and WireGuard Easy. The network `default` is project specific (after running `docker compose up` for each server actually two different Docker networks will be created - [`nginx-proxy-manager_default` and `wg-easy_default`](https://docs.docker.com/compose/networking/)).
> When a Docker stack is created with Compose, then by default name of every component (container, network, volume) will be prefixed with the project name which by default is the name of the directory where the Compose file resides [if not specified otherwise](https://docs.docker.com/engine/reference/commandline/compose/#use--p-to-specify-a-project-name). Therefore in Nginx Proxy Manager Compose file simply `wg-easy` is used, but in WireGuard Easy Compose file `nginx-proxy-manager_wg-easy` - it has to be referenced by the full name as this network is external to the WireGuard Easy stack.

So if I wanted to do pinhole and portainer I would need to add nginx proxy manager_wg-easy network to each compose file?

**Comment by eandersons** [comment]
Theoretically yes. In that case you could just use the network `nginx-proxy-manager_default`.

I would create a separate linking network for each server though.

**Comment by RobotsAreCrazy** [comment]
> Theoretically yes. In that case you could just use the network `nginx-proxy-manager_default`.
> 
> I would create a separate linking network for each server though.

Can you give me an example of that please?

**Comment by eandersons** [comment]
Example is already available in https://github.com/WeeJeWel/wg-easy/issues/499#issuecomment-1445952651.

**Comment by RobotsAreCrazy** [comment]
> Example is already available in https://github.com/WeeJeWel/wg-easy/issues/499#issuecomment-1445952651.

So in another compose file for every service I would like to connect to it's network, I would define nginx network_wg-easy as an external network in that compose file?

Just trying to wrap my head around it all before I put this into physical use.

**Comment by senseysensor** [comment]
well, let me show example how I managed to configure this.

docker-compose.yml:
```yaml
services:
  wg_easy:
    environment:
      - WG_HOST=my.domain.com
      - PASSWORD_HASH=...
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - /home/user/wg_volume:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - default

  nginx:
    build: ./nginx
    container_name: wg-easy-nginx
    hostname: nginx
    environment:
      - VIRTUAL_HOST=my.domain.com
      - LETSENCRYPT_HOST=my.domain.com
      - LETSENCRYPT_EMAIL=admin@my.domain.com
    restart: unless-stopped
    depends_on:
      - wg_easy
    networks:
      - proxy-tier
      - default

  proxy:
    image: nginxproxy/nginx-proxy:alpine
    restart: always
    ports:
      - 8082:80
      - 8443:443
    labels:
      com.github.nginx-proxy.docker-gen: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy


volumes:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
    driver: bridge
```

Dockerfile for nginx service looks like this:
```Dockerfile
FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
```
And nginx config above should contain something like this:
```nginx
    server {
        listen 80;
        location / {
		proxy_pass http://wg-easy:51821/;
        	proxy_http_version 1.1;
        	proxy_set_header Upgrade $http_upgrade;
        	proxy_set_header Connection "Upgrade";
        	proxy_set_header Host $host;
        }
    }
}
```

The last, nginx on the host machine should stream requests to 8082 / 8443 ports (for wg-easy virtual host `my.domain.com`) which are exposed by docker service.
