### ISSUE TITLE
Kubernetes: How to avoid exposing the Dashboard but only the UDP port

### ISSUE THREAD

**Issue by samuelexferri** [wg-easy/wg-easy#507]
I want to deploy wg-easy on Kubernetes on Digital Ocean. I'm using the following config (snippets):
```
# Load Balancer (WireGuard) (No TLS, Only UDP)
apiVersion: v1
kind: Service
metadata:
  name: wg-easy-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "51821"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "4"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "5"
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  type: LoadBalancer
  selector:
    app: wg-easy
  ipFamilyPolicy: SingleStack
  ports:
    - name: wg
      port: 51820
      targetPort: 51820
      protocol: UDP
    - name: wgdashboard # TODO: Remove Dashboard to public but it is needed for working
      port: 51821
      targetPort: 51821
      protocol: TCP
```

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wg-easy-pv
spec:
  storageClassName: openebs-data
  capacity:
    storage: 0.25Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /etc/wireguard
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-pvc
spec:
  volumeName: wg-easy-pv
  storageClassName: openebs-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-easy
  labels:
    app: wg-easy
spec:
  selector:
    matchLabels:
      app: wg-easy
  template:
    metadata:
      labels:
        app: wg-easy
    spec:
      restartPolicy: Always
      initContainers:
        - name: init
          image: busybox:1.32.0
          command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      containers:
        - name: wg-easy
          image: weejewel/wg-easy
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - name: wg
              containerPort: 51820
              protocol: UDP
            - name: wgdashboard
              containerPort: 51821
              protocol: TCP
          env:
            - name: PASSWORD
              value: "X" # TODO: Password
            - name: WG_HOST
              value: "<DOMAIN-WIREGUARD>"
            - name: "WG_PORT"
              value: "51820"
            - name: WG_DEFAULT_DNS
              value: "8.8.8.8"
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
          volumeMounts:
            - name: wg-easy-data
              mountPath: /etc/wireguard
      volumes:
        - name: wg-easy-data
          persistentVolumeClaim:
            claimName: wg-easy-pvc
---
# No Service Necessary
```

In this configuration everything works. I use port 51821 (wgdashboard) as a health check on the load balancer. But now I want to avoid exposing the dashboard to the public ip. How can this be achieved? It seems that if I only expose UDP port 51820 and not TCP 51821 I cannot get the handshake in the WireGuard application on the computer or phone.
Thanks in advance!
