### ISSUE TITLE
wg-easy in wirehole + Traefik not working

### ISSUE THREAD

**Issue by B0G0311** [wg-easy/wg-easy#521]
I am having trouble getting wg-easy up and running. I am using wirehole in which I replaced the basic wirehole container with wg-easy and am using traefik as my reverse proxy so I can use the vpn outside of my network. However I cannot seem to get the web ui to deploy.

My Wirehole stack
````
version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/:z"
    networks:
      private_network:
        ipv4_address: 10.2.0.200
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  wireguard:
    depends_on: [unbound, pihole]
    image: weejewel/wg-easy
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_HOST= vpn.domain.tech
      - PASSWORD=password
      - WG_PORT=51820
      - WG_DEFAULT_DNS=10.2.0.100 # Set it to point to pihole
      - WG_DEFAULT_ADDRESS=10.6.0.x
      
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    dns:
      - 10.2.0.100 # Points to pihole
      - 10.2.0.200 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to$
      - "traefik.http.routers.wireguard.entrypoints=proxy"
      - "traefik.http.routers.wireguard.rule=Host(`vpn.domain.tech`)" # <== Setting the domain for the d$
      - "traefik.http.services.pihole.loadbalancer.server.port=51821"


  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      - 10.2.0.200 # Points to unbound
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"
    environment:
      TZ: "America/New_York"
      WEBPASSWORD: "3a4gqHjVP%w1"
      ServerIP: 10.2.0.100 # Internal IP of pihole
      DNS1: 10.2.0.200 # Unbound IP
      DNS2: 10.2.0.200 # If we don't specify two, it will auto pick google.
    # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole/:/etc/pihole/:z"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/:z"
      - '/etc/resolv.conf:/etc/resolv.conf:z'
    networks:
      private_network:
        ipv4_address: 10.2.0.100
    labels:
     - "com.centurylinklabs.watchtower.enable=true"
     - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to$
     - "traefik.http.routers.pihole.entrypoints=proxy"
     - "traefik.http.routers.pihole.rule=Host(`pihole.domain.tech`)" # <== Setting the domain for the d$
     - "traefik.http.services.pihole.loadbalancer.server.port=80" 
```

Yet I try to goto the web ui at http://localIP:51821 and it says it is unable to connect.

There is also an error that the container provides:


[Error: ENOENT: no such file or directory, open '/etc/wireguard/wg0.conf'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/etc/wireguard/wg0.conf'
}
