### ISSUE TITLE
Moved to new Orange Pi 3 server, tunnel doesn't work

### ISSUE THREAD

**Issue by janaxhell** [wg-easy/wg-easy#523]
**Describe the bug**
I've been using wg-easy for some time on a OMV x86 server as docker container, tied to a Pihole+Unbound bare-metal on Orange Pi Zero 2.
Now I have bought an Orange Pi 3 LTS and basically replicated the whole system, using the same docker-compose with adapted volumes and such. Everything works except Wireguard. I have created a tunnel for my S22Ultra and this time it doesn't work, I cannot reach any URL with any browser. UDP 51820 is open on fritz.box router.

**To Reproduce**
This is my compose
```
version: "3.8"
services:
  wg-easy:
    environment:
      # ?? Required:
      # Change this to your host's public address
      - WG_HOST=[xxx.xxxxxxxx].com
      # Optional:
      - PASSWORD=[xxxxx]
      - WG_DEFAULT_DNS=192.168.1.2
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /srv/dev-disk-by-uuid-aeae213f-8ce4-405c-9d96-db90e69c28f8/Config/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

**Expected behavior**
I should be able to navigate from phone

**Server:**
 - OS: OMV6 on Armbian_23.02.2_Orangepi3-lts_bullseye_current_5.15.93 with Docker + Portainer

**Smartphone:**
 - Device: Samsung S22 Ultra 
 - OS: Android 12
 - Browser Vivaldi, Brave
 - Version: latest available

**Additional context**
My Wireguard container goes through NPM on port 51821 to my domain on Cloudflare.
Log doesn't say much:
```
2023-04-02T14:36:38.087Z Server Listening on http://0.0.0.0:51821
2023-04-02T14:36:38.093Z WireGuard Loading configuration...
2023-04-02T14:36:38.100Z WireGuard Configuration loaded.
2023-04-02T14:36:38.102Z WireGuard Config saving...
2023-04-02T14:36:38.109Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
$ wg syncconf wg0 <(wg-quick strip wg0)
2023-04-02T14:36:38.433Z WireGuard Config syncing...
2023-04-02T14:36:38.516Z WireGuard Config synced.
2023-04-02T14:36:48.319Z Server New Session: yG7Sa42AubHptVhJStAGEaRT1OjBLw8w
2023-04-02T14:36:50.467Z WireGuard Config saving...
2023-04-02T14:36:50.470Z WireGuard Config saved.
2023-04-02T14:36:50.470Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2023-04-02T14:36:50.550Z WireGuard Config synced.
$ wg genkey
$ echo EItzUI3nSeEl4cPregMKfVewFmQjCGcTx3Q7bVzSAGY= | wg pubkey
$ wg genpsk
2023-04-02T14:37:08.422Z WireGuard Config saving...
2023-04-02T14:37:08.425Z WireGuard Config saved.
2023-04-02T14:37:08.425Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2023-04-02T14:37:08.511Z WireGuard Config synced.
```
I have also tried with another Pihole+Unbound installed as container on the same Orange Pi 3 where Wireguard lives. Same result.

EDIT:
It appears that if I disable proxying on Cloudflare for my domain, I can navigate from Phone, but at the same time I cannot
open the webGUI because "connection is not private". I did not have this problem before, has anything changed lately?
I have my Wireguard container reverse-proxied through Nginx Proxy Manager to my Cloudflare domain on port 51821, and if I enable proxy con Cloudflare, I can access the webGUI, but not use the tunnel. What can I do?

EDIT2:
I have opened and closed Cloudflare proxy, port TCP 51821 on fritz.box and enabled/disabled HSTS on NPM several times, then reset everything as before (my domain PROXIED through Cloudflare and only UDP 51820 open on fritz.box) and now it works.. I can navigate from phone through tunnel. I'll wait tomorrow before closing this, I have no idea what happened and i want to be sure it still works.

EDIT3
No, Wireguard on phone works intermittently. For some time I can navigate and use messaging, then I am cut out of the net, impossible to access any URL or use Whatsapp/Discord. As soon as I close/reopen Wireguard it works again for a while. Log make no mention about this.

**Comment by FlorianSoler** [comment]
Same problem here, I can confirm that it come from the orange pi zero 3.
```
version: "3.8"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard-stable
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    env_file:
      - .env
    volumes:
      - ./app_data/config:/config
      - ./app_data/lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
```
```
PUID=1000
PGID=1000
TZ=Europe/Paris
#SERVERURL=wireguard.domain.com
SERVERPORT=51820
PEERS=user,admin
PEERDNS=1.1.1.1, 1.0.0.1
INTERNAL_SUBNET=10.10.0.0/24
ALLOWEDIPS=0.0.0.0/0
PERSISTENTKEEPALIVE_PEERS=
LOG_CONFS=true
```
