### ISSUE TITLE
Question about allow IP

### ISSUE THREAD

**Issue by killmasta93** [wg-easy/wg-easy#563]
Hi
Currently i have it working for the users, but an odd issue im having, is that when i put allowed IP the user should not be able to ping anything else, if the user changes on the config to put 0.0.0.0 it seems that it works for them, so not sure what else i need to change in the config? this is my docker compose
```

version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=19xx.xx.xx

      # Optional:
      - PASSWORD=test
      - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      #- WG_DEFAULT_DNS=192.168.21.254
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=192.168.21.244/32
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
