### ISSUE TITLE
Unable to Resolve Local IP Addresses

### ISSUE THREAD

**Issue by fenpaws** [wg-easy/wg-easy#572]
First of all, sorry for now sticking to your bug report pattern. Since I don't think this is a bug I decided to not use it, but I still structured it, so it's easier to read for you guys :D

# Problem Summary
I'm encountering an issue with my "wg-easy" Docker instance where I am unable to resolve local IP addresses of my home network. However, accessing the services using their respective domains works without any problems.

# Environment Setup
Every container runs on the same host with the ip 192.168.188.42
 - fritz.box (router) -> wg-easy -> pihole -> network
 - Pi-Hole is running in a separate Docker Compose file
 - wg-easy is also running in the host network mode.

# Issue Details

I can access external websites and services without any issues from the "wg-easy" instance.
The problem is specific to resolving local IP addresses within my home network.
I noticed that I can access the services using their respective domains.
The issue occurs only when I try to ping the local IPs directly.

# Some CLI Output

Without WG:
  ```
  PS C:\Users\USER> TRACERT.EXE 192.168.188.1
  
  Tracing route to fritz.box [192.168.188.1]
  over a maximum of 30 hops:
  
    1     1 ms     1 ms     1 ms  fritz.box [192.168.188.1]
  ```

With WG:

```
PS C:\Users\USER> TRACERT.EXE 192.168.188.1

Tracing route to fritz.box [192.168.188.1]
over a maximum of 30 hops:

  1     *        *        *     Request timed out.
  2     *        *        *     Request timed out.
  3     *        *        *     Request timed out.
  4     *        *        *     Request timed out.
[...]
```

---

wg-easy docker-compose.yml
```yml
version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: "wg-easy"
    environment:
      - WG_HOST=domain.com
      - PASSWORD=foobar123
      - WG_DEFAULT_DNS=192.168.188.42
      - WG_ALLOWED_IPS=192.168.188.0/24
    volumes:
      - .:/etc/wireguard
    ports:
      ##- "51820:51820/udp"
       - "51821:51821/tcp"
    restart: unless-stopped
    network_mode: 'host'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    #sysctls:
    #   - net.ipv4.ip_forward=1
    #   - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wg-easy.entrypoints=web"
      - "traefik.http.routers.wg-easy.rule=Host(`wg-easy.local.domain.com`)"
      - "traefik.http.middlewares.wg-easy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wg-easy.middlewares=wg-easy-https-redirect"
      - "traefik.http.routers.wg-easy-secure.entrypoints=websecure"
      - "traefik.http.routers.wg-easy-secure.rule=Host(`wg-easy.local.domain.com`)"
      - "traefik.http.routers.wg-easy-secure.tls=true"
      - "traefik.http.routers.wg-easy-secure.service=wg-easy"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"

```

pi-hole docker-compose.yml
```yml
version: "3.8"
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "80:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pi-hole.entrypoints=web"
      - "traefik.http.routers.pi-hole.rule=Host(`pi-hole.local.domain.com`)"
      - "traefik.http.middlewares.pi-hole-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pi-hole.middlewares=pi-hole-https-redirect"
      - "traefik.http.routers.pi-hole-secure.entrypoints=websecure"
      - "traefik.http.routers.pi-hole-secure.rule=Host(`pi-hole.local.domain.com`)"
      - "traefik.http.routers.pi-hole-secure.tls=true"
      - "traefik.http.routers.pi-hole-secure.service=pi-hole"
      - "traefik.http.services.pi-hole.loadbalancer.server.port=80"
```
