### ISSUE TITLE
Error: WireGuard exited with the error: Cannot find device "wg0"

### ISSUE THREAD

**Issue by JKL213** [wg-easy/wg-easy#585]
**Describe the bug**
I'm trying to start the container with a Docker Compose file. Doing so just produces the following error:
2023-06-26T18:02:41.768Z Server Listening on http://0.0.0.0:51821

2023-06-26T18:02:41.769Z WireGuard Loading configuration...

2023-06-26T18:02:41.778Z WireGuard Configuration loaded.

2023-06-26T18:02:41.778Z WireGuard Config saving...

2023-06-26T18:02:41.780Z WireGuard Config saved.

$ wg-quick down wg0

$ wg-quick up wg0

Error: WireGuard exited with the error: Cannot find device "wg0"

This usually means that your host's kernel does not support WireGuard!

    at /app/lib/WireGuard.js:65:19

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

    at async /app/lib/WireGuard.js:63:9

**To Reproduce**
1. I'm using this guide: https://goneuland.de/wg-easy-wireguard-webinterface-mittels-docker-compose-und-traefik-installieren
2. Created a folder in /opt for the install script
3. Deployed docker-compose.yml
4. Started the docker file with **"docker compose -f /opt/containers/wg-easy/docker-compose.yml up -d"**
5. Go into Portainer and look into logs.
6. Error is clearly displayed.

**Expected behavior**
I expected the server to start normally and the web interface to be viewable. 
**Screenshots**
![grafik](https://github.com/wg-easy/wg-easy/assets/38791325/bb47d98b-3cb9-4ca6-906a-5d7ff7cf3f7d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox, newest version

**Additional context**
The Wireguard setup is on a Debian 11 VPS server with Docker (newest version) and Docker Compose (newest version). I think there might be a conflict with other docker applications or another instance of Wireguard being installed earlier. However, I have already uninstalled this version. Wireguard is supposed to be running behind a Traefik instance but I do not believe that this is causing the issue. 
I updated the installation with apt-get update && apt-get upgrade.
Also, I've checked if the original install script from the github page works for me. Docker just returns "invalid reference format".

**Comment by OfflinePing** [comment]
Same error here. I reinstalled docker, docker-compse, docker.io. Ive tried to reset all iptables and other configs or firewalls and still getting that error

**Comment by fanvantan** [comment]
I got same problem with my CentOS 7. I found that there are some requirements to install wireguard. 
https://www.wireguard.com/install/#installation

For example, should install kernel-plus to support wireguard.

**Comment by GiaNTizmO** [comment]
Confirm that issue with my VPS with Linux.
Debian GNU/Linux 10
```Linux en1.gate 4.19.0-24-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64 GNU/Linux```

Upgrading the Linux kernel to version 5.1X solved this issue in my case.
```Linux en1.gate 5.10.0-0.deb10.23-amd64 #1 SMP Debian 5.10.179-1~deb10u1 (2023-05-26) x86_64 GNU/Linux```


```
root@en1.gate:~# docker logs 3e1d666d909e
2023-06-28T23:01:34.346Z Server Listening on http://0.0.0.0:51821
2023-06-28T23:01:34.348Z WireGuard Loading configuration...
2023-06-28T23:01:34.350Z WireGuard Configuration loaded.
2023-06-28T23:01:34.350Z WireGuard Config saving...
2023-06-28T23:01:34.352Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
2023-06-28T23:01:34.437Z WireGuard Config syncing...
$ wg syncconf wg0 <(wg-quick strip wg0)
2023-06-28T23:01:34.463Z WireGuard Config synced.
```

**Comment by Sinitra** [comment]
+1

`Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:06:41.515Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:06:41.516Z WireGuard Loading configuration...
2023-07-02T10:06:41.517Z WireGuard Configuration loaded.
2023-07-02T10:06:41.517Z WireGuard Config saving...
2023-07-02T10:06:41.518Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:06:54.914Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:06:54.915Z WireGuard Loading configuration...
2023-07-02T10:06:54.916Z WireGuard Configuration loaded.
2023-07-02T10:06:54.916Z WireGuard Config saving...
2023-07-02T10:06:54.918Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:07:21.095Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:07:21.096Z WireGuard Loading configuration...
2023-07-02T10:07:21.097Z WireGuard Configuration loaded.
2023-07-02T10:07:21.098Z WireGuard Config saving...
2023-07-02T10:07:21.098Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:08:12.879Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:08:12.880Z WireGuard Loading configuration...
2023-07-02T10:08:12.882Z WireGuard Configuration loaded.
2023-07-02T10:08:12.882Z WireGuard Config saving...
2023-07-02T10:08:12.883Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:09:13.462Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:09:13.463Z WireGuard Loading configuration...
2023-07-02T10:09:13.464Z WireGuard Configuration loaded.
2023-07-02T10:09:13.464Z WireGuard Config saving...
2023-07-02T10:09:13.465Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:10:14.021Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:10:14.022Z WireGuard Loading configuration...
2023-07-02T10:10:14.023Z WireGuard Configuration loaded.
2023-07-02T10:10:14.023Z WireGuard Config saving...
2023-07-02T10:10:14.024Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:11:14.623Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:11:14.624Z WireGuard Loading configuration...
2023-07-02T10:11:14.625Z WireGuard Configuration loaded.
2023-07-02T10:11:14.625Z WireGuard Config saving...
2023-07-02T10:11:14.626Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:12:15.178Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:12:15.179Z WireGuard Loading configuration...
2023-07-02T10:12:15.180Z WireGuard Configuration loaded.
2023-07-02T10:12:15.180Z WireGuard Config saving...
2023-07-02T10:12:15.181Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:13:15.819Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:13:15.820Z WireGuard Loading configuration...
2023-07-02T10:13:15.821Z WireGuard Configuration loaded.
2023-07-02T10:13:15.821Z WireGuard Config saving...
2023-07-02T10:13:15.822Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:14:16.327Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:14:16.327Z WireGuard Loading configuration...
2023-07-02T10:14:16.328Z WireGuard Configuration loaded.
2023-07-02T10:14:16.329Z WireGuard Config saving...
2023-07-02T10:14:16.330Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-07-02T10:15:17.048Z Server Listening on http://0.0.0.0:51821
2023-07-02T10:15:17.049Z WireGuard Loading configuration...
2023-07-02T10:15:17.050Z WireGuard Configuration loaded.
2023-07-02T10:15:17.050Z WireGuard Config saving...
2023-07-02T10:15:17.051Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
`

**Comment by RoseannePeeters** [comment]
Got the same issue, we need a fix for this

**Comment by ervomk** [comment]
Any update about this issue?

**Comment by moriony** [comment]
Confirm issue with DigitalOcean VPS Debian 10

Kernel upgrade solved issue in my case. Thx @GiaNTizmO  

Debian kernel upgrade documentation https://wiki.debian.org/HowToUpgradeKernel

My steps:
```sh
$ uname -a
Linux moriony 4.19.0-25-cloud-amd64 #1 SMP Debian 4.19.289-1 (2023-07-24) x86_64 GNU/Linux
$ apt install linux-image-5.10.0-0.deb10.23-amd64
$ reboot
$ uname -a 
Linux moriony 5.10.0-0.deb10.23-amd64 #1 SMP Debian 5.10.179-3~deb10u1 (2023-07-28) x86_64 GNU/Linux
$ apt autoremove
```

**Comment by bornostojak** [comment]
Here is my solution for this issue:

1. on the host machine, run `sudo modprobe ip_tables && sudo modprobe iptable_nat`
2. to the container, add the following enviroment variables: 
`WG_POST_UP='iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -j MASQUERADE; iptables -A FORWARD -o %i -j ACCEPT'` and `WG_POST_DOWN='iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -j MASQUERADE; iptables -D FORWARD -o %i -j ACCEPT'`

Also, just in case, here is my `docker-compose.yaml`, deployed as a docker swarm stack:

```yaml
version: '3.7'

volumes:
  wg_clients:

networks:
  wg:


configs:
  nginx_config:
    file: ./configs/nginx/nginx.conf

secrets:
  nginx_passwords:
    file: ./configs/nginx/passwords
  nginx_ssl_crt:
    file: ./secrets/ssl.crt
  nginx_ssl_key:
    file: ./secrets/ssl.key

services:
  wgeasy:
    image: weejewel/wg-easy:7
    environment:
      WG_POST_UP: 'iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -j MASQUERADE; iptables -A FORWARD -o %i -j ACCEPT'
      WG_POST_DOWN: 'iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -j MASQUERADE; iptables -D FORWARD -o %i -j ACCEPT'
      WG_DEFAULT_ADDRESS: 192.168.1.x
      PASSWORD: <REDACTED>
      WG_HOST: example.com
      WG_ALLOWED_IPS: 0.0.0.0/0
      WG_PERSISTENT_KEEPALIVE: 30
      WG_DEFAULT_DNS: 1.1.1.1
    volumes:
      - wg_clients:/etc/wireguard
    networks:
      - wg
    ports:
      - 51820:51820/tcp
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

  nginx:
  # purely for https access to the web GUI
    image: nginx:stable-alpine3.17-slim
    secrets:
      - source: nginx_ssl_crt
        target: ssl.crt
      - source: nginx_ssl_key
        target: ssl.key
      - source: nginx_passwords
        target: passwords
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - wg
    ports:
      - 21443:443

``` 

I'm actually curious if this works for other folks, depending on your setup, that is.
