### ISSUE TITLE
Server.js only listens on IPv6 and not IPv4 when running Docker with network host

### ISSUE THREAD

**Issue by fanvantan** [wg-easy/wg-easy#589]
**Server.js only listens on IPv6 but not IPv4 when running Docker with networking host mode.**

I want to keep the original IP address of Wireguard client traffic instead of being masqueraded by the host IP address. Therefore, I run Docker with network host mode. Here’s my docker-compose.yml file:
```
version: "3.8"
services:
  wg-easy:
    network_mode: host
    environment:
      - PASSWORD=xxx
      - PORT=51821
      - WG_HOST=xxx
      - WG_PERSISTENT_KEEPALIVE=30
      - WG_POST_UP=iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT;iptables -A INPUT -p tcp -m tcp --dport 51821 -j ACCEPT;iptables -A FORWARD -i wg0 -j ACCEPT;iptables -A FORWARD -o wg0 -j ACCEPT;
      - WG_POST_DOWN=iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT;iptables -D INPUT -p tcp -m tcp --dport 51821 -j ACCEPT;iptables -D FORWARD -i wg0 -j ACCEPT;iptables -D FORWARD -o wg0 -j ACCEPT;
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
```

This is the output from netstat. The host is not listening to tcp/51821 but is listening to tcp6/51821.
```
# netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1006/sshd           
tcp6       0      0 :::51821                :::*                    LISTEN      4569/node           
tcp6       0      0 :::22                   :::*                    LISTEN      1006/sshd           
udp        0      0 0.0.0.0:51820           0.0.0.0:*                           -                   
udp6       0      0 :::51820                :::*                                -                   
```

Per my understanding, unlike network bridge mode, network host mode doesn’t have an assigned IP address. Additionally, the Server.js code line that makes the server listen on port 51821 doesn’t specify a binding IP address (e.g., 0.0.0.0). Therefore, Node.js will only listen on the IPv6 address.
Could you check if specify a binding address will solve this problem ?
