### ISSUE TITLE
UI not accessible (gateway time-out)

### ISSUE THREAD

**Issue by dParikesit** [wg-easy/wg-easy#596]
**Describe the bug**
I have a stack of wg-easy, adguard home, and nginx proxy manager. I have added wg-easy:51821 to nginx. When I tried to access the UI via domain name, I get 504 gateway time-out. When I tried to access it via http://IP:51821 it 's unreachable even though I have opened the inbound port. 

Log looks fine to me. Adguard also works properly. Haven't checked wireguard functionality because I can't access the UI.

**Screenshots**
![image](https://github.com/wg-easy/wg-easy/assets/64581930/b92ba5a9-e2a7-4ba9-bc5f-7247ccb44466)
![image](https://github.com/wg-easy/wg-easy/assets/64581930/a23e9682-b6d7-4980-acc8-2c0887da986f)
![image](https://github.com/wg-easy/wg-easy/assets/64581930/26024186-79e5-4720-abbd-ab279e5162d2)
![image](https://github.com/wg-easy/wg-easy/assets/64581930/5596c2d3-eb37-48bf-a142-eec4cb7475df)

**Docker compose**
```
version: "3.9"

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ~/vpn/nginx/data:/data
      - ~/vpn/nginx/letsencrypt:/etc/letsencrypt
    networks:
      vpn:
        ipv4_address: 10.1.0.2

  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    volumes:
      - ~/vpn/adguard/work:/opt/adguardhome/work
      - ~/vpn/adguard/conf:/opt/adguardhome/conf
      - /etc/letsencrypt/live/<REDACTED>/fullchain.pem:/opt/ssl/fullchain.pem:rw
      - /etc/letsencrypt/live/<REDACTED>/privkey.pem:/opt/ssl/privkey.pem:rw
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 80:80/tcp
      # - 80:80/udp
      # - 443:443/tcp
      # - 443:443/udp
      - 784:784/udp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 8853:8853/udp
    networks:
      vpn:
        ipv4_address: 10.1.0.3

  wireguard:
    image: weejewel/wg-easy:latest
    container_name: wireguard
    restart: unless-stopped
    environment:
      WG_HOST: <REDACTED>
      PASSWORD: <REDACTED>
      WG_DEFAULT_DNS: 10.1.0.3
      WG_DEFAULT_ADDRESS: 10.1.1.x
    volumes:
      - ~/vpn/wireguard:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821 # admin UI
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      vpn:
        ipv4_address: 10.1.0.4

networks:
  vpn:
    ipam:
      config:
        - subnet: 10.1.0.0/24
```
