### ISSUE TITLE
Cannot find device "wg0"

### ISSUE THREAD

**Issue by RoseannePeeters** [wg-easy/wg-easy#599]
**Describe the bug**
Starting the docker container and I get following error
```bash
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | Error: WireGuard exited with the error: Cannot find device "wg0"
wg-easy  | This usually means that your host's kernel does not support WireGuard!
```

This happened on Ubuntu 22.04, so I tried another os, AlmaLinux 8, and that gave the same error.

I should note that I am using a containerized vps from a provider (which allows ALL VPN SOFTWARE)

**To Reproduce**
1. Run the docker command or use a compose file.

**Expected behavior**
The docker container to start properly.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 and AlmaLinux 8
 - Browser /
 - Version: latest

**Additional context**
I should note that I am using a containerized vps from a provider (which allows ALL VPN SOFTWARE)

**Comment by Kwallie010** [comment]
Maybe check out this docker compose, I managed to solve that error by adding the cap_add and sysctls as follows: 
```
I do not have the same OS, but I did run into the same error. I finally solved the error with the following docker compose: 

version: "3.8"
services:
  wg-easy:     
    image: weejewel/wg-easy
    container_name: wireguard
    restart: unless-stopped
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51822:51820/udp"
      - "51821:51821/tcp"
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD=${PASSWORD}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```
