### ISSUE TITLE
No connection (rx: 0 B) - wg-easy on Windows Server 2019

### ISSUE THREAD

**Issue by 411A** [wg-easy/wg-easy#610]
**Describe the bug**
Hi, I used `docker-compose` to create `wg-easy` on my Windows Server 2019. Completion was successful but when I use the config through QRCode on my Android 13 phone (official WireGuard app - Version 1.0.20230707), I receive no data (no internet), and the web panel doesn't show the download-upload.
```
Transfer
rx: 0 B, tx: 2.02 KiB
```
I used the below `docker-compose.yml`:
```yml
version: "3.8"

services:
  wg-easy:
    environment:
      - WG_HOST=VPS_IP_FROM_VPSPROVIDER_PANEL
      # Password to login on http://localhost:51821
      - PASSWORD=1234
    image: weejewel/wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
```
Then on `cmd`:
```cmd
docker-compose up -d
```
Also allowed UDP ports on the firewall:
```powershell
 New-NetFirewallRule -DisplayName "Allowed WireGuard Port (Inbound)" -Direction Inbound -LocalPort 51820 -Protocol UDP -Action Allow
```
```powershell
 New-NetFirewallRule -DisplayName "Allowed WireGuard Port (Outbound)" -Direction Outbound -LocalPort 51820 -Protocol UDP -Action Allow
```
Other info on my `.conf` file:
```
Interface
Addresses: 10.8.0.2/24
DNS servers: 1.1.1.1

Peer
Pre-shared key
enabled
Allowed IPs
0.0.0.0/0, ::/0
Endpoint: VPS_IP_FROM_VPSPROVIDER_PANEL:51820
```
I've never worked with WireGuard before, and most of the guides are using Ubuntu, excuse me if I forget some more configuration & this issue seems simple.

**To Reproduce**
1. Install Docker Desktop on Windows Server 2019, restart
2. Inside a folder create `docker-compose.yml` with the provided content on the description, change `WG_HOST` & `PASSWORD`
3. Run docker desktop, open a `cmd` terminal (inside the created folder that contains `docker-compose.yml`) & enter: `docker-compose up -d`
4. Set firewall rules on PowerShell if needed
5.  ...

**Desktop:**
 - OS: Windows Server 2019 - V 1809
 - Browser: Microsoft Edge Version 115.0.1901.203 (Official build) (64-bit)

**Smartphone:**
 - Device: Samsung Galaxy A71
 - OS: Android 13
