### ISSUE TITLE
Need help! How to do this scheme? (attach)

### ISSUE THREAD

**Issue by alexsalex** [wg-easy/wg-easy#621]
Maybe somebody already have this done. Any suggestion appreciated,

![VPN Diagram](https://github.com/wg-easy/wg-easy/assets/17325366/42e77097-3a56-4bed-8c98-36cfb7809ae1)

**Comment by eandersons** [comment]
First of all, these kind of questions belong in [Discussions](/wg-easy/wg-easy/discussions).

Secondly, what exactly is your issue? What have you already tried? What works and what not?

Regarding Nginx Proxy Manager, #499 might contain some pointers, but basically read the documentation of the chosen tools, and you should be fine.

**Comment by alexsalex** [comment]
Agree. If somebody can move this post to Discussion I will really appreciate it.

I just need some information how to configure Easy-WG to accept connections on internal wireguarg ip. If somebody can help I will be happy)

**Comment by AndreiTelteu** [comment]
@alexsalex I figured it out !
I have this docker-compose.yml config
```yaml

version: "3.8"

services:
  wg:
    environment:
      - WG_HOST=your public wireguard domain
      - PASSWORD=
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    image: weejewel/wg-easy
    container_name: wg
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2

  pihole:
    image: pihole/pihole
    .... etc

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./nginx/route.sh:/docker-entrypoint.d/10-route.sh
    ports:
      - 8000:80
    networks:
      wg-easy:
        ipv4_address: 10.8.1.4
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
```
So all wg clients are using `10.8.0.x`, wg itself and pihole and nginx are on 10.8.1.x.
I added the nginx container with this 2 mapped files:

1. `nginx/default.conf`
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        http2 on;
        server_name _;
        location / {
                proxy_ssl_verify off;
                proxy_pass https://10.8.0.14:33443;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header REMOTE-HOST $remote_addr;
                proxy_set_header Accept-Encoding gzip;
        }
}
```
**NOTE**: `10.8.0.14:33443` this is the wireguard client and port that i want to proxy to

2. `nginx/route.sh` - this is a initialization hook that routes the trafic to the wg client network
```
apt update
apt install -y whiptail
apt install -y iproute2
ip route add 10.8.0.0/24 via 10.8.1.2
```
**NOTE**: Notice `10.8.1.2` is the ip of the wireguard container defined in docker-compose, and 10.8.0.0/24 is the addresses of wg clients. Change them accordingly.

And now `http://your-server-ip:8000` routes to `https://10.8.0.14:33443` in your wireguard network via this nginx container.
You can now put caddy or nginx-proxy-manager in front of it like you can find in any other tutorial.
