### ISSUE TITLE
Problem with Oracle Cloud VM

### ISSUE THREAD

**Issue by HossamMohsen7** [wg-easy/wg-easy#629]
Hello, I'm trying to use wg-easy on my Oracle cloud machine running `Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1032-oracle aarch64)`, but when I try to connect devices to my wg-easy instance they don't get internet access, I tried to change WG_DEVICE and iptables rules with no luck. Ports 51820/udp and 51821/tcp are forwarded on Oracle's Dashboard.
Here is my `docker-compose.yml`:
```
version: "3.8"

services:
  wg-easy:
    environment:
      - WG_HOST=REMOVED
      - PASSWORD=REMOVED
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
	  - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

```
