### ISSUE TITLE
Incorrect password

### ISSUE THREAD

**Issue by kkycble** [wg-easy/wg-easy#642]
**Describe the bug**
It keeps saying incorrect password even when the correct password is entered

**To Reproduce**
deploy container using this docker compose: 

```
version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST= xyz.synology.me
      # Optional:
      - PASSWORD= 123456
      - WG_PORT= 51820
      # - WG_DEFAULT_ADDRESS= 10.8.0.x
      - WG_DEFAULT_DNS= 192.168.1.248
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS= 192.168.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /volume1/docker/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
```

then incorrect password is shown when 123456 is entered is login page. 

**Expected behavior**
I should login just fine. 

**Additional context**
When commenting the password variable. I can access the web ui functionality just fine.
