### ISSUE TITLE
Client connection issues in `nightly` build

### ISSUE THREAD

**Issue by BerserkeR-Git** [wg-easy/wg-easy#692]
While the new image starts up for me and the UI works, the connection itself doesn't, and I keep getting this:
```
2023-12-21T20:35:53.148Z Server Listening on http://0.0.0.0:51821/

2023-12-21T20:35:53.150Z WireGuard Loading configuration...

2023-12-21T20:35:53.153Z WireGuard Configuration loaded.

2023-12-21T20:35:53.153Z WireGuard Config saving...

2023-12-21T20:35:53.155Z WireGuard Config saved.

$ wg-quick down wg0

$ wg-quick up wg0

2023-12-21T20:35:53.288Z WireGuard Config syncing...

$ wg syncconf wg0 <(wg-quick strip wg0)

2023-12-21T20:35:53.318Z WireGuard Config synced.

2023-12-21T20:35:59.528Z Server New Session: i5sRsCUFkeLvjyauYOHTzzanEtQN3LVO

2023-12-21T20:37:07.814Z WireGuard Config saving...

2023-12-21T20:37:07.815Z WireGuard Config saved.

2023-12-21T20:37:07.815Z WireGuard Config syncing...

$ wg syncconf wg0 <(wg-quick strip wg0)

2023-12-21T20:37:07.848Z WireGuard Config synced.

2023-12-21T20:37:09.166Z WireGuard Config saving...

2023-12-21T20:37:09.168Z WireGuard Config saved.

2023-12-21T20:37:09.168Z WireGuard Config syncing...

$ wg syncconf wg0 <(wg-quick strip wg0)

2023-12-21T20:37:09.204Z WireGuard Config synced.
```
But the outside connection still works with the old image, weejewel/wg-easy (v7)
So the new image boots up but the outside connections aren't working and I'm not seeing any network traffic in the UI.

_Originally posted by @BerserkeR-Git in https://github.com/wg-easy/wg-easy/issues/682#issuecomment-1866922975_

**Comment by peterlewis** [comment]
Thank you for raising this, @BerserkeR-Git.

@pheiduck Do you think this may be related to the issue raised by @redstripes89 [downstream](https://github.com/peterlewis/wg-easy/issues/71)?

**Comment by pheiduck** [comment]
I am not sure where it came from maybe because I set the MTU fixed to 1420

**Comment by pheiduck** [comment]
@BerserkeR-Git please test: ghcr.io/wg-easy/wg-easy:development

**Comment by peterlewis** [comment]
Please note that the MTU will have been hardcoded into the downloaded `.conf`. Can you please download a fresh copy and re-import to WireGuard?

**Comment by peterlewis** [comment]
@pheiduck I'd suggest we merge the MTU reversion regardless as it is subsequently hardcoding the MTU into the .conf.

**Comment by pheiduck** [comment]
@BerserkeR-Git 
cd into the directory where your wg-easy lies. 
1. do: `docker compose down`
2. `docker system prune -a —volume`
3. `docker compose up -d`

**Comment by peterlewis** [comment]
Okay. So it's not MTU causing your issue, then. Thought glad it was brought up as ~always~ often good to remove rigid values where possible!

I'm wondering whether, and indeed suspect that this is a dependency regression, as opposed to being a result of rebase from downstream.

I would suggest we look to create a dev build based on @WeeJeWel's v8 release, but including the synology fix, and see how that works for you.

**Comment by peterlewis** [comment]
Sure thing. I've pushed that build to `development` so if you can re-pull and revert with your findings, then that'd be fab.

**Comment by rusty1281** [comment]
I just got home and tested this myself. The initial development image was (is) also working fine. I have just tested again (without the new pull).

In my previous testings I have removed MTU 1420 value on the client side automatically, as that was always "automatic" for me, so I didn't pay attention to it.

So just to confirm, even though the new correct helped Berserker, clearing the MTU value on the client side works like a charm. Maybe I should have mentioned it in the previous issue.

Great work again guys! Tnx!

**Comment by peterlewis** [comment]
Okay. Thank you, both.

@BerserkeR-Git I don't suspect your issue to be caused by dark mode, thankfully! 👍🏻 I think we may be looking at some kind of regression in one of the (multiple) node modules that have been patched. I'll continue to investigate.

@rusty1281 Thank you for letting me know all is good. I'm going to push the MTU reversion to nightly. If you can please, subsequently, head on over to `nightly` then that'd be lush.

**Comment by rusty1281** [comment]
> @rusty1281 Thank you for letting me know all is good. I'm going to push the MTU reversion to nightly. If you can please, subsequently, head on over to `nightly` then that'd be lush.

Ofc, I will test `nightly`as soon as you update the image.

**Comment by peterlewis** [comment]
@rusty1281 updated :)

**Comment by rusty1281** [comment]
> @rusty1281 updated :)

Nightly running with 0 issue. MTU on automatic for me.

<img width="815" alt="Screenshot 2023-12-21 at 23 47 50" src="https://github.com/wg-easy/wg-easy/assets/5110408/df9c6739-95e6-4566-aa15-6a1c5be69efe">

**Comment by peterlewis** [comment]
@rusty1281 excellent news! We'll leave the MTU reversion in-place then! Sorry for the inconvenience. I have created a separate issue for you at https://github.com/wg-easy/wg-easy/issues/694 so if you see regression of this, please update that separate issue.

We'll keep this issue, going forwards, to track (and look to resolve) @rusty1281's reported issue, which I think may be related to a regression in one of the node dependencies. We shall see!

**Comment by peterlewis** [comment]
Okay thank you @rusty1281. So both you and @BerserkeR-Git are running on Synology(?) and both experiencing the issue.

I suspect, as mentioned previously, we are looking at a note dependency regression. Will need to do some further troubleshooting alongside @pheiduck.

I will keep in touch! For now, the `development` image is `latest + synology fix` and anticipate the next update it sees will be related to your issue, so stick with that for now.

**Comment by rusty1281** [comment]
> > > @rusty1281
> > 
> > 
> > Nightly running with 0 issue. MTU on automatic for me.
> 
> I'm on nightly now but I'm getting the same result. I even tried it with a separate compose file and clean install, but I'm not getting a connection. I left MTU on auto as well, just like before with the dev build that was in fact working.

I have just tested this on my MacBook using the same setup as on my iPhone. I have connected to the internet over my iPhone and then activated WG. All works fine for me. Either on the phone or on the MacBook.

<img width="818" alt="Screenshot 2023-12-22 at 00 08 41" src="https://github.com/wg-easy/wg-easy/assets/5110408/db321e9d-8454-4838-acd7-a05a22a85171">

@peterlewis I have no issues at all. All working for me fine. I have tested with number of scenarios and with multiple Synology NAS boxes, no issues at all.

**Comment by peterlewis** [comment]
Oh crumbs! Sorry, @rusty1281, I had misread your quoted reply as being from you! I'm glad (positively delighted) you're not experiencing issues with the latest `nightly` release!

We will continue to look into @BerserkeR-Git's issue, given when the issue arose (rebase from downstream). As mentioned, I suspect node dependency.

**Comment by rusty1281** [comment]
No worries @peterlewis, let me know if I can validate any more updates and changes in the upcoming images. I have updates my [article(s)](https://www.blackvoid.club/wireguard-vpn-for-your-synology-nas/) that reference this WG solution (that is where most Syno reports came from), and will keep it up to date as this develops further.

**Comment by peterlewis** [comment]
Thank you, both, much appreciated.

**Comment by peterlewis** [comment]
@BerserkeR-Git, for your information, have pushed Synology fix (v9) to `latest` meaning that you can head on back to stable whilst we work through this issue.

If you're happy to help us test further, though, then that'd be lush. I'll drop a comment here when we've got progression on the issue.

**Comment by peterlewis** [comment]
The issues you are seeing may be related to those raised by @redstripes89 in my (now-archived) fork. I'm hoping he's able to test the `nightly` build here and report back with his experience.

**Comment by peterlewis** [comment]
@BerserkeR-Git can you please post your `docker-compose`, redacting any sensitive information?

Thanks!

**Comment by pheiduck** [comment]
The Port config looks not correct 
```
ports:
      - "redacted:51820/udp"
      - "51820:51821/tcp"
```

should be:

```
ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
```

**Comment by pheiduck** [comment]
@rusty1281 could you please post your docker compose for comparison?

**Comment by peterlewis** [comment]
Yes and if @redstripes89 and @hansnull are also happy to do so then that'd be great!

**Comment by LoV432** [comment]
Same issue here on Manjaro. The UI is working but no connection. Reverting to old version fixes the issue

```
wg-easy  | 2023-12-22T11:03:09.210Z Server Listening on http://0.0.0.0:51821
wg-easy  | 2023-12-22T11:03:09.212Z WireGuard Loading configuration...
wg-easy  | 2023-12-22T11:03:09.215Z WireGuard Configuration loaded.
wg-easy  | 2023-12-22T11:03:09.216Z WireGuard Config saving...
wg-easy  | 2023-12-22T11:03:09.221Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | 2023-12-22T11:03:09.323Z WireGuard Config syncing...
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2023-12-22T11:03:09.350Z WireGuard Config synced.
wg-easy  | 2023-12-22T11:03:33.938Z Server New Session: JOmgWtIsUSM6N7cJnVCiwPa2vJKxdXQp
```

```yaml
version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=REMOVED

      # Optional:
      - PASSWORD=REMOVED
      - WG_PORT=445
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=100.100.100.100
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

    image: ghcr.io/wg-easy/wg-easy:nightly
#    image: lov432/wg-easy:7-weekly
    container_name: wg-easy
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "445:51820/udp"
      # - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      traefik_proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`REMOVED`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.routers.wireguard.tls.certresolver=production"
      - "traefik.http.routers.wireguard.tls.domains[0].main=REMOVED"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "traefik.docker.network=traefik_proxy"


networks:
    traefik_proxy:
       external: true
```

**Comment by peterlewis** [comment]
@LoV432 please can you confirm that the latest stable fixes things for you?

**Comment by LoV432** [comment]
> @LoV432 please can you confirm that the latest stable fixes things for you?



Yes `image: ghcr.io/wg-easy/wg-easy` works just fine

![image](https://github.com/wg-easy/wg-easy/assets/60856741/926e3f3f-613f-4c79-926a-bba1ab5d9752)
```
wg-easy  | 2023-12-22T11:29:01.565Z Server Listening on http://0.0.0.0:51821
wg-easy  | 2023-12-22T11:29:01.566Z WireGuard Loading configuration...
wg-easy  | 2023-12-22T11:29:01.570Z WireGuard Configuration loaded.
wg-easy  | 2023-12-22T11:29:01.570Z WireGuard Config saving...
wg-easy  | 2023-12-22T11:29:01.571Z WireGuard Config saved.
wg-easy  | $ wg-quick down wg0
wg-easy  | $ wg-quick up wg0
wg-easy  | $ wg syncconf wg0 <(wg-quick strip wg0)
wg-easy  | 2023-12-22T11:29:01.665Z WireGuard Config syncing...
wg-easy  | 2023-12-22T11:29:01.697Z WireGuard Config synced.
wg-easy  | 2023-12-22T11:29:09.565Z Server New Session: wOTr3J60OmsUTPpgo5I2gE7-SAp4q32m
```

**Comment by peterlewis** [comment]
Excellent. Thank you confirming.

**Comment by rusty1281** [comment]
I have just run the `latest` on my test and prod setup. Run with zero issue. LAN and WAN accessible as with v7.

**Comment by rusty1281** [comment]
> @rusty1281 could you please post your docker compose for comparison?

@pheiduck off here it is:

```
version: "3.5"
services:
  wgeasy:
    image: ghcr.io/wg-easy/wg-easy:latest
    network_mode: "bridge"
    container_name: wgeasy
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - /volume1/docker/wgeasy:/etc/wireguard
    environment:
      - WG_HOST=<public IP or DDNS address>
      - PASSWORD=<Wireguard web ui password>
    restart: always
```

**Comment by redstripes89** [comment]
I just siwtched to v9 of this image and can confirm working also.

```yaml
version: "3.9"
services:
  wireguard:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wireguard
    env_file: ./config/wireguard.env
    image: ghcr.io/wg-easy/wg-easy:9
    labels:
      traefik.docker.network: proxy
      traefik.enable: true
      traefik.http.routers.wireguard.entrypoints: websecure
      traefik.http.routers.wireguard.middlewares: default@file
      traefik.http.routers.wireguard.rule: Host(<removed>)
      traefik.http.routers.wireguard.service: wireguard
      traefik.http.routers.wireguard.tls: true
      traefik.http.routers.wireguard.tls.certresolver: tls_resolver
      traefik.http.services.wireguard.loadbalancer.server.port: 51821
    networks:
      proxy:
        ipv4_address: <removed>
    ports:
      - "<removed>:51820/udp"
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./wireguard:/etc/wireguard:rw
```

wireguard.env
```yaml
PASSWORD=<removed>
WG_PORT=<removed>
WG_HOST=<removed>
WG_DEFAULT_DNS=<removed>
```
