### ISSUE TITLE
Error after latest update (Version 10 & 11)

### ISSUE THREAD

**Issue by gVes** [wg-easy/wg-easy#752]
I am running wg-easy on docker. It's been working fine for the last year I would say. however after yesterday's latest update I am unable to connect, and unable to open GUI.

This is the error in the logs I am getting:

Node.js v18.19.0
node:events:495
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRNOTAVAIL: address not available 10.10.1.4:51821
    at Server.setupListenHandle [as _listen2] (node:net:1800:21)
    at listenInCluster (node:net:1865:12)
    at doListen (node:net:2014:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRNOTAVAIL',
  errno: -99,
  syscall: 'listen',
  address: '10.10.1.4',
  port: 51821
}
Node.js v18.19.0

**Comment by pheiduck** [comment]
Please read: https://github.com/wg-easy/wg-easy/blob/master/contributing.md
Before creating an issue.

**Comment by pheiduck** [comment]
Is this the only wg-easy instance you have running on your network?

**Comment by pheiduck** [comment]
See:  `Error: listen EADDRNOTAVAIL: address not available 10.10.1.4:51821`

**Comment by pheiduck** [comment]
Are the Ports configured on the firewall?
The IP most be one from your local network.

**Comment by gVes** [comment]
Hi, thanks for the quick reply. 

I forgot to mention I run a reverse proxy in front of the wg-easy, that’s why it’s advertising on my internal IP. This setup has been working fine until this morning after the update. 

Let me check if something has changed with the firewall in the morning. But besides that I have not changed anything server side. 🤷🏻‍♂️

**Comment by rookiezn** [comment]
Same issue for me. Hope following information would help.

### wg-easy image version

latest (10)

sha256:db6192701bd61579dc2bb686dd71ff39dd789ccd2ee391ee269f1b5a040d857d

### Host OS:

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

### Update steps:

```bash
sudo docker compose pull
sudo docker compose up -d --remove-orphans
sudo docker logs wg-easy
```

### docker-compose.yml

```yml
version: '3.8'
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx-proxy-manager'
    networks:
      - backbone
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81' # npm portal
      - '443:443'
      - '52230:51820/udp' # wireguard
      - '52231:52231/tcp' # wireguard portal
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    network_mode: service:nginx-proxy-manager
    volumes:
      - ./wireguard/config:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - WG_HOST=MY_HOST
      - WG_PORT=52230
      - WEBUI_HOST=MY_HOST
      - PORT=52231
      - PASSWORD=MY_PASSWORD
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_MTU=1420
      - WG_ALLOWED_IPS=10.8.0.0/24
      - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

networks:
  backbone:
    name: backbone
```

### Error logs

```
Node.js v18.19.0
2024-01-15T02:07:08.551Z WireGuard Loading configuration...
2024-01-15T02:07:08.563Z WireGuard Configuration loaded.
2024-01-15T02:07:08.563Z WireGuard Config saving...
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available MY_PUBLIC_IP:52231
    at Server.setupListenHandle [as _listen2] (node:net:1800:21)
    at listenInCluster (node:net:1865:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:2014:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRNOTAVAIL',
  errno: -99,
  syscall: 'listen',
  address: 'MY_PUBLIC_IP',
  port: 52231
}
```
