### ISSUE TITLE
Complete dark screen

### ISSUE THREAD

**Issue by organicnz** [wg-easy/wg-easy#886]
**Describe the bug**
Complete dark screen

**To Reproduce**
1. Go to 'docker-compose.yaml'
2. Edit Image to 'image: ghcr.io/wg-easy/wg-easy:nightly'
3. Reload web UI
4. See dark screen

**Expected behavior**
Web UI is expected with configs

**Screenshots**
<img width="1728" alt="Screenshot 2024-03-02 at 17 20 57" src="https://github.com/wg-easy/wg-easy/assets/4765090/f147c500-7f45-4b6a-b279-987dcfc5040d">

**Desktop (please complete the following information):**
 - OS: MacOs Sononma 14.4 Beta (23E5205c)
 - Browser Arc Version 1.31.0 (46662)

**Additional context**

`$ cat docker-compose.yml`

```
x-deploy: &default-deploy
  restart_policy:
    condition: unless-stopped
    delay: 5s
    window: 120s
  update_config:
    order: start-first

version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=vpn.example.com

      # ⚠️ Change the Web UI Password:
      - PASSWORD=xxxxx
    #image: wee jewel/wg-easy:nightly
    image: ghcr.io/wg-easy/wg-easy:nightly
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - ./.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    mem_limit: "16g"
    mem_reservation: "16g"
    cpus: 4
    cpuset: "0"
    networks:
     - no-zero-trust-cloudflared
     - web
    deploy:
      <<: *default-deploy

volumes:
  caddy_data:
  caddy_config:

networks:
   zero-trust-cloudflared:
     name: zero-trust-cloudflared
   web:
     external: true
     name: web
   no-zero-trust-cloudflared:
     external: true
     driver: bridge
     name: no-zero-trust-cloudflared
```
