### ISSUE TITLE
Client addresses from WG-easy to other Services.

### ISSUE THREAD

**Issue by ma-karai** [wg-easy/wg-easy#91]
WG-EASY is great :)

Is there a chance that i can get the clients into the docker network so that i would be able to see them in for example in pihole

Here is my current docker-compose.yaml

```
version: "3.8"
services:
  unbound:
    image: "klutchell/unbound"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    ports:
      - "5053:5053/udp"
    volumes:
      - ./unbound:/etc/unbound
    networks:
      wg-network:
        ipv4_address: 10.8.1.10
        
  pihole:
    depends_on: [unbound]
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      PIHOLE_DNS_: '10.8.1.10#5053;10.8.1.10#5053'
      WEBPASSWORD: 'password'
    # Volumes store your data between container upgrades
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
      wg-network:
        ipv4_address: 10.8.1.20 
    restart: unless-stopped
    
  wg-easy:
    depends_on: [unbound, pihole]
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=wg.mydomain.tld

      # Optional:
      - PASSWORD=password
      - WG_PORT=51820
      #- WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=10.8.1.20, 10.8.1.20

      - WG_ALLOWED_IPS= 0.0.0.0/0
      # figure out how to block
      # https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/

      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "8081:51821/tcp" # webinterface
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-network:
        ipv4_address: 10.8.1.30 

networks:
  wg-network:
    ipam:
      driver: default
      config:
        - subnet: 10.8.1.0/24

```
Which works, routed traffic goes to pihole, pihole gets the dns from ubound, all good, BUT, my client list only shows the ip for  for wg-easy
![image](https://user-images.githubusercontent.com/17119942/138905374-f04520ac-18d6-444a-9271-32ba174aa384.png)

Is there a way to setup the 3 apps, unbound + pihole +wg-easy to have certain ips, and the wg clients to assume ips in the same network.

e.g
unbound 10.8.0.10
pihole 10.8.0.20
wg-easy 10.8.0.30
wg-easy-clients 10.8.0.128/25
