### ISSUE TITLE
Tx/Rx chart not shown

### ISSUE THREAD

**Issue by cscholz** [wg-easy/wg-easy#927]
Traffic Chart bar not shown
I've updated my docker image created with docker-compose but the traffic bar is not shown.

How can I troubleshoot it?

**docker-compose.yml used**

```
version: "3.8"
volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=domain.tld

      # Optional:
      - PASSWORD=
      - WG_PORT=51820
      - WG_DEFAULT_DNS=10.8.0.1
      - WG_MTU=1380
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_PRE_UP=iptables -t nat -F; iptables -F;
      - WG_POST_UP=ip link set wg0 multicast on; iptables -t nat -I POSTROUTING 1 -s 10.8.0.0/24 -o wg0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2 (0 # Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - /etc/wireguard:/etc/wireguard
    network_mode: host
    dns:
      - 192.168.178.1
    dns_search:
      - local
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
```
