### ISSUE TITLE
Not working anymore after last update

### ISSUE THREAD

**Issue by kellertobias** [wg-easy/wg-easy#952]
**Describe the bug**
I had a working install with the last version to have no dark mode (didn't remember the version number) and basically just did a `docker-compose pull && docker-compose down && docker-compose up -d`. Now my clients do connect, however no bandwidth goes through anymore.

This is my compose file:

```
version: "3"
services:
  wireguard:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.wireguard.loadbalancer.server.port=51821"
      - "traefik.http.routers.wireguard.service=wireguard"
      - "traefik.http.routers.wireguard.rule=Host(`vpn.myserver.de`)"
      - "traefik.http.routers.wireguard.entrypoints=https"
      - "traefik.http.routers.wireguard.tls.certresolver=default"
      - "traefik.http.routers.wireguard.middlewares=forward-auth"

    environment:
      WG_HOST: vpn.myserver.de
      WG_PERSISTENT_KEEPALIVE: 25
      WG_DEFAULT_ADDRESS: 192.168.200.0
      WG_DEFAULT_ADDRESS_RANGE: 24
      WG_DEFAULT_DNS: 8.8.8.8, 1.1.1.1
      WG_POST_UP: iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
      WG_MTU: 1500
      UI_TRAFFIC_STATS: true

    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    volumes:
      - .:/etc/wireguard
    ports:
      - "0.0.0.0:51820:51820/udp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wireguard:
        ipv4_address: 172.43.0.1

networks:
  wireguard:
    driver: bridge
    ipam:
      config:
        - subnet: 172.43.0.0/24
          gateway: 172.43.0.254
```
