### ISSUE TITLE
wg-easy with pihole : how do I change this god awful name in Query Log in pi-hole?

### ISSUE THREAD

**Issue by yuukiAme** [wg-easy/wg-easy#971]
Following the [wiki on pi-hole and wg-easy](https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole) here. 

Here is my config for docker, docker compose and ran in Portainer.

```

version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=notarealdomain.dns.com # I changed this to my actual domain name.

 # Optional:
      - WG_PORT=51820 # The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.
      # check the conf file and set ENDPOINT :51824 , not :51820
      # - WG_MTU=1420 # The MTU the clients will use. Server uses default WG MTU.
      # - WG_ALLOWED_IPS=192.168.16.0/24, 10.0.1.0/24 # Allowed IPs clients will use.
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

      # ⚠️ Change the Web UI Password:
      - PASSWORD=SuperComplicatedPassword # When set, requires a password when logging in to the Web UI.

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3 # DNS server clients will use.
      - WG_DEFAULT_ADDRESS=10.8.0.x # Clients IP address range.
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51824:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2 # wg-easy IP Address in Pi-hole, you won't see 10.8.0.x in Query Log

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      # ⚠️ Change the Web UI Password:
      - WEBPASSWORD=SuperComplicatedPassword
    volumes:
      - '~/.pihole/etc-pihole:/etc/pihole'
      - './.pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3 # pi-hole IP Address

networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24
        - 
```

Everything is working fine. 

- I port forwarded the ports. 
- I can access the GUI, 
- scan the QR code 
- changed the ENDPOINT in my conf in Wireguard app.
- I can access the pi-hole on `10.8.1.3` and have consistent storage and config (new adlist added but after rebooting and it doesn't goes away)

# Now my question is how do I change this god awful name in Query Log in pi-hole?

![IMG_0544](https://github.com/wg-easy/wg-easy/assets/45681604/ee649ee6-adce-408f-becd-2c138e9e8eae)

the name that is `wg-easy.wg-easy_wg-easy` which is the IP address `10.8.1.2`

I tried changing in the DHCP setting inside pi-hole but it uses `.lan` and DHCP is not enabled. So it's not the right setting.

Any ideas?
